### PR TITLE
Fix: Do not needlessly show the Change Vote button

### LINKED ISSUE #3603: [Manage tokens - QA]  UI allows changing the vote when the voting has finished
## Description: 
The issue is that you shouldn't be allowed to click on "Change vote", as your first vote actually finished the voting phase. So the UI should not show you the option to Change vote anymore

## Steps to reproduce

1. Install the reputational Weight extension.
2. Open  manage tokens Actions
3. Add one token, fill in all fields and submit the form.
4. Go to the vote step and Support vote.
5. Change vote and oppose the vote.

https://www.figma.com/design/5V8pr7iMwXsT9L3VAZsmUt/Actions-%26-Motions?node-id=3615-356361&t=RydvhxIe7fdiiH1T-0

## Expected behaviour

* UI should not show you the option to Change your vote.

## Actual behaviour

* UI show the option to Change vote on the Vote step of manage tokens action.

https://github.com/user-attachments/assets/da262495-abda-4550-921d-ce902378121d

Uploading 51.mp4…

### PR DESCRIPTION
**Pull request by rumzledz**
## Description

It was a bit tricky to fix this because at first, I thought I could synchronise the rendering based on the loading state of the query responsible for this button. As I was debugging it, I thought that it's a perfect time to refactor the way we make UI updates for our motions.

If you think this piece of work needs to be done separately, please let me know.

### Minimise the reliance on action query polling and prefer real-time updates

Speaking for myself, it got a bit difficult to understand when polling starts and when they end. This is even made more complex due to the mixture of query polling and refetch. I have zero doubt that everyone here can understand this pattern if you thoroughly investigate it but the whole point of these changes is to super minimise this mystical approach.

This PR introduces subscription-based updates when it comes to keeping track of action updates. You can find these subscriptions being used in the `useGetColonyAction` hook.

The only 2 areas left where this polling mechanism is being used in:

- The retry button for the Transaction Error Content
- For the completed action form when an annotation is attached to a newly created action

### ActionContextProvider

We have this pattern where we would first retrieve the transaction hash to render our completed action component. Then we would prop drill the transaction ID down to our motion/multi-sig widgets so that we can retrieve the action again via another call to `useGetColonyActionQuery`. I thought this was redundant as we can just globally have a single source of truth for the current action we're dealing with. An exception to this rule is for Actions that are can have nested motions i.e. Advanced Payments. The MotionBox component for those are still calling `useGetColonyAction` because it is what it is!

### MotionStep and MultiSigStep

Our motions have steps that share the same name i.e. FinalizeStep. When debugging, of course it's just a matter of CMD + clicking the component or checking where it's being imported from to see which is which. But for the sake of making it easier to know which motion step you're looking at, at a glance, I have introduced namespacing.

```js
// Before
<FinalizeStep />

// After
<MotionStep.Finalize />
<MultiSigStep.Finalize />
```

## Testing

> [!NOTE]
> **Known motion-related issues that this PR has inherited**
> - [[Payments]Pending button stuck after claiming motion on the Finalize step/ or Claim button appears twice](https://github.com/JoinColony/colonyCDapp/issues/3859)
> - [[Dashboard - QA] Payment statuses aren't changed in the Recent activity table of Dashboard during performing any action with reputation](https://github.com/JoinColony/colonyCDapp/issues/3691)
> - [Unable to reclaim stake on a failed motion](https://github.com/JoinColony/colonyCDapp/issues/4004)
> - [Return stakes is failing](https://github.com/JoinColony/colonyCDapp/issues/4158)
> - [Return stakes is failing for a motion](https://github.com/JoinColony/colonyCDapp/issues/4158)

### 1. Voter Scenario (Reputation)

1. Enable the Reputation Extension
2. Create a Simple Payment motion
3. On the Staking step, Oppose and fully stake
4. Approve and fully stake
5. Approve and submit your vote
6. Verify that the Change Vote button does NOT appear ✅ 

### 2. Multiple Voters Scenario (Reputation)

1. Enable the Reputation Extension
2. Create a Simple Payment motion
3. On the Staking step, Oppose and fully stake
4. Copy the transaction's URL
5. Open an incognito window and connect Amy's wallet (Wallet 2)
6. Visit the transaction's URL
7. Approve and fully stake
8. Oppose and Submit your vote
9. Verify that the Change Vote button appears ✅ 
10. Click the Change Vote button
11. Verify that your vote is updated accordingly
12. As leela, approve and submit your vote
13. Verify that the Change Vote button does NOT appear ✅ 
14. As leela, reveal your vote
15. As amy, reveal your vote
16. Finalise the motion
17. Verify that you can finalise the motion

## The ANNOYING part and I'M SORRY

1. Please test motion creation and finalisation
- Advanced Payment via Staking behaviour should be representative of what you can expect for the Split & Staged payments via Staking due to shared logic
- One reputation motion should be representative of the rest of the actions due to shared logic
2. Please test multisig creation and finalisation
- Advanced Payment via Staking behaviour should be representative of what you can expect for the Split & Staged payments via Staking due to shared logic
- One multisig motion should be representative of the rest of the actions due to shared logic

Resolves #3603

### CODE REVIEW

**Review by rdig — CHANGES_REQUESTED** [review]
Everything seems fine, however, as I detailed below, I get stuck on the Advanced Payment release with reputation step.

Also:

> Voting step

I think you're confusing this with the "Staking" step, which made your testing steps a bit hard to follow


**Single voter:**


https://github.com/user-attachments/assets/4e55ffa4-9140-4b4a-86f7-28b6e176b070

**Multiple voters:**
[Screencast from 2025-01-24 13-53-47.webm](https://github.com/user-attachments/assets/6b585f1f-d0c3-4054-8f2f-f586f7bb323d)

**Advanced Payment via Staking:**
I am getting stuck on releasing via reputation. It might not be related to this, but I'm rejecting until we figure it out

https://github.com/user-attachments/assets/ce7e28ac-c109-4f86-8c9d-206f3e2f7463

Tried a couple of times, and still the same outcome:
image

**Comment by rumzledz** [comment]
Hey @rdig ! The issue you came across seems to be the one that was fixed on `master` recently. I have rebased my PR to incorporate that fix. When you get the chance, can you please test it again? 😄

**Review by rdig — APPROVED** [review]
Very nice! Yeah, you were right, after that rebase everything works as expected.

This was a lot of work and it seems to be working pretty well. Nicely done Romeo! :100: 

Single motion:
https://github.com/user-attachments/assets/9074cee8-c836-4273-836b-75a177cd7328

Motion with multiple users:
[Screencast from 2025-01-29 20-24-13.webm](https://github.com/user-attachments/assets/07922f0d-4303-4c49-9169-f1a69f0b4fb0)

Advanced payment:
https://github.com/user-attachments/assets/c4e7b6a7-e741-4cc1-956b-236ed9b8b25a

**Review by Nortsova — DISMISSED** [review]
Wooooow, @rumzledz , you did enormous work! ⭐  

Thanks for the investigation and refactoring everything!


All test cases working great, except Advanced Payment bug that we discussed today, but it is unrelated to current PR 🙌 

Voter scenario:
Change button is Not appear:
image

amy change vote:
image

after clicking "change vote" my vote changed to "support":
image

leela no change vote:
image

motion was finalized: 
image


advanced payments:
funding:
image
image

release:
image

Split payments:
image
image
image

staged payments:
image
image
image

Multisig:
image
image
image

**Review by Nortsova — DISMISSED** [review]
Retested after rebase and it still works as expected, nice job @rumzledz  ✨

File: src/components/v5/common/ActionSidebar/hooks/useGetActionFormData.ts [hunk 1]
```diff
@@ -390,19 +379,8 @@ const useGetActionData = (transactionId: string | undefined) => {
...
-    isInvalidTransactionHash,
-    loadingAction,
-    isMotion: !!action?.isMotion,
-    isMultiSig: !!action?.isMultiSig,
-    networkMotionState,
-    motionState,
-    expenditure,
-    loadingExpenditure,
-    startPollingForAction,
-    stopPollingForAction,
```
Comment (davecreaser) [inline src/components/v5/common/ActionSidebar/hooks/useGetActionFormData.ts:404]: Well, that's certainly simpler 🤣 🧹

File: src/components/v5/common/ActionSidebar/hooks/useGetColonyAction.ts [hunk 2]
```diff
@@ -186,29 +137,73 @@ const useGetColonyAction = (transactionHash?: string) => {
...
+    onData: updateAction,
+  });
+
+  useOnCreateMultiSigUserSignatureSubscription({
+    onData: updateAction,
+  });
+
+  useOnDeleteMultiSigUserSignatureSubscription({
+    onData: updateAction,
+  });
```
Comment (davecreaser) [inline src/components/v5/common/ActionSidebar/hooks/useGetColonyAction.ts:164]: ❤️ 🧹 

Very clean, I like this a lot

File: src/components/v5/common/ActionSidebar/partials/Motions/Motions.tsx [hunk 3]
```diff
@@ -8,24 +8,23 @@ import clsx from 'clsx';
...
 import useEnabledExtensions from '~hooks/useEnabledExtensions.ts';
 import { SpinnerLoader } from '~shared/Preloaders/index.ts';
-import { type MotionAction } from '~types/motions.ts';
 import { MotionState } from '~utils/colonyMotions.ts';
 import { formatText } from '~utils/intl.ts';
-import useGetColonyAction from '~v5/common/ActionSidebar/hooks/useGetColonyAction.ts';
 import UninstalledMessage from '~v5/common/UninstalledMessage/index.ts';
 import Stepper from '~v5/shared/Stepper/index.ts';
 
+import { MotionStep } from './MotionStep/index.ts';
```
Comment (davecreaser) [inline src/components/v5/common/ActionSidebar/partials/Motions/Motions.tsx:20]: I like this name spacing change a lot too 🐊

File: src/components/v5/common/ActionSidebar/partials/forms/CreateDecisionForm/hooks.ts [hunk 4]
```diff
@@ -51,14 +40,6 @@ export const useCreateDecision = (
...
           const safeDescription = sanitizeHTML(payload.description || '');
 
-          handleSaveAgreementInLocalStorage({
-            colonyAddress,
-            title: payload.title,
-            motionDomainId: Number(payload.createdIn),
-            description: safeDescription,
-            walletAddress,
-          });
-
```
Comment (davecreaser) [inline src/components/v5/common/ActionSidebar/partials/forms/CreateDecisionForm/hooks.ts:61]: Just a little confused as to why the deletions in this file were made - they seem slightly unrelated to the other changes?

Could you maybe give a brief reason why this has been removed? Thanks!

(for reference, I tested saving drafts of agreements, and they still work 👍 ⚡ )

**Review by davecreaser — APPROVED** [review]
Damn @rumzledz really really good stuff here, this is a huge simplification and a great refactor. Big fan of all the choices you made with subscriptions, the context and the name spacing. Stellar stuff! ⭐ 🌚 

I've just left one comment with something that confused me, maybe you could address that (not a problem, just something I didn't fully understand).

Tested the flows and everything is working great too, and the original bug is of course fixed. Nice one!

https://github.com/user-attachments/assets/8a9a2e78-7f83-4bf1-ab61-88d639ef05b7


https://github.com/user-attachments/assets/c22d2de1-dec7-4520-9e1b-93b2827d0705


Uploading Screen Recording 2025-01-30 at 18.42.10.mov…

File: src/components/v5/common/ActionSidebar/partials/forms/CreateDecisionForm/hooks.ts (hunk 4 above)
Comment (rumzledz) [reply src/components/v5/common/ActionSidebar/partials/forms/CreateDecisionForm/hooks.ts:61]: Thanks so much for reviewing @davecreaser ! I removed this because I found out that it's actually redundant 😅 This code is meant for the Save as draft button for an agreement and it's not meant to be here

Comment (davecreaser) [reply src/components/v5/common/ActionSidebar/partials/forms/CreateDecisionForm/hooks.ts:61]: Aha okay perfect. Thanks for the explanation!

**Review by rdig — DISMISSED** [review]
Re-approved

**Review by davecreaser — APPROVED** [review]
Reapproving after rebase ✅

**Review by Nortsova — APPROVED** [review]
Re reviewed 🙌  Everything still working ✅ 

Thank you 👍

**Review by rdig — APPROVED** [review]
