### PR TITLE
fix: show description tooltip in action form and completed action

### LINKED ISSUE #3739: [Payments] Tooltip is not displayed for the Description field in Payments.
## Steps to reproduce

1. Navigate to the Payment forms.
2. Locate the Description field.
3. Hover over the Description title.
4. Observe that no tooltip is displayed, unlike other fields in the form.

## Expected behaviour

* A tooltip should appear when hovering over the Description title, providing helpful guidance, such as:
"Provide a description for why this action is being performed, including any relevant details."

## Actual behaviour

* The tooltip does not appear for the Description title, leading to inconsistency with other fields and potential user confusion.

https://www.figma.com/design/5V8pr7iMwXsT9L3VAZsmUt/Actions-%26-Motions?node-id=2729-248940&node-type=frame&t=wt1IRZoIrw0LLxNk-0
image
image

### PR DESCRIPTION
**Pull request by bassgeta**
## Description

This PR adds back tooltips to the description field.

## Testing

I took some creative liberty to reword the tooltip in the completed action from:
```
Provide a description for why this action is being performed including any relevant details.
```

to

```
The description for why this action is being performed including any relevant details.
```
since it makes no sense grammatically otherwise :shrug: 

1. Try to create any action and hover the description field. Verify that the tooltip appears :eyes: 
image
2. Create the action and verify that the tooltip appears, but with slightly different text
image

## Diffs

**Changes** 🏗

* The ActionForm `DescriptionField` now renders the tooltip
* The completed action's `Description` row now render a slightly different tooltip

Resolves  #3739

### CODE REVIEW

File: src/components/v5/common/ActionSidebar/partials/Description/Description.tsx [hunk 1]
```diff
@@ -24,14 +24,14 @@ const Description: FC<DescriptionProps> = ({
     <ActionFormRow
       icon={Pencil}
       fieldName={DESCRIPTION_FIELD_NAME}
-      // Tooltip disabled to experiment with improving user experience
```
Comment (davecreaser) [inline src/components/v5/common/ActionSidebar/partials/Description/Description.tsx:27]: Looks like this experiment did not go as planned? 😆

**Review by davecreaser — APPROVED** [review]
Looking good! Tooltips showing as expected. I agree with the grammar too, makes a lot of sense like this 😄 

Screenshot 2024-12-17 at 09 10 43
Screenshot 2024-12-17 at 09 29 13

**Review by rumzledz — APPROVED** [review]
Grammatically and logically sound! 💯 

## Form editing

Screenshot 2024-12-17 at 20 42 42

## Completed Action

Screenshot 2024-12-17 at 20 43 13

**Review by jakubcolony — APPROVED** [review]
Looks great! 🎉 

image

File: src/components/v5/common/ActionSidebar/partials/Description/Description.tsx (hunk 1 above)
Comment (arrenv) [reply src/components/v5/common/ActionSidebar/partials/Description/Description.tsx:27]: I disagree, this tooltip should not have been added back in.
