### PR TITLE
[New Nav] Fix: Colony Sidebar UI adjustments

### LINKED ISSUE #3092: [New Navigation] Colony SIdebar UI adjustments
**Description**

This issue tackles UI-related issues for the Colony Sidebar

**Completion checklist**

* [ ] When the switcher is active on the desktop version, the highlight on the left side nav bar should remain active in the select state. Currently, it only shows on hover. Image
* [ ] Activity feed should be 'Activity' as per Figma across all sizes. Image

### PR DESCRIPTION
**Pull request by rumzledz**
## Description

colony sidebar adjustments

## Testing

1. Connect Dev Wallet 1
2. Visit the planex colony
3. Observe the Colony Sidebar and verify that Activity Feed is now called Activity
4. Click the Colony Switcher component and verify that it maintains its hover state when the colony switcher popover is present

Resolves #3092

### CODE REVIEW

**Review by mmioana — APPROVED** [review]
Awesome work @rumzledz 

Tested and can confirm the colony switcher remains active after clicking it

https://github.com/user-attachments/assets/4fa033fd-a192-4dff-8364-7c0762ac1a36

Also the `Activity feed` has been renamed to `Activity`
Before
Screenshot 2024-09-17 at 10 37 04
After
Screenshot 2024-09-17 at 11 05 03

File: src/components/v5/shared/Navigation/ColonySwitcher/ColonySwitcher.tsx [hunk 1]
```diff
@@ -36,9 +36,11 @@ const ColonySwitcher: React.FC<ColonySwitcherProps> = ({
       <Button
         ref={setTriggerRef}
         type="button"
-        className={clsx(sidebarButtonClass, className, '!py-[6px]', {
+        className={clsx(sidebarButtonClass, className, 'group !h-[45px]', {
```
Comment (Nortsova) [inline src/components/v5/shared/Navigation/ColonySwitcher/ColonySwitcher.tsx:39]: Do we really need the height here? Is it possible to reduce the padding or adjust it somehow? I’m not a big fan of fixed sizes, but it could be useful in certain cases. Right now, it's a 50/50 situation.

https://defensivecss.dev/tip/fixed-sizes/

File: src/components/v5/shared/Navigation/ColonySwitcher/ColonySwitcher.tsx [hunk 2]
```diff
@@ -55,7 +57,14 @@ const ColonySwitcher: React.FC<ColonySwitcherProps> = ({
         </section>
         {!isLogoButton && (
           <section>
-            <CaretUpDown className="h-3 w-auto flex-shrink-0 text-gray-400" />
+            <CaretUpDown
+              className={clsx(
+                'h-3 w-auto flex-shrink-0 text-gray-400 transition-colors group-hover:text-base-white',
```
Comment (Nortsova) [inline src/components/v5/shared/Navigation/ColonySwitcher/ColonySwitcher.tsx:62]: could we use size instead of height here please?

File: src/components/v5/shared/Navigation/Sidebar/Sidebar.tsx [hunk 3]
```diff
@@ -30,7 +30,7 @@ const Sidebar = React.forwardRef<HTMLDivElement, SidebarProps>(
         ref={ref}
         className={clsx(
           'top-[calc(var(--header-nav-section-height)+var(--top-content-height))]',
-          'z-sidebar hidden h-full w-fit flex-col items-start rounded-lg bg-gray-900 px-2 pb-4 pt-2 md:flex',
+          'z-sidebar hidden h-full w-fit flex-col items-start rounded-lg bg-gray-900 px-2 pb-[18px] pt-[14px] md:flex',
```
Comment (Nortsova) [inline src/components/v5/shared/Navigation/Sidebar/Sidebar.tsx:33]: Do we actually need to use pixels here? Can we sync with @melyndav on this?

For 14px, we could use pt-3.5, and for 18px, we can add a custom 4.5 value - https://tailwindcss.com/docs/customizing-spacing

Using specific pixel values feels less flexible to me

File: src/components/v5/shared/Navigation/Sidebar/partials/SidebarRouteItem/SidebarRouteItem.tsx [hunk 4]
```diff
@@ -102,7 +102,7 @@ const SidebarRouteItem: React.FC<SidebarRouteItemProps> = ({
               onKeyDown={noop}
               tabIndex={0}
               role="button"
-              className="flex aspect-square h-[22px] items-center justify-center rounded-[4px] transition-colors hover:bg-base-white md:hover:bg-gray-900"
+              className="mr-[1px] flex aspect-square h-[22px] items-center justify-center rounded-[4px] transition-colors hover:bg-base-white md:hover:bg-gray-900"
```
Comment (Nortsova) [inline src/components/v5/shared/Navigation/Sidebar/partials/SidebarRouteItem/SidebarRouteItem.tsx:105]: can we avoid height here please? Use padding instead for example

**Review by Nortsova — CHANGES_REQUESTED** [review]
Hey @rumzledz ! Thanks for this nice fixes! 

UI looks great! And seems you done a lot of work for navigation! Appreciate it 

sidebar-switcher

However I left a couple improvement comments, this tiny changes could help us made our UI more flexible :) 

Thank you! 🙏

**Review by Nortsova — APPROVED** [review]
Just spoke to @rumzledz , I am okay with this implementation as well and it was a reason for that. Thanks Romeo again for this hard pixel perfect work 👏

**Review by rdig — APPROVED** [review]
Seems to be working as described. Nicely done.

Screenshot from 2024-09-19 09-38-58
Screenshot from 2024-09-19 09-39-09
Screenshot from 2024-09-19 09-39-20
