### PR TITLE
Fix: go/colonyname redirects to 404 if no colony exists

### LINKED ISSUE #3809: `/go/colonyname` should redirect to 404 if the colony does not exist
## Steps to reproduce

1. Navigate to [http://localhost:9091/go/colonyname](http://localhost:9091/go/colonyname)

## Expected behaviour

* If no colony exists with this name, redirect to the 404 route

## Actual behaviour

* The "Go" page loads which suggests there is a colony with this name. This is potentially misleading if you have the URL slightly wrong.

Screenshot 2024-11-29 at 15 13 26

### PR DESCRIPTION
**Pull request by iamsamgibbs**
## Description

This PR fixes an issue where [http://localhost:9091/go/colonyname](http://localhost:9091/go/colonyname) would still load even if there is no colony with this name.

## Testing

Navigate to [http://localhost:9091/go/colonyname](http://localhost:9091/go/colonyname) you should be redirected to a 404 page.

As a logged in user with access to Planex, navigate to [http://localhost:9091/go/planex](http://localhost:9091/go/planex) you should be directed to the planex colony.

As a logged out user, navigate to [http://localhost:9091/go/planex](http://localhost:9091/go/planex) you should see the preview page.

## Diffs

**Changes** 🏗

* If no colonyAddress is found, redirect to 404 route

Resolves #3809

### CODE REVIEW

**Review by mmioana — APPROVED** [review]
Nice and simple fix on this issue @iamsamgibbs 🥇 

Navigating to http://localhost:9091/go/colonyname 

https://github.com/user-attachments/assets/a5d3bd21-4476-4570-a11f-fd65a6e31cde

Navigating to http://localhost:9091/go/planex as a logged out user

https://github.com/user-attachments/assets/96bd3a2c-6cec-40a6-9826-a66dd425409d

Navigating to http://localhost:9091/go/planex as a `leela`

https://github.com/user-attachments/assets/31b9b7fe-4813-4410-910a-0d79b504aaae

**Review by Nortsova — APPROVED** [review]
Nice catch @iamsamgibbs 👏 

Everything work as expected ✨ 
Colony without colony address:
image

Existed colony as leela:
image

Existed colony as logged out user:
image

File: src/components/frame/v5/pages/ColonyPreviewPage/ColonyPreviewPage.tsx [hunk 1]
```diff
@@ -146,6 +146,10 @@ const ColonyPreviewPage = () => {
     return <Navigate to={`/${colonyName}`} />;
   }
 
+  if (!colonyAddress) {
+    return <Navigate to={NOT_FOUND_ROUTE} />;
+  }
```
Comment (rumzledz) [inline src/components/frame/v5/pages/ColonyPreviewPage/ColonyPreviewPage.tsx:151]: Kuhlean ✨

**Review by rumzledz — APPROVED** [review]
Clean fix @iamsamgibbs ! ✨ 

## Accessing a page that does not exist

Screenshot 2025-01-08 at 01 00 29

## Accessing a Colony I am a member of

Screenshot 2025-01-08 at 01 00 42

## Accessing a Colony with my wallet disconnected

Screenshot 2025-01-08 at 01 01 02
