### PR TITLE
fix: fund expenditure via motion permission proofs and domains

### LINKED ISSUE #3705: [Expenditures] bug: all of voting reputation motions to fund an expenditure use the root domain to check for permissions
This is something I have discovered while rummaging around the codebase, but given [these few lines](https://github.com/JoinColony/colonyCDapp/blob/01bf277d15fb0bdd4295f20de1507e8167578e8e/src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/FundingModal/FundingModal.tsx#L232)
image

Makes it apparent that we always check for permissions in the root domain.
Why does this work? Well because we have another bug that always creates an expenditure in the root domain, so this works by chance :melting_face: 

## How to solve it
We need to create expenditures in the domain we are funding it from and then we need to realign the funding motion to get the action domain and get all the skill indices accordingly.

TBD: needs more info, if something is amiss, just ping @bassgeta

### PR DESCRIPTION
**Pull request by bassgeta**
## Description

This PR reimplements the fund expenditure via voting reputation saga so it uses the new helpers and it adds support for changing the funding motion created in domain.

## Testing

1. Install the voting reputation extension
2. Create an advanced payment as `leela` sending some funds to some recipients from `General`
image
3. Get to the funding step and fund it via Reputation
image
4. Fully support the motion, run `npm run forward-time 1` and try to finalize it. Then release it and verify that the funds were sent (`leela` had 396 at start, now she has 398 so hooray!)
image
image

ALright so funding from general works which is all fine, now let's check out 2 more cases

1. Create an advanced payment as `leela` sending some funds to some recipients from `Andromeda`
image
2. Get to the funding phase and choose `Reputation` as the decision method
image
3. Fully support it, run `npm run forward-time 1` and refresh the page. Finalize the motion, release the payment and verify that the changes are applied (for example check if Andromeda's funds were drained).

Now open the `FundingModal` file and change line 270
image
to `motionDomainId: selectedTeam.nativeId,`

1. Create an advanced payment as `leela` sending some funds to some recipients from `Andromeda`
image
2. Get to the funding step and choose `Reputation` as the decision method.
image
3. Verify that the motion gets created (we can't really check that it's been created in `Andromeda` in the UI) in Andromeda, by running this query
```
query MyQuery {
  getColonyAction(
    id: "0x8ec51ae8a1bf0d18500e6f29b737965f36ef522f0fb2fb32825f22eca886de29"
  ) {
    expenditure {
      nativeDomainId
      actions {
        items {
          isMotion
          motionDomainId
          motionData {
            nativeMotionDomainId
          }
        }
      }
    }
  }
}
```
and verify that the `nativeMotionDomainId` is 2 (ignore the blue blocks, it was testing time :D )
image
4. Fully support it, `npm run forward-time 1` and finalize it then release the payment. Verify that the funds were moved.

As an additional sanity check, install the multisig extension, set the threshold to 1, create an advanced payment and fund it via multisig.

## Diffs

**Changes** 🏗

* `fundExpenditureMotion` now uses the new helpers and supports creating the motion in a different domain than root

Resolves #3705

### CODE REVIEW

**Review by rumzledz — APPROVED** [review]
## 1. Leela has 396 CREDS before advanced payment from General

Screenshot 2024-11-19 at 20 03 55

## 2. Leela now has 398 CREDS after advanced payment from General

Screenshot 2024-11-19 at 20 09 36

## 3. Andromeda's funds before advanced payment

Screenshot 2024-11-19 at 20 13 38

## 4. Andromeda's funds after advanced payment

Screenshot 2024-11-19 at 20 19 55

## 5. Updated the motion payload

Screenshot 2024-11-19 at 20 24 18

## 6. Verifying that the nativeMotionDomainId is 2

Screenshot 2024-11-19 at 20 28 32

## 7. Verifying that funds were deducted from Andromeda

It was 98.9798 before.

Screenshot 2024-11-19 at 20 30 29

File: src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/FundingModal/FundingModal.tsx [hunk 1]
```diff
@@ -267,10 +267,10 @@ const FundingModal: FC<FundingModalProps> = ({
 
       const motionPayload: ExpenditureFundMotionPayload = {
         ...commonPayload,
-        colony,
-        motionDomainId: Id.RootDomain,
-        fromDomainFundingPotId: Id.RootDomain,
-        fromDomainId: Id.RootDomain,
+        motionDomainId: Id.RootDomain, // @TODO wire this up in the future
```
Comment (iamsamgibbs) [inline src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/FundingModal/FundingModal.tsx:270]: What is the reasoning for wiring this up in the future? Is it because there is no "Created In" field to select in the funding modal?

**Review by iamsamgibbs — APPROVED** [review]
Looks good to me! Nice job figuring this all out! I had problems with the motion widget getting stuck at various stages, but that is unrelated to this PR.

Balance before:
Screenshot 2024-11-19 at 13 21 08

I tested failing a motion, then passing one.

Screenshot 2024-11-19 at 13 24 18

Balance after (I think my stake for the failed motion got stuck as I couldn't claim it back, but it also hasn't disappeared as being lost...)

Screenshot 2024-11-19 at 13 25 04

Clicking the transaction from the UserHub opens the motion rather than the advanced payment.
 
Screenshot 2024-11-19 at 13 26 44

Andromeda amount before:

Screenshot 2024-11-19 at 13 38 59

Andromeda amount after:

Screenshot 2024-11-19 at 13 40 28

Then after the code edit:

Screenshot 2024-11-19 at 13 44 12

And final amount:

Screenshot 2024-11-19 at 13 46 09

File: src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/FundingModal/FundingModal.tsx (hunk 1 above)
Comment (bassgeta) [reply src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/FundingModal/FundingModal.tsx:270]: Yeah I've basically started wiring this up and when I tried changing the created in field, I figured out it's missing :D
So I left it as is, and we can decide when to add it in :shrug: but if this PR works, that should be trivial, as we're testing creating motions in all possible scenarios here :crossed_fingers:

**Review by Nortsova — APPROVED** [review]
I did all test steps and it seems to be working as expected, nice job 👍 

I also encountered issues with the Motion widget getting stuck. I then discovered that my network was set to 3G. After switching it to 'no throttling,' it started working better. However, we still need to investigate why the pending state sometimes gets stuck.

image
image
