### PR TITLE
Fix: Userhub transactions and notifications should not clear team

### LINKED ISSUE #3879: UserHub Transactions should not clear selected team
## Steps to reproduce

1. Make sure you have a team selected in the team switcher
2. Open the Userhub, switch to the transaction tab and click on one of the transactions

## Expected behaviour

* The action should open in the sidebar without clearing the selected team

## Actual behaviour

* The selected team is cleared

https://github.com/user-attachments/assets/465239d4-9023-4814-be0e-6c2319f5ac63

Might make sense to tackle this with #3000

### LINKED ISSUE #3880: UserHub Notifications should not clear the selected team
## Steps to reproduce

1. Make sure you have a team selected in the team switcher
2. Open the Userhub, switch to the notifications tab and click on one of the notifications

## Expected behaviour

* The action should open in the sidebar without clearing the selected team

## Actual behaviour

* The selected team is cleared

https://github.com/user-attachments/assets/61a9ba63-ae56-40da-bc6c-625c9cd2f911

### PR DESCRIPTION
**Pull request by iamsamgibbs**
## Description

This PR fixes an issue where the selected team is cleared when opening a notification or transaction from the userhub.

## Testing

* Step 1 - Create an action which will create both a notification and a transaction.
* Step 2 - On the dashboard, ensure you can selected a team.
* Step 3 - Select the action notification from the userhub, it should open and keep the selected team.
* Step 4 - Close the action sidebar and confirm the team is still selected. Now select the action transaction from the userhub. It should open and keep the selected team.

https://github.com/user-attachments/assets/f58fe6c2-a77d-41b9-9c9f-f6f25f1e5b5f

## Diffs

**Changes** 🏗

* Notification items now use `setQueryParamOnUrl` to use the transaction hash
* Grouped transactions now use `setQueryParamOnUrl` to use the transaction hash

Resolves #3879
Resolves #3880

### CODE REVIEW

**Review by Nortsova — APPROVED** [review]
Nice fix @iamsamgibbs ✨  

Works perfectly 👏 
team-filter-query

**Review by mmioana — APPROVED** [review]
Really nice fix @iamsamgibbs the selected team is not cleared upon opening a notification or a transaction 💯 

https://github.com/user-attachments/assets/edcf6fc2-cd12-49c1-a32a-bb94184b48af

File: src/components/common/Extensions/UserHub/partials/NotificationsTab/partials/Notification/Action/ActionNotification.tsx [hunk 1]
```diff
@@ -64,9 +65,17 @@ const ActionNotification: FC<NotificationProps> = ({
       ? window.location.pathname
       : `/${colony?.name}`;
 
-    navigate(`${path}?${TX_SEARCH_PARAM}=${transactionHash}`, {
-      replace: true,
-    });
+    navigate(
+      setQueryParamOnUrl({
```
Comment (rumzledz) [inline src/components/common/Extensions/UserHub/partials/NotificationsTab/partials/Notification/Action/ActionNotification.tsx:69]: ✨ ✨

**Review by rumzledz — APPROVED** [review]
Absolutely finessed ✨ 

preserve-domain
