### PR TITLE
Remove root/recovery permissions from selection on child domain

### LINKED ISSUE #1655: Manage permission options in child teams
## Steps to reproduce
- Open the Create a new action panel.
- Select a team to give the member permissions.
- You will see that you have the option to give `Owner` permissions to a member in a team. This should not be possible, as the `Owner` permissions should only give assignable in the Root/General.
- At the moment, doing so will give the following contract error `colony-bad-domain-for-role`.

## Expected behavior
- The `Owner` permission should not be a selectable option when you are awarding permissions in a child team.
- When selecting `Custom permissions`, `Root` and `Recovery` should not be options when within a child team

Figma Design - https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-v3?type=design&node-id=7292-382616&mode=design&t=GiZWxOFvBz8MwL40-11

image

## Actual behavior
- You are able to select the `Owner` permission option when giving permissions in a child team.
- You are able to select the `Root` and `Recovery` permission option when giving `Custom` permissions in a child team.
- The transaction is failing without any feedback to the user.

image

### PR DESCRIPTION
**Pull request by ArmandoGraterol**
Removed `Owner` set of permissions and `Root/Recovery` when the selected domain is not ROOT.

Screenshot 2024-01-04 at 19 56 11
Screenshot 2024-01-04 at 19 56 21

Resolves #1655

### CODE REVIEW

File: src/components/v5/common/ActionSidebar/partials/forms/ManagePermissionsForm/ManagePermissionsForm.tsx [hunk 1]
```diff
@@ -58,6 +62,15 @@ const ManagePermissionsForm: FC<ActionFormBaseProps> = ({ getFormOptions }) => {
...
 
+  const ALLOWED_PERMISSION_OPTIONS = PERMISSIONS_OPTIONS.map(
+    ({ options, ...rest }) => ({
+      ...rest,
+      options: options.filter(({ value }) =>
+        value === USER_ROLE.Owner ? Number(team) === Id.RootDomain : true,
+      ),
+    }),
+  );
+
```
Comment (rdig) [inline src/components/v5/common/ActionSidebar/partials/forms/ManagePermissionsForm/ManagePermissionsForm.tsx:73]: We need to make this a util, so that we don't repeat code

**Review by rdig — CHANGES_REQUESTED** [review]
Rejected just because of code repetition, once that's handled I'll approve it

**Review by jakubcolony — DISMISSED** [review]
I'm actually not too sure you can extract it very nicely, as one seems to be dealing with USER_ROLES whereas the other is ColonyRole. Maybe a comment explaining the logic would be good?

File: src/components/v5/common/ActionSidebar/partials/forms/ManagePermissionsForm/ManagePermissionsForm.tsx (hunk 1 above)
Comment (ArmandoGraterol) [reply src/components/v5/common/ActionSidebar/partials/forms/ManagePermissionsForm/ManagePermissionsForm.tsx:73]: You think so? Both functions are checking the same thing but they go about it differently (I.E. they are filtering different data structures)

**Review by rdig — DISMISSED** [review]
On a second look, my previous complaints turnout out to be unfounded. 

Approving. Nice Work.

File: src/components/v5/common/ActionSidebar/partials/forms/ManagePermissionsForm/ManagePermissionsForm.tsx [hunk 2]
```diff
@@ -1,5 +1,8 @@
+import { Id } from '@colony/colony-js';
 import React, { FC, useCallback } from 'react';
+import { useWatch } from 'react-hook-form';
 
+import { USER_ROLE } from '~constants/permissions';
```
Comment (jakubcolony) [inline src/components/v5/common/ActionSidebar/partials/forms/ManagePermissionsForm/ManagePermissionsForm.tsx:5]: Sorry to be a pain, but would you mind changing this to an enum if it's easy enough? It's one of those `as const` hacky type. No problem if not - can always open a maintenance issue for it.

**Review by jakubcolony — APPROVED** [review]

**Review by rdig — APPROVED** [review]
Re-approved, once again :)

File: src/components/v5/common/ActionSidebar/partials/forms/ManagePermissionsForm/ManagePermissionsForm.tsx (hunk 2 above)
Comment (ArmandoGraterol) [reply src/components/v5/common/ActionSidebar/partials/forms/ManagePermissionsForm/ManagePermissionsForm.tsx:5]: Oops, sorry man! I saw this comment after merging. I'll create the issue for this 👍

Comment (ArmandoGraterol) [reply src/components/v5/common/ActionSidebar/partials/forms/ManagePermissionsForm/ManagePermissionsForm.tsx:5]: There you go: https://github.com/JoinColony/colonyCDapp/issues/1739
