### PR TITLE
Fix: Open empty action sidebar on back navigation

### LINKED ISSUE #3890: [Actions - QA] Action drawer appears empty when retrying an action
## Steps to reproduce

1. Create any action.
2. Redo the action.

## Expected behaviour

* The action drawer should load properly with all required fields and options when retrying or starting a new action.

## Actual behaviour

* The action drawer opens but appears blank with no content.

image

https://github.com/user-attachments/assets/967ea393-dc5a-4530-bf06-2fb084318d94

### PR DESCRIPTION
**Pull request by mmioana**
Fix: Open empty action sidebar on back navigation

## Description

- The original issue stated the `Redo action` opens an empty action sidebar, even though this is no longer reproducible.

https://github.com/user-attachments/assets/10c051d0-35dd-4a05-9811-217f5f345ec2

- However there was an issue when opening a completed action, followed by the action sidebar back button and then using the browser back button a couple of time that would trigger the empty action sidebar being shown.

https://github.com/user-attachments/assets/42a3dac9-2982-47fd-a3e3-37950deecb5b

This was mainly caused by the fact that on back navigation, if the action sidebar was opened, we didn't react to the absence of a `txHash` and `actionType`. So my solution involved listening to location key changes (the `key` should update once the navigation history updates) and if there is no `txHash` and `actionType` present, to close the action sidebar. 
Additionally, we were mutating the history state needlessly by always performing a navigation without the `txHash` upon closing the action sidebar, even if there was no `txHash` set, so I have fixed that.

> [!IMPORTANT]
> If you do find a better solution or approach, please do reach out

**On this branch**

https://github.com/user-attachments/assets/71a1d0a5-53cc-4562-aaf4-2a1de46a42d6

## Testing

TODO: Let's test the browser back navigation no longer opens an empty action sidebar.

* Step 1. Go to http://localhost:9091/planex
* Step 2. Open a completed action. Click on the action sidebar back button
Screenshot 2025-01-23 at 14 06 48
* Step 3. Now click a couple of times on the browser back button
* Step 4. Check the empty action sidebar is not present
* Step 5. Try redoing an action
* Step 6. Click again on the browser back button
* Step 7. Create a new action and complete it (eg. Mint tokens)
* Step 8. Click again on the browser back button
* Step 9. Now let's create a new colony by running the `create-colony-url` script. Complete the colony creation form.
* Step 10. On the dashboard, go to the `Recent Activity` table
Screenshot 2025-01-23 at 14 10 50
* Step 11. Click on the `Create new action` button. Check it still opens the empty action sidebar.
* Step 12. Click on the back navigation. It should redirect to the colony creation form

**Please try also whatever other scenario comes to mind.**

## Diffs

**New stuff** ✨

* `useLocationKeyChange` hook

**Changes** 🏗

* Use the `actionSidebarInitialValues?.[ACTION_TYPE_FIELD_NAME]` in the `ColonyLayout`
* Get the current `txHash` and perform the navigation on action sidebar close only if it exists in `ActionSidebarContextProvider`

Resolves #3890

### CODE REVIEW

**Review by iamsamgibbs — APPROVED** [review]
Very nice, this is working great. I like the solution.

Testing it out, everything works as I assume it would:


https://github.com/user-attachments/assets/10108733-eab6-41c8-ade5-4c65ab65236b

Testing the colony creation flow:

https://github.com/user-attachments/assets/21a76e9d-3a70-4303-94cb-6ca03d9c84da

**Review by rdig — APPROVED** [review]
All good here. Nice solution!

https://github.com/user-attachments/assets/ab96109d-f42b-4026-8f08-ef0ffddb96e1

I did however find that on the Advance Payments action we don't have a back button. Is that expected, or just an oversight ?

image

File: src/context/ActionSidebarContext/ActionSidebarContextProvider.tsx [hunk 1]
```diff
@@ -62,10 +62,15 @@ const ActionSidebarContextProvider: FC<PropsWithChildren> = ({ children }) => {
   const selectedDomain = useGetSelectedDomainFilter();
   const selectedDomainNativeId = selectedDomain?.nativeId ?? '';
   const navigate = useNavigate();
+  const [searchParams] = useSearchParams();
+  const transactionId = searchParams?.get(TX_SEARCH_PARAM);
```
Comment (Nortsova) [inline src/context/ActionSidebarContext/ActionSidebarContextProvider.tsx:66]: One small comment here: we can rename transactionId to have "param" in its naming for more clarity at 70 line  🙌  But it is not necessary if you don't feel doing it 🫶 

```suggestion
  const transactionIdParam = searchParams?.get(TX_SEARCH_PARAM);
```

**Review by Nortsova — APPROVED** [review]
Awesome solution :) I am also faced with random Empty Sidebar sometimes but wasn't able to understand a pattern for it 😄 

Thank you ✨  It works great 
back-01
back-02
back-03
