### PR TITLE
Fix: URL showing capitalization on create colony confirmation

### LINKED ISSUE #2136: URL showing with capitalization
## Steps to reproduce

1. Create a new colony.
2. Proceed to the confirmation step.
3. Pay attention to the capitalization of the domain. 

## Expected behaviour

* There should be no capitalization on the domain URL.

## Actual behaviour

* There is capitalization on the domain URL.

image

### PR DESCRIPTION
**Pull request by iamsamgibbs**
## Description

The colony URL on the 'Create Colony' conformation should not allow capital letters. This PR enforces lowercase.

## Testing

1. Create a new colony.
2. Proceed to the confirmation step.
3. Pay attention to the capitalization of the domain.

## Diffs

**Changes** 🏗

* Colony URL is now lowercase

Resolves #2136

Screenshot 2024-04-04 at 16 13 30

### CODE REVIEW

**Review by rdig — APPROVED** [review]
Short and sweet!

File: src/components/common/Onboarding/wizardSteps/CreateColony/CreateColonyCardRow.tsx [hunk 1]
```diff
@@ -41,7 +41,7 @@ const CardRow = ({ updatedWizardValues, setStep }: CardRowProps) => {
     {
       title: 'navigation.admin.colonyDetails',
       text: colonyDisplayName,
-      subText: `app.colony.io/${colonyName}`,
+      subText: `app.colony.io/${colonyName.toLowerCase()}`,
```
Comment (rdig) [inline src/components/common/Onboarding/wizardSteps/CreateColony/CreateColonyCardRow.tsx:44]: This should actually use the global ENV level url value for the base domain.

Can you please update that as well ?

```suggestion
      subText: `${APP_URL.origin}/${colonyName.toLowerCase()}`,
```

**Review by rdig — APPROVED** [review]
Good to go, however please update the url value as well

File: src/components/common/Onboarding/wizardSteps/CreateColony/CreateColonyCardRow.tsx (hunk 1 above)
Comment (iamsamgibbs) [reply src/components/common/Onboarding/wizardSteps/CreateColony/CreateColonyCardRow.tsx:44]: 🤦‍♂️ I should have caught that, updating now!

**Review by rdig — APPROVED** [review]
Nicely done!

**Review by ArmandoGraterol — APPROVED** [review]
Same here, working as expected for me 👌
