### PR TITLE
fix: string for create agreement motion action type

### LINKED ISSUE #3986: [PROD] Agreement action type is different in the completed state
## Steps to reproduce

1. Navigate to a colony with a completed agreement. Or create a new agreement using permissions and complete the action.
2. Once in the completed state, the action type changes from 'Create agreement' to 'Decision'

## Expected behaviour

* The title of the agreement action should not change in the completed state. 

## Actual behaviour

* Once in the completed state, the agreement type changes from 'Create agreement' to 'Decision'.

Creation stage:
image

Completed state:
image

### PR DESCRIPTION
**Pull request by bassgeta**
## Description

Classic `en-actions.ts` mismatch :D 

## Testing

1. Install the voting reputation extension
2. Create an agreement motion, observe that in the form the action type is `Create agreement`
image
3. Verify that when it's created it still says `Create agreement` for the action type
image

## Diffs

**Changes** 🏗

* Fixed the string for `ColonyActionType.CreateDecisionMotion` in `en-actions.ts`

**Deletions** ⚰️

* unused translations objects in completed action

Resolves #3986

### CODE REVIEW

**Review by iamsamgibbs — APPROVED** [review]
Pesky strings, nice find:

Screenshot 2025-01-15 at 18 29 30

File: src/components/v5/common/CompletedAction/consts.ts [hunk 1]
```diff
@@ -1,17 +1,2 @@
...
-  [ColonyActionType.CreateDomain]: 'actions.createNewTeam',
-  [ColonyActionType.ColonyEdit]: 'actions.editColonyDetails',
-  [ColonyActionType.MintTokens]: 'actions.mintTokens',
-  [ColonyActionType.Payment]: 'actions.simplePayment',
-  [ColonyActionType.MoveFunds]: 'actions.transferFunds',
-  [ColonyActionType.UnlockToken]: 'actions.unlockToken',
-  [ColonyActionType.VersionUpgrade]: 'actions.upgradeColonyVersion',
-  [ColonyActionType.VersionUpgradeMotion]: 'actions.upgradeColonyVersion',
-  default: 'Action',
-};
```
Comment (mmioana) [inline src/components/v5/common/CompletedAction/consts.ts:17]: Thanks for removing an unused const 🧹

**Review by mmioana — APPROVED** [review]
Nice, now both the form and the completed action sidebar shows correctly `Create agreement` as the action type 💯 

Screenshot 2025-01-17 at 14 02 20
Screenshot 2025-01-17 at 14 02 29

**Review by Nortsova — APPROVED** [review]
Nice fix ✨  Now it works as expected

Form Action type:
image

Action type at completed action screen is still "Create agreement":
image
