### PR TITLE
Fix: Truncate Search Item label text

### LINKED ISSUE #3679: [Payments - QA] Display colony address according to design in payments
## Steps to reproduce

1. Open the Simple Payment form.
2. Enter the Colony address to search for a recipient.
3. Verify if the colony address display matches the approved design.

## Expected behaviour

* The colony address should be displayed as specified in the design

## Actual behaviour

* The colony address is truncated

https://www.figma.com/design/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-v3?node-id=1782-11883&node-type=frame&t=5sdisJVjGs5wzSIt-0
image
image

### PR DESCRIPTION
**Pull request by rumzledz**
## Description

Just a good ol' combination of text and address truncation.

truncate-address

## Testing

> [!IMPORTANT]
> ### 1. Update amy's username
> 1. Open the `UserAccountPage/hooks.tsx` file and update line 31 to:
> ```js
> return { canChangeUsername: true, daysTillUsernameChange };
> ```
> 2. Connect amy's wallet
> 3. Visit your profile page: http://localhost:9091/account/profile
> 4. Update your username to: 
> ```js
> QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ
> ```
> ### 2. Add a wallet address to the list of recippients
> 1. Visit the Wayne colony: http://localhost:9091/wayne
> 2. Copy its address
> 3. Visit the Planex colony: http://localhost:9091/planex
> 4. Bring up the Manage verified members form
> 5. Add Wayne's address and submit the form

### Verifying the truncation

1. Bring up the Simple payment form
2. Bring up the recipients list popover
3. Verify that:
 - the popover doesn't have a horizontal scrollbar
 - your new username is truncated
 - Wayne's contract address conforms to our address truncation
4. Change the action type to Manage Verified Members form
5. Set the Add/remove field to Remove members
6. Click the Select members field
7. Verify that:
 - the popover doesn't have a horizontal scrollbar
 - your new username is truncated
 - Wayne's contract address conforms to our address truncation

Resolves #3679

### CODE REVIEW

File: src/components/v5/common/ActionSidebar/partials/VerifiedMembersSelect/VerifiedMembersSelect.tsx [hunk 1]
```diff
@@ -160,7 +160,6 @@ const VerifiedMembersSelect: FC<VerifiedMembersSelectProps> = ({
                 'left-6 right-[1.9rem] w-auto': isMobile,
               })}
               showEmptyContent
-              shouldReturnAddresses
```
Comment (davecreaser) [inline src/components/v5/common/ActionSidebar/partials/VerifiedMembersSelect/VerifiedMembersSelect.tsx:163]: I think this _should_ return addresses, right?

I added `0x94CB46d05c2c88A7A053632865634a19Ba4C02fc` as a verified member, and when I search for it, it doesn't show up. If i remove the search term it does though.

**Review by davecreaser — CHANGES_REQUESTED** [review]
Nice one @rumzledz!

All looks good with the original bug:
Screenshot 2025-01-24 at 17 15 00
Screenshot 2025-01-24 at 17 15 21

Just having some trouble / questions about the change to not return addresses when searching verified members.

Screenshot 2025-01-24 at 17 17 40

Seems to me that in the PR from @iamsamgibbs it states that addresses _should_ show in the search for verified members?

File: src/components/v5/common/ActionSidebar/partials/VerifiedMembersSelect/VerifiedMembersSelect.tsx (hunk 1 above)
Comment (rumzledz) [reply src/components/v5/common/ActionSidebar/partials/VerifiedMembersSelect/VerifiedMembersSelect.tsx:163]: We might need to revisit this one @iamsamgibbs 👀

Comment (iamsamgibbs) [reply src/components/v5/common/ActionSidebar/partials/VerifiedMembersSelect/VerifiedMembersSelect.tsx:163]: 🫠 Strange! If it's in the list of options, it should return before even checking if `shouldReturnAddresses` is true or not (I also realise now that this name maybe isn't the most intuitive, when `shouldReturnAddresses` is true: if there are no matches in the list **and** the search value is address, then return the search value is the expected behaviour). Will join you in taking a look at this on Monday!

Comment (rumzledz) [reply src/components/v5/common/ActionSidebar/partials/VerifiedMembersSelect/VerifiedMembersSelect.tsx:163]: Okay I just rebased from `master` and that seems to have fixed it. So something funny must've happened on master but got recently fixed or something 😅  @davecreaser @iamsamgibbs can I please ask you to try it again?

Comment (rumzledz) [reply src/components/v5/common/ActionSidebar/partials/VerifiedMembersSelect/VerifiedMembersSelect.tsx:163]: Oh and @davecreaser we removed the `shouldReturnAddresses` prop for the `VerifiedMembersSelect` function because we don't want to show the unknown item if it's not being returned from the search results

**Review by davecreaser — APPROVED** [review]
Nice one @rumzledz

Everything is still working, and the address now shows up in the search!

Screenshot 2025-01-28 at 12 05 36
Screenshot 2025-01-28 at 12 05 46
Screenshot 2025-01-28 at 12 07 23
Screenshot 2025-01-28 at 12 08 35

**Review by iamsamgibbs — APPROVED** [review]
Nice job, this is all working great now!

Adding an address:
Screenshot 2025-01-28 at 18 15 23

Trying to remove an address when it is not already a verified member:
Screenshot 2025-01-28 at 18 15 16

Removing an address that HAS actually been verified:
Screenshot 2025-01-28 at 18 22 07
 
And simple payments:
Screenshot 2025-01-28 at 18 22 21

Screenshot 2025-01-28 at 18 22 25

Lets get it merged!
