### PR TITLE
Fix multisig widget loading state

### LINKED ISSUE #3422: [Multi-sig] bug: when the action is loading, you get double spinners popping in
## Steps to reproduce

1. Create any Multi-sig action
2. Observe spinners when it starts loading
[multi-sig-permissions-3393.webm](https://github.com/user-attachments/assets/f0cce1f1-937f-4ce9-9094-18d7d45c857c)

## Expected behaviour

* We should display a loading skeleton and solve these spinners popping in
[Figma link](https://www.figma.com/design/5V8pr7iMwXsT9L3VAZsmUt/Actions-%26-Motions?node-id=2729-248940&node-type=frame&t=aYkGZam3rlKkpzZ9-0)
image

## Actual behaviour

* Spinner > component > spinner > component

### PR DESCRIPTION
**Pull request by davecreaser**
## Description

- Fix the loading state of the multisig action sidebar widget to match the Figma designs. Previously it showed an awkward spinner in the top left of the sidebar, whereas it should really be matching the general loading state for this widget.

- As part of this work, I refactored that general action sidebar loading component a little and extracted the widget part into a more reusable component so it could also be used here.

Figma: https://www.figma.com/design/5V8pr7iMwXsT9L3VAZsmUt/Actions-%26-Motions?node-id=26993-210663&t=jBC7dx6GQVefvIes-4

## Testing

* Step 1. Install the multisig extension
* Step 2. Make any multisig action
* Step 3. Load that action so that it opens in the sidebar. As it loads, check the loading state. I used a screen recorder, and also changed line 35 of `src/components/v5/common/ActionSidebar/partials/MultiSigSidebar/MultiSigSidebar.tsx` to `if (true)` to force the loading state.

https://github.com/user-attachments/assets/cb0ceb73-4dcc-49ba-b212-581189845fc2

Screenshot 2024-11-29 at 17 43 44

## Diffs

**New stuff** ✨

* New component `ActionSidebarWidgetLoadingSkeleton`

**Changes** 🏗

* Refactored ActionSidebarLoadingSkeleton
* Changed the loading behaviour of the MultiSigSidebar

Resolves #3422

### CODE REVIEW

**Review by iamsamgibbs — APPROVED** [review]
Nice job pulling out the loading skeleton to make it reusable, all working as expected.

https://github.com/user-attachments/assets/cbd85fd6-b8cf-4828-814b-20af7026dcc6

File: src/components/v5/common/ActionSidebar/partials/ActionSidebarWidgetLoadingSkeleton/ActionSidebarWidgetLoadingSkeleton.tsx
Comment (mmioana) [inline src/components/v5/common/ActionSidebar/partials/ActionSidebarWidgetLoadingSkeleton/ActionSidebarWidgetLoadingSkeleton.tsx:1]: I really love this component, nice job refactoring it 🙌 
To fully (or almost fully) match `Figma` we should replace all `rounded-md` with `rounded`. 
Also can we please replace `[10px]` with `2.5` and `[1.125rem]` with `4.5?

File: src/components/v5/common/ActionSidebar/partials/ActionSidebarWidgetLoadingSkeleton/ActionSidebarWidgetLoadingSkeleton.tsx [hunk 1]
```diff
@@ -0,0 +1,66 @@
...
+      <div className="flex w-full items-center gap-4">
+        <div className="flex items-center justify-center">
+          <div className="h-[10px] w-[10px] rounded-full bg-gray-100" />
+        </div>
+        <div className="h-6 w-14 overflow-hidden rounded-full skeleton" />
+      </div>
+      <div className="ml-[1.625rem] overflow-hidden rounded-lg border border-gray-200">
+        <div className="flex w-full gap-2 border-b border-gray-200 bg-gray-50 p-[1.125rem] py-3">
+          <div className="h-4 w-4 overflow-hidden rounded-md skeleton" />
+          <div className="h-4 w-52 overflow-hidden rounded-md skeleton" />
```
Comment (mmioana) [inline src/components/v5/common/ActionSidebar/partials/ActionSidebarWidgetLoadingSkeleton/ActionSidebarWidgetLoadingSkeleton.tsx:17]: Here actually we should replace `rounded-md` with `rounded-full`

File: src/components/v5/common/ActionSidebar/partials/ActionSidebarWidgetLoadingSkeleton/ActionSidebarWidgetLoadingSkeleton.tsx [hunk 2]
```diff
@@ -0,0 +1,66 @@
...
+        </div>
+        <div>
+          <div className="flex flex-col gap-3 bg-base-white p-[1.125rem]">
```
Comment (mmioana) [inline src/components/v5/common/ActionSidebar/partials/ActionSidebarWidgetLoadingSkeleton/ActionSidebarWidgetLoadingSkeleton.tsx:20]: And here we should replace `gap-3` with `gap-2`

**Review by mmioana — CHANGES_REQUESTED** [review]
Amazing job on this one @davecreaser! Thumbs up for refactoring the loading skeleton for the action sidebar 🥇 

Created a simple payment with `Multi-sig`
Screenshot 2024-12-02 at 18 06 55

And the loading skeleton shown on the action sidebar

https://github.com/user-attachments/assets/51ab5933-9222-4051-8e48-c939af5b25a9


I left a few refactoring comments to match as best as possible the `Figma` designs, if you could please tackle them 🙏

**Review by bassgeta — DISMISSED** [review]
Left one potential improvement idea, but no need to do it here (we can open up another issue to unify all these skeletons), but overall nice job :100: 
image

File: src/components/v5/common/ActionSidebar/partials/ActionSidebarWidgetLoadingSkeleton/ActionSidebarWidgetLoadingSkeleton.tsx (hunk 1 above)
Comment (davecreaser) [reply src/components/v5/common/ActionSidebar/partials/ActionSidebarWidgetLoadingSkeleton/ActionSidebarWidgetLoadingSkeleton.tsx]: Looking at the Figma it looks like this should actually just be `rounded` (4px border radius). Rounded full would be too much here I think.

**Review by iamsamgibbs — APPROVED** [review]
Eagle eye fixes all look good!

Screenshot 2024-12-03 at 17 27 33

**Review by bassgeta — APPROVED** [review]
Still looking good :ok_hand: 
image

**Review by rumzledz — APPROVED** [review]
Beautiful result @davecreaser ! No redundant loaders in sight! Pew pew!

ms-loader

**Review by mmioana — APPROVED** [review]
Thanks for your super fast changes @davecreaser 🎉 All good from my side

https://github.com/user-attachments/assets/29f56fb5-87f4-4971-a1bb-347ef4b96feb
