### PR TITLE
Fix: Unable to reveal motion oppose

### LINKED ISSUE #3258: Unable to reveal motion oppose vote
This issue is reproducible on master and in production.

## Steps to reproduce

1. Create a motion
2. Stake it on both sides.
3. Vote oppose.

## Expected behaviour

Reveal step shows your oppose vote and you are able to reveal it.

## Actual behaviour

You are presented with the following message:

> No reveal required:
> You did not vote so do not need to reveal. Please wait for all required voters to reveal or the reveal stage to end.

Screen recording of the issue:

https://github.com/user-attachments/assets/98c65d26-26d5-40a1-a5b0-82069e9ebbe1

For reference, this is a recording from a different PR that shows the correct behaviour when voting oppose:

https://github.com/user-attachments/assets/74f8d7b7-a651-4018-8b98-b9c49b6d9b2c

### PR DESCRIPTION
**Pull request by iamsamgibbs**
## Description

This PR addresses an issue introduced by #3108 which caused oppose motions to be revealed. `!!userVote` was incorrectly validating MotionVote.Nay as false and has been replaced with a more explicit check `(userVote === MotionVote.Nay || userVote === MotionVote.Yay)`.

Completely unrelated, but I also fixed up a tiny key issue with the ActionSidebarLoadingSkeleton which was causing console errors.

## Testing

* Step 1 - Install the reputation voting extension
* Step 2 - Create a motion, stake it on both sides.
* Step 3 - Vote to oppose the motion. When the sidebar updates to the reveal stage, it should be possible to reveal your oppose vote.

https://github.com/user-attachments/assets/b5a1a6d8-c67e-47a1-9f72-3eac7b294c71

Compared to master:

https://github.com/user-attachments/assets/20606992-f1e7-4bdb-8af8-13c68df450a7

## Diffs

**Changes** 🏗

* Fixed vote reveal if statement
* Added missing ActionSidebarLoadingSkeleton keys

Resolves #3258

### CODE REVIEW

**Review by rdig — APPROVED** [review]
Everything works as expected. Nicely done

Screenshot from 2024-10-08 12-00-21
Screenshot from 2024-10-08 12-00-41
Screenshot from 2024-10-08 12-01-23
Screenshot from 2024-10-08 12-01-34
Screenshot from 2024-10-08 12-01-39
Screenshot from 2024-10-08 12-01-43

However I did pick up on this:

Screenshot from 2024-10-08 12-02-06
Screenshot from 2024-10-08 12-02-12

The "pending" button renders way to close to the total line entry

File: src/components/v5/common/ActionSidebar/partials/ActionSidebarLoadingSkeleton/ActionSidebarLoadingSkeleton.tsx [hunk 1]
```diff
@@ -23,7 +23,8 @@ const ActionSidebarLoadingSkeleton = () => {
       </div>
       <div>
         {new Array(7).fill(0).map((_, index) => (
-          <div className="mt-2 flex w-full max-w-[25rem] gap-2">
+          // eslint-disable-next-line react/no-array-index-key
+          <div key={index} className="mt-2 flex w-full max-w-[25rem] gap-2">
```
Comment (jakubcolony) [inline src/components/v5/common/ActionSidebar/partials/ActionSidebarLoadingSkeleton/ActionSidebarLoadingSkeleton.tsx:27]: Nice one 👍

**Review by jakubcolony — APPROVED** [review]
LGTM 👍 

image
image

image
image
image

image

**Review by davecreaser — APPROVED** [review]
Nice quick fixes @iamsamgibbs, thanks for picking this up!

Works as expected:
Screenshot 2024-10-09 at 18 07 57
Screenshot 2024-10-09 at 18 08 21
