### PR TITLE
Fix: Prevent stale response data from useGetColonyForNotificationQuery

### LINKED ISSUE #3576: QA Notifications: Colony name change doesn't show in notifications tab within the userhub
## Steps to reproduce

1. Create a new action to edit the colony.
2. Change the colony logo and the name.
3. Complete the transaction using permissions. 
4. Create a transfer fund action. Complete the action with any information you wish.
5. A notification will be triggered in the user pill within the top right user header. 
6. Open the user hub, and select the notifications tab.
7. Note, the name and avatar of the colony the notification is sent from is not changed even after creating a transaction with the new colony name. 

## Expected behaviour

* The colony name and avatar when updated should also be updated in the Colony. 

## Actual behaviour

* The old colony name and avatar remain in the UI and do not match the Colony switcher or other areas like the dashboard displaying the same information.

image

_** Note: Even leaving the colony and switching to another and coming back doesn't update the information within the user hub and the old colony name and avatar still appear._

_**Extra note: A forced refresh worked**_

image

### PR DESCRIPTION
**Pull request by rumzledz**
## Description

I updated `useGetColonyForNotificationQuery`'s fetch policy to cache-and-network to ensure data freshness. 

fetchpolicy

## Testing

1. Edit the Colony's name and logo
2. ⚠️  **IMPORTANT** Don't refresh the page
3. Complete a transfer fund action via Permissions
4. ⚠️ **IMPORTANT** Don't refresh the page
5. Wait for the notification to come through
6. Verify that the latest Colony name and logo are shown

Resolves #3576

### CODE REVIEW

File: src/components/v5/common/ActionSidebar/ActionSidebar.tsx [hunk 1]
```diff
@@ -314,7 +314,7 @@ const ActionSidebar: FC<PropsWithChildren<ActionSidebarProps>> = ({
       </div>
       {isLoading && <ActionSidebarLoadingSkeleton />}
       <div
-        className={clsx('flex flex-grow', {
+        className={clsx('flex flex-grow overflow-y-auto', {
```
Comment (mmioana) [inline src/components/v5/common/ActionSidebar/ActionSidebar.tsx:317]: @rumzledz I think this is already added in your #3621 PR, so let's remove it from here 👍 or base this branch on top of the other one

**Review by mmioana — APPROVED** [review]
Awesome fix @rumzledz now the colony details are updating also in the notifications area without page refresh 💯 

Screenshot 2024-11-05 at 10 26 39
Screenshot 2024-11-05 at 10 27 23
Screenshot 2024-11-05 at 10 28 11
Screenshot 2024-11-05 at 10 28 18

**Review by rdig — APPROVED** [review]
Did everything via a recording to prove no page refreshes involved.

Everything works as expected now. Very nicely done!


https://github.com/user-attachments/assets/88d2b07a-d5a2-4301-b147-f8f471d38ae2

**Review by iamsamgibbs — APPROVED** [review]
Nice job, works great!

Screenshot 2024-11-06 at 09 47 36
