### PR TITLE
[Multi-Sig] fix: user popovers not displaying inherited permissions

### LINKED ISSUE #2783: [Multi-Sig] User Info Popover Icons do not account for inherited permissions
## Steps to reproduce

Step 1 - Assign a user payer permissions in a sub domain
Step 2 - Assign the same user owner permissions in general
Step 3 - Open their user info popover, hover over the permissions icon for the sub domain.

## Expected behaviour

* The "admin" permissions tooltip should show as whilst they only have the payer permissions in the sub-domain, they have inherited the other admin permissions from the root domain.
* Inherited permissions should show with the text "(inherited)" after the relevant permission.

image

## Actual behaviour

* The "payer" permissions tooltip shows

## Suggestions (optional)

This same issue occurs when assigning multi-sig permissions.

 
Screenshot 2024-07-26 at 14 27 32

Screenshot 2024-07-26 at 14 27 36

Screenshot 2024-07-26 at 14 27 40

### PR DESCRIPTION
**Pull request by bassgeta**
## Description

What it says, since inherited roles aren't in the database, we need to do some workarounds on the UI for them.
Paired this w/ @mmioana :hand: 

## Testing

I think the following cases should cover everything.

Preparations: 

1. Give `amy` the architecture role in `General`
image
2. Give `amy` the funding role in `Andromeda`
image
3. Give `fry` the `Payer` role set in `General`
image
4. Give `fry` the `Admin` role set in `Andromeda`
5. Give `leela` the `Architecture` role in `Andromeda`
image
6. Install the Multi-Sig extension
7. Give `leela` the `Owner` Multi-Sig role
image
8. Give `amy` `Funding` Multi-Sig role in `Andromeda`
image
9. Give `amy` the `Architecture` Multi-Sig role in `General`
image

Testing:
1. Verify that `leela` has `Owner` bundle in general and `Owner` in Multi-Sig
image
image
2. Verify that `leela` has `Architecture` in `Andromeda` but inherits all owner roles except recovery and root
image
3. Verify that `amy` has `Architecture` in `General` and Multi-Sig `Architecture` in `General`
image
image
4. Verify that `amy` has `Funding` and `Architecture (inherited)` in `Andromeda` (same for Multi-Sig)
image
image
5. Verify that `amy` has just `Architecture (inherited)` in any other subdomain (same for Multi-Sig)
image
image
6. Verify that `fry` has the `Payer` bundle in `General`
image
7. Verify that `fry` has the `Admin` bundle in `Andromeda`
image
8. Verify that `fry` has 3 inherited permissions in any other subdomain
image

## Diffs

**Changes** 🏗

* Decoupled the `DomainPermissionsList` component
* Decoupled the `PermissionTooltip` component
* And also decoupled the `PermissionTooltipContent` component :D 
* If a user has only non inherited roles, display `This member has the {role} permission bundle that includes the following permissions:`, otherwise display `This member has the following permission types:`
* Display the `(inherited)` appendix for inherited roles

Resolves  #2783

### CODE REVIEW

File: src/components/v5/shared/UserInfoPopover/partials/PermissionTooltip/PermissionTooltipContent.tsx [hunk 1]
```diff
@@ -0,0 +1,76 @@
...
+        {userPermissions.map((permission) => (
+          <li key={permission}>
+            {rolePrepend}
+            {ColonyRole[permission]}
+          </li>
+        ))}
+        {userInheritedPermissions.map((permission) => (
+          <li key={`inherited.${permission}`}>
+            {rolePrepend}
+            {ColonyRole[permission]} (inherited)
```
Comment (Nortsova) [inline src/components/v5/shared/UserInfoPopover/partials/PermissionTooltip/PermissionTooltipContent.tsx:67]: it would be good to have i18n translation for "inherited"

**Review by Nortsova — APPROVED** [review]
Thanks @bassgeta  and @mmioana , awesome work!  🙌 

Can confirm that leela has owner permissions in general:
image
and in MultiSig:
image
leela has Architecture in Andromeda but inherits all owner roles except recovery and root:
image

amy has Architecture in General and Multi-Sig Architecture in General
image
image

amy has Funding and Architecture (inherited) in Andromeda (same for Multi-Sig)
image
image

amy has just Architecture (inherited) in any other subdomain (same for Multi-Sig)
image
image

fry has the Payer bundle in General
image

fry has the Admin bundle in Andromeda
image

fry has 3 inherited permissions in any other subdomain
image

File: src/components/v5/shared/UserInfoPopover/partials/DomainPermissionList/DomainPermissionList.tsx [hunk 2]
```diff
@@ -0,0 +1,120 @@
...
+                      }
+                      isRootDomain={isRootDomain}
+                      isMultiSig
+                    />
+                  )}
+                  <Tooltip
+                    placement="top"
+                    className="flex items-center justify-end text-sm font-normal text-gray-900"
+                    tooltipContent={
+                      <Numeral value={reputationRaw} suffix=" pts" />
```
Comment (rumzledz) [inline src/components/v5/shared/UserInfoPopover/partials/DomainPermissionList/DomainPermissionList.tsx:101]: Doesn't have to dealt with here since it can also be addressed during the `master` rebase but just a gentle reminder that this should have the decimals value:
```ts
const { colony } = useColonyContext();

<Numeral
  value={reputationRaw}
  suffix=" pts"
  decimals={getTokenDecimalsWithFallback(colony.nativeToken.decimals)}
/>;
```

File: src/components/v5/shared/UserInfoPopover/partials/PermissionTooltip/PermissionTooltipContent.tsx [hunk 3]
```diff
@@ -0,0 +1,76 @@
...
+        {userPermissions.map((permission) => (
+          <li key={permission}>
+            {rolePrepend}
+            {ColonyRole[permission]}
+          </li>
+        ))}
+        {userInheritedPermissions.map((permission) => (
+          <li key={`inherited.${permission}`}>
+            {rolePrepend}
+            {ColonyRole[permission]} {formatText(MSG.inheritedAppendText)}
```
Comment (rumzledz) [inline src/components/v5/shared/UserInfoPopover/partials/PermissionTooltip/PermissionTooltipContent.tsx:67]: NOT a change request! This can also be rewritten as:

```ts
const MSG = defineMessages({
  inheritedPermission: {
    id: `${displayName}.inheritedPermission`,
    defaultMessage: '{permission} (inherited)',
  }
});

formatText(MSG.inheritedPermission, { permission: ColonyRole[permission] });
```

**Review by rumzledz — APPROVED** [review]
Thorough test setup @bassgeta ! By following the steps, I can confirm that the permissions and inherited permissions are being properly labelled and displayed for Leela, Amy & Fry. Awesome stuff! ✨ 

**Amy**
2950_amy

**Leela**
2950_leela

**Fry**
2950_fry

The other comments I left are NOT change requests 👌

File: src/components/v5/shared/UserInfoPopover/partials/PermissionTooltip/PermissionTooltip.tsx [hunk 4]
```diff
@@ -0,0 +1,77 @@
...
+    if (isRootDomain) {
+      return [];
+    }
+
+    return userPermissionsInParentDomain
+      .filter(
+        (permission) =>
+          permission !== ColonyRole.Root && permission !== ColonyRole.Recovery,
+      )
+      .filter((permission) => !userPermissionsInDomain.includes(permission));
```
Comment (davecreaser) [inline src/components/v5/shared/UserInfoPopover/partials/PermissionTooltip/PermissionTooltip.tsx:45]: Nitpick, but we could just combine these two filters into one so that it doesn't loop over the array twice. Could also just have userInheritedPermissions be calculated inside a useMemo so that the function isn't called on each render.

**Review by davecreaser — APPROVED** [review]
Nicely done guys! The code is actually much more readable now too, along with the issue being solved :)

I just left one comment about an unnecessary double loop, but other than that all good to me.

Also really nice testing steps, made it a breeze to test. Here's some fun screenshots of my tests giving exactly what was expected:

Screenshot 2024-08-19 at 13 53 59
Screenshot 2024-08-19 at 13 54 04
Screenshot 2024-08-19 at 13 54 37
Screenshot 2024-08-19 at 13 55 14
Screenshot 2024-08-19 at 13 55 19
Screenshot 2024-08-19 at 13 55 47
Screenshot 2024-08-19 at 13 55 51
Screenshot 2024-08-19 at 13 56 15
Screenshot 2024-08-19 at 13 56 28
Screenshot 2024-08-19 at 13 56 51
Screenshot 2024-08-19 at 13 57 09
Screenshot 2024-08-19 at 13 57 19
