### PR TITLE
Fix actions count not respecting selected domain filter

### LINKED ISSUE #1542: Dashboard widgets not showing correct data
## Description

When filtering by a team on the dashboard in production, the total actions shows the root total and not the total specific to the team.

This is a regression introduced to a PR Thomas completed before launch. 

Widget in question when a filter is active:

image

The expected behaviour for the user is when filtering by a team on the dashboard using the top team filter next to the breadcrumbs, the total actions widget displays the number of actions for that specific team filtered. 

NB: The 'all teams' and 'root' filters looks to be working correctly.

### PR DESCRIPTION
**Pull request by jakubcolony**
### Colony dashboard

https://github.com/JoinColony/colonyCDapp/assets/112586815/8bd01ca4-5a6e-48b6-9a9f-dce73663dce7

### Activity feed

https://github.com/JoinColony/colonyCDapp/assets/112586815/95c7f85b-83c0-451b-bf19-df7525287e6c

Changes:
- Some renaming of `team` to `domain` for consistency
- `useActionsCount` - new shared hook for getting actions count

Resolves #1542

### CODE REVIEW

File: src/hooks/useActionsCount.ts [hunk 1]
```diff
@@ -0,0 +1,61 @@
...
+              {
+                fromDomainId: {
+                  eq: getDomainDatabaseId(colonyAddress, domainId),
+                },
+              },
+              {
+                motionDomainId: { eq: domainId },
+              },
+            ]
+          : undefined,
```
Comment (jakubcolony) [inline src/hooks/useActionsCount.ts:43]: All this logic really depends on when we consider an action to be in a particular domain. Currently, this will count:
- All actions with `fromDomainId` matching the selected domain ID
- All motions created in the selected domain

In contrast, the logic determining the most active team only considers the `fromDomainId` field, and not motions.

I think it's one for @arrenv to confirm but I don't want to block this over a small detail.

**Review by ArmandoGraterol — APPROVED** [review]
Nice work with this one Jakub!

**Review by arrenv — CHANGES_REQUESTED** [review]
@jakubcolony Nice one! This works as expected.

Only one thing I noticed is the "0" that appears on switching, which is not an issue for the members value changing.

change-actions

File: src/hooks/useActionsCount.ts [hunk 2]
```diff
@@ -0,0 +1,61 @@
...
+          ? {
+              gte: getThirtyDaysAgoIso(),
+            }
+          : undefined,
+      },
+    },
+    skip: !colony,
+  });
+
+  const actionsCount = totalActionData?.searchColonyActions?.total ?? 0;
```
Comment (bassgeta) [inline src/hooks/useActionsCount.ts:54]: I think this is causing the 0 flicker @arrenv mentioned.
I guess we can either memo the last value or return a loading flag with the count, displaying a spinner in the widgets?
Otherwise gj on this one, especially with the team -> domain word change, one layer of obfuscation gone :tada:

**Review by ArmandoGraterol — APPROVED** [review]
Loader working as expected for me 👌

**Review by bassgeta — DISMISSED** [review]
Spinners ftw, nice one :+1:

**Review by arrenv — CHANGES_REQUESTED** [review]
@jakubcolony Thank you, a loading state is better then showing 0.

For consistency, can we use skeleton loaders as opposed to little spinners here.

There is a design for it here - https://www.figma.com/file/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-v3?type=design&node-id=1782-45010&mode=design&t=jCVitGw2TLuAmLn3-11

With the spec being:
> During loading, a skeleton loader should appear for values that have not yet loaded. For the team color widget, this should use the same Light/Gray/200, but with a 25% opacity.

**Comment by jakubcolony** [comment]
@arrenv changed to skeleton loaders

**Review by bassgeta — APPROVED** [review]

**Review by ArmandoGraterol — APPROVED** [review]
The skeleton loader looks to be working as expected 👍 Good job

**Review by ArmandoGraterol — DISMISSED** [review]

**Review by arrenv — APPROVED** [review]
Nice one @jakubcolony, thank you for the update.

**Review by arrenv — APPROVED** [review]
All good!

**Review by arrenv — APPROVED** [review]

File: src/context/ipfs/ipfsnode/IPFSNode.ts [hunk 3]
```diff
@@ -38,12 +38,12 @@ class IPFSNode {
...
   /** Start the connection to IPFS (if not connected already) */
   start(): Promise<void> {
-    return this._ipfs.start();
+    return this.ipfs.start();
   }
 
   /** Stop the connection to IPFS */
   async stop(): Promise<void> {
-    return this._ipfs.stop();
+    return this.ipfs.stop();
```
Comment (rdig) [inline src/context/ipfs/ipfsnode/IPFSNode.ts:46]: I know this is just a linting issue, I just want to note that IPFSNode is only used for development.

What's more, it's not even supported anymore and we'll have to migrate to `helia` eventually

File: src/hooks/useActionsCount.ts [hunk 4]
```diff
@@ -0,0 +1,62 @@
...
+                },
+              },
+              {
+                motionDomainId: { eq: domainId },
+              },
+            ]
+          : undefined,
+        createdAt: onlyRecent
+          ? {
+              gte: getThirtyDaysAgoIso(),
```
Comment (rdig) [inline src/hooks/useActionsCount.ts:46]: :+1:

**Review by rdig — APPROVED** [review]
Code-wise and functional, it works as expected

Screenshot from 2024-01-16 19-33-25

Nice work!
