### PR TITLE
Fix `/edit-profile` loading state

### LINKED ISSUE #134: Fix the loading states for the user profile edit
As per discussion in #79

### PR DESCRIPTION
**Pull request by willm30**
## Description

This PR fixes [the problem](https://github.com/JoinColony/colonyCDapp/pull/79#issuecomment-1341046043) with the loading state at `/edit-profile`.

## Testing

I have covered the following scenarios:

1. Navigate to /edit-profile with no wallet connected. --> redirects to /landing
2. Connect wallet to a wallet with a registered user, then navigate to edit-profile. --> displays Profile Edit screen
3. While on edit-profile, refresh the browser. --> shows loading spinner, then displays Profile Edit screen
4. Disconnect wallet while at edit-profile --> redirects to /landing
5. Navigate to edit-profile with a wallet that doesn't have a user associated. --> shows loading spinner, then redirects to /landing

Please double-check each and any others you can think of.

**New stuff** ✨

* `useCanEditProfile.ts` to manage loading states and redirect to landing

Resolves #134

### CODE REVIEW

File: src/Entry.tsx [hunk 1]
```diff
@@ -5,8 +5,8 @@ import { IntlProvider } from 'react-intl';
 import { ApolloProvider } from '@apollo/client';
 
 import layout from '~styles/layout.css';
-import { DialogProvider } from '~shared/Dialog';
 import '~utils/yup/customMethods'; // ensures custom yup methods are available when components load
+import { DialogProvider } from '~shared/Dialog';
```
Comment (willm30) [inline src/Entry.tsx:9]: Ordering matters here to avoid circular module dependencies

File: src/hooks/index.ts [hunk 2]
```diff
@@ -34,6 +34,7 @@ export { default as useTitle } from './useTitle';
 export { default as useTokenInfo, TokenInfoProvider } from './useTokenInfo';
 export { default as useUserAvatarImageFromIPFS } from './useUserAvatarImageFromIPFS';
 export { default as useUserSettings, SlotKey } from './useUserSettings';
+export { default as useCanEditProfile } from './useCanEditProfile';
```
Comment (willm30) [inline src/hooks/index.ts:37]: Order matters here, needs to go after './useUserSettings' so `SlotKey` is defined

File: src/components/common/UserProfileEdit/UserMainSettings.tsx [hunk 3]
```diff
@@ -94,15 +94,10 @@ const UserMainSettings = ({
         },
       },
     });
+
+    updateUser?.(walletAddress, true);
   };
 
-  useEffect(
```
Comment (willm30) [inline src/components/common/UserProfileEdit/UserMainSettings.tsx:99]: With the addition of a "background update" option, updating the user on dismount is no longer necessary and can be performed in the form submit handler.

File: src/context/AppContext.tsx [hunk 4]
```diff
@@ -47,34 +49,37 @@ export const AppContextProvider = ({ children }: { children: ReactNode }) => {
...
-        query.then(({ data }) => {
+  const updateUser = useCallback(
+    async (address?: string, shouldBackgroundUpdate = false) => {
+      if (address) {
+        try {
+          if (!shouldBackgroundUpdate) {
+            setUserLoading(true);
+          }
+          const apolloClient = getContext(ContextModule.ApolloClient);
+          const { data } = await apolloClient.query<
```
Comment (willm30) [inline src/context/AppContext.tsx:60]: Using `async / await` here instead of  `.then` forces React to pause code execution until the query has completed, which stops React from batching the `setUserLoading` calls. This ensures `userLoading` actually gets set to true, which wasn't happening before.

File: src/context/AppContext.tsx [hunk 5]
```diff
@@ -47,34 +49,37 @@ export const AppContextProvider = ({ children }: { children: ReactNode }) => {
...
-          GetCurrentUserQuery,
-          GetCurrentUserQueryVariables
-        >({
-          query: GetCurrentUserDocument,
-          variables: { address },
-          fetchPolicy: 'network-only',
-        });
-        query.then(({ data }) => {
+  const updateUser = useCallback(
+    async (address?: string, shouldBackgroundUpdate = false) => {
```
Comment (willm30) [inline src/context/AppContext.tsx:53]: Per the comment below, now that `userLoading` is being set to true as expected, it's useful that we have some way of performing context updates in the "background", i.e. without prompting the display of a loading spinner. E.g when updating user settings or uploading a user avatar.

File: src/context/AppContext.tsx [hunk 6]
```diff
@@ -37,7 +40,6 @@ export const AppContextProvider = ({ children }: { children: ReactNode }) => {
   try {
     initialWallet = getContext(ContextModule.Wallet);
   } catch (error) {
-    initialUser = null;
```
Comment (willm30) [inline src/context/AppContext.tsx:40]: If this is set to `null` here, user will never be `undefined` and thus we lose the distinction between a wallet without a registered user (`null`) and the state in which we're checking if there's a registered user (`undefined`)

**Comment by Julianahlk** [comment]
@willm30 Overall looks good and all the scenarios you mentioned worked well for me. 

Only the I notice is that when you are redirected to the landing page after logging out from /edit-profile, the subscribed colonies list is still showing and the user avatar still has the thumbnail of the previously logged in user. If you logout from other routes these are cleared.

**Comment by willm30** [comment]
@Julianahlk Thanks, I had the relevant lines in my other PR as was working on these together and didn't realise but have moved over to here.

File: src/components/common/ColonyHome/ColonyMembersWidget/MembersSubsection.tsx [hunk 7]
```diff
@@ -160,7 +160,6 @@ const MembersSubsection = ({
                 // banned={canAdministerComments && banned}
                 banned={false}
                 showInfo
-                notSet={false}
```
Comment (willm30) [inline src/components/common/ColonyHome/ColonyMembersWidget/MembersSubsection.tsx:163]: UserAvatar had notSet default to true, even though more or less everywhere it was used it was being passed a false prop, like here. I have removed the default and removed these props where they were used.

File: src/components/common/UserProfileEdit/UserAvatarUploader.tsx [hunk 8]
```diff
@@ -58,12 +56,6 @@ const UserAvatarUploader = ({
     setAvatar(null);
   };
 
-  // on dismount
-  useEffect(
```
Comment (willm30) [inline src/components/common/UserProfileEdit/UserAvatarUploader.tsx:62]: Effect no longer necessary

File: src/components/frame/AvatarDropdown/AvatarDropdown.tsx [hunk 9]
```diff
@@ -97,8 +97,8 @@ const AvatarDropdown = ({ preventTransactions = false, spinnerMsg }: Props) => {
           <UserAvatar
             address={wallet?.address || ''}
             size="s"
-            notSet={false}
             user={user}
+            notSet={!wallet}
```
Comment (willm30) [inline src/components/frame/AvatarDropdown/AvatarDropdown.tsx:101]: Ensures notSet is true when user is logged out.

**Review by jakubcolony — APPROVED** [review]
Great to see a solution to this @willm30! All working well for me 👍

**Comment by willm30** [comment]
@Julianahlk Are you able to re-review when you get a moment? Thank you

**Review by Julianahlk — APPROVED** [review]
Everything working now 👍 Looks good.
