### PR TITLE
Fix: Clickable transactions

### LINKED ISSUE #3765: Userhub Transactions tab: Motion related transactions should open the correct motion
## Steps to reproduce

1. Install the voting reputation extension
2. Create a simple payment motion
3. Fully stake the motion on both sides
4. Vote to support the motion
5. Reveal your vote.
6. Finalize the motion.
7. Open the userhub and navigate to the transactions tab.
8. Click on the Vote or Reveal vote transactions.

## Expected behaviour

* The simple payment motion should open

## Actual behaviour

* The action sidebar attempts to load the vote transaction, rather than the simple payment motion.

This also affects motions created as part of an advanced payment, and in that instance the transaction should open the advanced payment.

### PR DESCRIPTION
**Pull request by davecreaser**
## Description

- Refactor the way clickable transactions works, and ensure that it works for all transaction types.

An issue was raised (https://github.com/JoinColony/colonyCDapp/issues/3765) where motion related transactions were not opening the correct action when clicked. After investigating the issue, it turned out that most transactions were not opening the correct action, and in fact were not even opening the correct colony. This PR aims to refactor the way clicking on a transaction in the user hub works, and introduces a new 'associatedActionId' property on the transaction type. This will hold the action id (which is itself a transaction hash) of the action which should be opened. If it is not present, it can be assumed that the transaction hash contained in the transaction itself is the correct one.

This PR fixes the following navigation bugs when a transaction is clicked:
- Opening the correct colony for all transactions
- Going to the correct action for motion related transactions
- Going to the correct action for expenditure related transactions
- Going to the correct action for multi sig related transactions
- Going to the correct action for expenditure funding related transactions (permissions, multi sig, and repuation)
- Going to the correct colony dashboard for create colony transactions
- Going to the extensions page for extension related transactions
- Going to the incoming funds page for funds claimed transactions

## Testing

Theoretically, every transaction type can be tested, so if you really really want to spend two days testing this then feel free to just trigger every possible type of transaction method listed here: `src/types/transactions.ts` and make sure when clicking them in the user hub that you navigate where you would expect!

In reality of course, you probably don't want to do that, so here's some good places to test. Feel free to test either all of them or just some of them:

* After running the create data script and before doing anything, just check that all the transactions generated by that script running navigate correctly:

https://github.com/user-attachments/assets/35be96f7-4181-4df8-8643-55201470a9f8

* Install some extensions (I used reputation and multisig, and changed the multisig threshold since this will help with testing the motions further down the line). Now check the transactions for them:

https://github.com/user-attachments/assets/e2a81b37-1a9c-487c-832b-dbf191df42d3

* Create an agreement, and follow the entire flow until it has succeeded (stake for and against to trigger a vote, and then vote for it, reveal and finalize) and then check that these transactions navigate properly:

In my video some other motion related bugs are shown, but you can ignore these (claiming twice at the end, seeing a flash of the change vote button, and seeing oppose wins for a second even though the motion passed)

https://github.com/user-attachments/assets/05735ace-0d8f-42b7-a70e-9d7518d01f22

* Create a multisig motion (don't forget to first give permissions!), and again follow the flow until it has succeeded. In my testing, I just manipulated the multisig threshold instead of using two users, but feel free to test however you see fit. Check the transactions for these:

https://github.com/user-attachments/assets/6b5b14fc-6c77-44e9-845c-57327c42e669

* Create an expenditure (an advanced payment or a streaming payment, or a split payment) and again follow the flow until it has succeeded. It would be good to test funding with all different types of funding methods. In my video I've used reputation. Check the transactions for these:

https://github.com/user-attachments/assets/46b4d975-e20c-4710-b1d6-86ddaadd76b4

If you can think of any other transactions to test, feel free! Some other things which I haven't mentioned are cancelling transactions, and doing actions using permissions for example.

## Diffs

**New stuff** ✨

* New optional property `associatedActionId` on the transaction model

**Changes** 🏗

* Ensured that associatedActionId is added to transactions where necessary.
* Changed the way clickable transactions are handled.

Resolves #3765

### CODE REVIEW

**Review by mmioana — APPROVED** [review]
Thanks for solving this issue @davecreaser 🙌 

Checked transactions after running the `create-data` script

https://github.com/user-attachments/assets/c65806f9-b73a-40be-9e44-9f8f9e417217

Then after installing the `Multi-sig` and `Reputation` extensions

https://github.com/user-attachments/assets/d1be2f89-5e07-4ed1-b6bf-b94a9ffa17e6

Then for creating an `Agreement`

https://github.com/user-attachments/assets/344a696a-44cb-42c7-b532-0bd5afbdfba7

Then for a simple payment using `Multi-sig`

https://github.com/user-attachments/assets/a8752986-aea1-46a4-ad1d-b1fd7366d0c4

Then an `Advanced payment` where I used `Permissions`, `Reputation` and `Multi-sig` to fund the payment

https://github.com/user-attachments/assets/1ce9a7d1-82c7-4989-95e8-18b2174ede73


https://github.com/user-attachments/assets/e55dcca0-b9f8-4e9e-a98d-721881ab9762


https://github.com/user-attachments/assets/c581146c-decc-4000-bf5f-e009735493a6


And it all works like a charm ✨ really great work!

I am just wondering if it would make sense to create a helper for getting the `associatedActionId` based on the expenditure or txHash, something like
```
const getTransactionAssociatedActionId = (
  expenditure?: ExpenditureFragment,
  actionTxHash?: string,
) => expenditure?.creatingActions?.items[0]?.transactionHash || actionTxHash;
```

Either way this should not be a blocker for merging this PR 💯

**Comment by davecreaser** [comment]
Thanks @mmioana, nice idea with the helper util, I've updated the PR based on that feedback!

**Review by mmioana — APPROVED** [review]
Thanks a lot for doing the refactoring @davecreaser 🥇 it all looks much cleaner now ✨ 

And everything still works as expected!

After running the create-data script

https://github.com/user-attachments/assets/f2b14609-93d9-464f-83cc-af143514e7a4

After installing some extensions

https://github.com/user-attachments/assets/71d82017-68d4-48d1-8ffc-32980ae17a14

Creating an agreement

https://github.com/user-attachments/assets/a4f26027-44e9-42e2-b878-acf434d87c84

Using multi-sig for a simple payment

https://github.com/user-attachments/assets/4e6344ac-04d5-44fb-ae1c-8fbb002dd11d

Created an advanced payment

https://github.com/user-attachments/assets/5eec4f4a-efbc-48f7-9ea3-67e83a9bf722

Can confirm all transactions point to the right action/motion 💯 nice job!!!

File: src/components/common/Extensions/UserHub/partials/TransactionsTab/partials/GroupedTransaction.tsx [hunk 1]
```diff
@@ -92,35 +102,66 @@ const GroupedTransaction: FC<GroupedTransactionProps> = ({
...
     getFormattedDateFrom(new Date(transactionGroup[0].createdAt));
 
   const handleNavigateToAction = () => {
-    if (canLinkToAction) {
+    if (!canLink) return;
+
+    // If this is a create colony transaction.
+    if (values.group.key === TRANSACTION_METHODS.CreateColony) {
+      navigate(`/${COLONY_HOME_ROUTE.replace(':colonyName', colonyName)}`);
+      return;
```
Comment (rumzledz) [inline src/components/common/Extensions/UserHub/partials/TransactionsTab/partials/GroupedTransaction.tsx:126]: **[Nitpick alert]**: you can also return it in one fell swoop!

```js
if (values.group.key === TRANSACTION_METHODS.CreateColony) {
  return navigate(`/${COLONY_HOME_ROUTE.replace(':colonyName', colonyName)}`);
}
```

Comment (rumzledz) [reply src/components/common/Extensions/UserHub/partials/TransactionsTab/partials/GroupedTransaction.tsx:126]: Was thinking that because there aren't any other paths or search params here, maybe you can just get away with:

```js
navigate(`/${colonyName}`);
```

**Review by rumzledz — APPROVED** [review]
Really neat solution for setting up an association for different events for an action @davecreaser ! Also cheers for the mini GraphQL breakdown session earlier 🙌 

associated-hash

**Review by bassgeta — APPROVED** [review]
Real nice solution with this extra parameter :ok_hand: 
Additionally, this gives a much nicer way of linking stuff together, something we didn't have before, super legit!
I've left one comment on the multi sig widget part, maybe we could get the `associatedActionId` beforehand and pass just that instead of the entire action.

Now for testing!
Create data transactions plus some multisig test tx :heavy_check_mark: 

https://github.com/user-attachments/assets/97251479-b3eb-4d82-acc3-c1f2ae620a7a

And the advanced payment flow also works :heavy_check_mark: 

https://github.com/user-attachments/assets/fde03d76-608d-442a-bed2-a4e6f70a866d

If you look at like 1:42 we have a bunch of empty notifications? cc @davecreaser 
we probably don't need to fix it here, it could be already an issue on `master`
