### PR TITLE
Fix: Tabs right arrow showing over loader

### LINKED ISSUE #3749: Mobile menu scroller arrow appears on top of loader on profile page
## Steps to reproduce

1. Set screen size to mobile
2. Navigate to [http://localhost:9091/account/profile](http://localhost:9091/account/profile)

## Expected behaviour

* The loading spinner should appear unobscured

## Actual behaviour

* The loading spinner has the scroller arrow appear over it

Screenshot 2024-11-21 at 15 03 59

Screenshot 2024-11-21 at 15 04 20

### PR DESCRIPTION
**Pull request by iamsamgibbs**
## Description

This PR fixes an issue where the right arrow of the tabs component was showing on top of the loader.

## Testing

Navigate to http://localhost:9091/account/preferences Make sure you don't see the right arrow whilst the page is loading.

https://github.com/user-attachments/assets/4ca928fb-0824-434a-bcf8-3508fbe55425

## Diffs

**Changes** 🏗

* Removed unnecessary z-index

Resolves #3749

### CODE REVIEW

File: src/components/shared/Extensions/Tabs/Tabs.tsx [hunk 1]
```diff
@@ -29,7 +29,7 @@ const Tabs: FC<PropsWithChildren<TabsProps>> = ({
           upperContainerClassName,
         )}
         leftNavBtnClassName="absolute left-0 z-base"
-        rightNavBtnClassName="z-base"
+        rightNavBtnClassName=""
```
Comment (mmioana) [inline src/components/shared/Extensions/Tabs/Tabs.tsx:32]: Could we just remove the property given we set it to an empty string?

**Review by mmioana — APPROVED** [review]
Nice and simple fix @iamsamgibbs 🥇 

Master shows the tabs arrow when page is loading

https://github.com/user-attachments/assets/2a037150-e49e-4a03-a732-b01994222a76


While on this branch, not

https://github.com/user-attachments/assets/47522929-176b-42b3-828d-f4edd80e9db0

However @iamsamgibbs I am wondering if we can just remove setting the `rightNavBtnClassName` to an empty string, given it's either way optional?
I'll approve nonetheless 🙌

**Review by davecreaser — APPROVED** [review]
All good here, but same question as @mmioana :)

Screenshot 2024-12-10 at 16 36 21

**Review by bassgeta — APPROVED** [review]
image
No arrow in sight :eye: 
nice one!

**Comment by iamsamgibbs** [comment]
@mmioana @davecreaser @bassgeta Made the change I should have made in the first place and removed the entire line instead of just leaving it empty! 🤦‍♂️

**Review by davecreaser — APPROVED** [review]
Cleaner for sure 😆

**Review by mmioana — APPROVED** [review]
All good @iamsamgibbs 🥇 


https://github.com/user-attachments/assets/4ffc128a-c5a9-4081-8e22-4b5ef35a63a6

**Review by bassgeta — APPROVED** [review]
Still good :sunglasses: 
image
