### PR TITLE
Fix: Improvements to transaction errors

### LINKED ISSUE #2222: Fixes and improvements to transaction errors
## Steps to reproduce

There are a few issues here. Note, this was not tested locally, only in production.

1. Create a new colony. (can be seen in Userhub as well)
2. Reject the transaction.
3. Click the `Retry` button.
    a. It will not trigger the retry.
    b. If in the Userhub, it will close the Userhub.
4. Click `Cancel`.
5. Click the `Yes` option.
6. If creating a Colony, this will break the app.

## Expected behaviour

* If cancelling creating a Colony, it should not break the app and should return the user to the previous step.
* `Retry` should trigger the transaction again.
* Clicking `Retry` should not close the Userhub.
* `Cancel` should be an option along with `Retry` as of the design.
   * `Cancel` should have the same behviour as it does now with the `Yes` / `No` confirmation.
* It should show the full error message, wrapped.
* It should match the style of the design.

[Figma link](https://www.figma.com/file/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-v3?type=design&node-id=1782-51131&mode=design&t=EIF9brlfr9amkOk9-4)

image

## Actual behaviour

* Cancelling the transaction to create a Colony should not break the app.
* `Retry` does not do anything.
* The error message is cut off.
* You only see the `Cancel` option if you click the `Retry` option.

#### Retry does not do anything
cannot-retry-transaction

#### Retry closes the Userhub
cannot-retry userhub

#### Cancelling in the creating step crashes the app
cancelling-colony-creation

### PR DESCRIPTION
**Pull request by iamsamgibbs**
## Description

There were a few issues with how transaction errors were handled in the user hub.

Issue 1 - UserHub transactions were missing the "Cancel" option. This PR adds a "Cancel" button in addition to the existing "Retry" button. It has the same behaviour as the existing "Cancel" button and requires a confirmation step.

Issue 2 - Transaction error message character limits were too short. This PR increases the allowed length and fixes the logic in the short description utility function.

Issue 3 - The transaction error messages were incorrectly styled. Should now match [figma](https://www.figma.com/file/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-v3?type=design&node-id=1782-51131&mode=design&t=EIF9brlfr9amkOk9-4)

Issue 4 - Clicking "Retry" was closing the UserHub. This was occurring only when the UserHub was automatically opened by a failed transaction. This is because the visibility of the menu is being controlled by both the popper tooltip and the isUserHubOpen state and probably warrants a bigger refactor at some point, for now this issue has been resolved by ensuring the popper tooltip visibility is true when isUserHubOpen is true.

Issue 5 - Clicking the "Retry" button on a failed transaction in the UserHub transactions tab would sometimes not trigger the transaction to retry. When attempting to reproduce this, I found the first retry would work, but the second would fail. This was being caused by the action channel buffer overflowing when too many actions are queued. To resolve this I have changed the action channel buffer type from fixed to expanding. (I'm unsure if further investigation is needed here, or if the fixed buffer size was simply too small?)

Issue 6 - When creating a colony, if you cancelled your transaction at the first step, the entire app would crash. This PR fixes this and returns you the "Confirm all" step if the transaction is cancelled.

## Testing

Connect with a metamask wallet rather than a developer wallet so that you can easily cancel transactions.

Issue 1 - Create a new action, when you submit the form, decline the transaction in metamask. The UserHub should automatically open. Cancel the transaction, you should be prompted for a confirmation.

Issue 2 - Check UserHub transaction error messages are visible up to 120 characters.

Issue 3 - Check UserHub transaction error message styling matches figma design.

Issue 4 - Repeat steps in issue 1. Retry the transaction, the UserHub should stay open.

Issue 5 - Repeat steps in issue 1. Retry and reject the transaction multiple times.

Issue 6 - Run `node scripts/create-colony-url.js` to get a link to create a new colony. Complete the form and reject the first transaction. Cancel the transaction and you should be returned to the previous step.

## Diffs

**Changes** 🏗

* UserHub transaction error styling
* UserHub transaction now has "Cancel" button
* UserHub transaction retry button no longer closes UserHub
* Cancelling the create colony transaction no longer crashes the app

Resolves #2222

Screenshot 2024-04-19 at 15 46 38

https://github.com/JoinColony/colonyCDapp/assets/34915414/eeff4c9b-b931-4aed-86c3-621c4d5c9b75

### CODE REVIEW

**Review by bassgeta — CHANGES_REQUESTED** [review]
Code-wise looks good, I can confirm that the first 5 issues are all resolved!
However, I am getting this error for issue 6:
image

**Review by jakubcolony — CHANGES_REQUESTED** [review]
LGTM overall, just spotted one thing around issue 3

**Issue 1:**

All good here:

https://github.com/JoinColony/colonyCDapp/assets/112586815/59162b15-c4e1-4f21-8b16-ca6be527240a

**Issue 2:**

I think that looks right:

image

**Issue 3:**
The font-weight looks different in Figma:
image
image

Issues 4, 5 and 6 all seem to be resolved.

Great work @iamsamgibbs!

**Comment by iamsamgibbs** [comment]
Thanks for the review Jakub! Issue 3 is looking okay to me on my end?

Screenshot 2024-04-23 at 10 48 08

**Review by jakubcolony — APPROVED** [review]
Must've been a stale cache or something - all looks good now:

image

File: src/components/common/Extensions/UserHub/partials/TransactionsTab/partials/GroupedTransactionContent.tsx [hunk 1]
```diff
@@ -93,26 +93,40 @@ const GroupedTransactionContent: FC<GroupedTransactionContentProps> = ({
             toggleCancelConfirmation={toggleCancelConfirmation}
           />
         ) : (
-          <TransactionStatus status={status} />
+          <TransactionStatus status={status} hasError={!!error} />
```
Comment (chmanie) [inline src/components/common/Extensions/UserHub/partials/TransactionsTab/partials/GroupedTransactionContent.tsx:96]: I have some reservations about passing in a separate error here, but I think it's necessary for now. I will handle this in my refactor.

**Comment by chmanie** [comment]
Thank you @iamsamgibbs, this was important, at least to re-establish that functionality. I will address the extra error in my refactoring

**Review by chmanie — APPROVED** [review]
Thank you @iamsamgibbs, this was important, at least to re-establish that functionality. I will address the extra error in my refactoring
