### PR TITLE
Fix: Correctly show the expected Action Form content

### LINKED ISSUE #3482: Main nav "Make payment" unexpected behavior
## Steps to reproduce

Edit: I happened to be running a pretty costly process when running into this issue. In testing it later, I was not able to replicate as easily. But I still think it is worth looking into why it loaded the categories, then the blank action screen.

1. Open an existing action.
2. Click on the "Make payment" button in the main nav.
3. Note what opens in the action panel.

## Expected behaviour

* Clicking the "Make payment" button in the main nav should open the Payments action category screen.

## Actual behaviour

* Clicking the "Make payment" button in the main nav  while, in an existing action opens the blank action panel.

[opening-panel-2.webm](https://github.com/user-attachments/assets/7b760dce-162f-43ec-b84f-806c2c7017ea)

### PR DESCRIPTION
**Pull request by rumzledz**
## Description

There was a weird race condition being caused by a `useEffect` inside `ActionSidebarContextProvider`. It was resetting a state which ended up clearing the current action which we're using to conditionally render either the GroupedTransactionContent or the actual Action Form.

race-condition

There was also an issue wherein if you're already on an action-specific form i.e. Simple payment, clicking the "Create agreement" button on the Sidebar doesn't do anything. I fixed those up to make sure that the actionType correctly propagates, which should hopefully make the form update correctly depending on what action has been set.

action-form-updates

## Testing

1. Click the Manage Colony Sidebar button
2. Verify that you see the Manage Group Content
3. Click the Make Payment Sidebar button
4. Verify that you see the Payments Group Content
5. Click Simple Payment
6. Wait for the Simple Payment form to be initialised
7. Click the Create Agreement Sidebar button
8. Verify that the form gets correctly updated to Create Agreement
9. Click the Manage Colony Sidebar button
10. Verify that you see the Manage Group Content
11. Click Mint Tokens
12. Click the Make Payment Sidebar button 
13. Verify that you see the Payments Group Content

Resolves #3482

### CODE REVIEW

**Review by mmioana — APPROVED** [review]
Awesome work for fixing this issue @rumzledz 🙌 

Now opening the action sidebar behaves properly 💯 
Screenshot 2024-11-06 at 11 32 10
Screenshot 2024-11-06 at 11 32 21
Screenshot 2024-11-06 at 11 32 32
Screenshot 2024-11-06 at 11 32 40
Screenshot 2024-11-06 at 11 32 48
Screenshot 2024-11-06 at 11 33 01
Screenshot 2024-11-06 at 11 33 08

File: src/components/shared/Fields/Form/Form.tsx [hunk 1]
```diff
@@ -129,6 +129,20 @@ const Form = <FormData extends FieldValues>({
...
+      const resolvedDefaultValues =
+        typeof defaultValues === 'function'
+          ? await defaultValues()
+          : defaultValues;
+
+      formHelpers.reset(resolvedDefaultValues);
+    };
+
+    initializeForm();
+  }, [defaultValues, formHelpers]);
```
Comment (bassgeta) [inline src/components/shared/Fields/Form/Form.tsx:144]: we could maybe just do `formHelpers.reset` as the dependency, not sure if any other helpers can change according to form state

**Review by bassgeta — APPROVED** [review]
Nice job separating all of this, I can imagine it was a bit hellish to debug too :sweat_smile: 
Manage colony sidebar :heavy_check_mark: 
image
Make payment :heavy_check_mark: 
image
Simple payment into agreements works, and if I spam buttons nonstop, nothing breaks!

**Review by rdig — APPROVED** [review]
