### PR TITLE
Fix/3928+3905 member card permissions and reputation

### LINKED ISSUE #3905: [PROD] Multi-sig missing permissions in members cards #3905
## Steps to reproduce

1. Navigate to the MetaColony
2. Select the Members Page.
3. View the cards filtered by 'All teams'. In particular, note the display of the 'Alex' card.
4. Select a team at the top to filter by.
5. Note the same 'Alex' card. The UI is broken and is not displaying the correct multi-sig permissions that have been inherited into the Product team. 
6. Select 'Product' team using the team switcher.
7. The cards are not being correctly sorted by reputation. 

## Expected behaviour

* Contributor cards should not break when teams are filtered. Cards should be filtered at the team level correctly as per the product specs.

* The individual member cards are not displaying the correct information. 

image

## Actual behaviour

* Cards are breaking when filtering is applied. Cards are not being sorted correctly and are not displaying the correct multi-sig permissions that are inherited. Individual user cards also don't show the correct teams and permissions. 

image

### LINKED ISSUE #3928: [PROD] Dashboard: Team Reputation not picking up inherited multi-sig or usernames with address
## Steps to reproduce

1. Navigate to the MetaColony dashboard
2. Filter to the 'Product' team
3. View the Top Member card. Note only 4 users are showing, one with no name.
4. Navigate to the Member's page.
5. Filter by Product again.
6. Note there are 6 users in the Product team. 2 with inherited multi-sig permissions, 1 with an address as the username. These 2 users are missing from the widget on the dashboard which should display as 'All other' and the address for the other user is not being shown. 

## Expected behaviour

* The Top Member version of the Team rep card on the dashboard should include all users, including those with inherited permissions.

* The card should also display users with addresses as their username.

## Actual behaviour

* The Top Members card does not include users with inherited permissions.

* The Top Members card does not display usernames that are addresses.

image

image

### PR DESCRIPTION
**Pull request by iamsamgibbs**
WIP

## Description

This PR resolves a few permissions / reputation related UI issues:

* The top users chart on the dashboard now shows the wallet address if a user does not have a profile / display name.
* The domains list on the user popover will now show all domains if a user has permissions in the root domain to show their inherited permissions.
* The permissions badges on the member cards now more closely align with the permissions badges on the user popover.

## Testing

First lets check the top users chart shows the wallet address when a user does not have a profile / display name.

* Step 1: Navigate to [http://localhost:9091/planex/members](http://localhost:9091/planex/members)
* Step 2: Copy the wallet address of a member with reputation in a sub-domain:

Screenshot 2025-01-14 at 12 54 12

* Step 3: Use GraphiQL to delete their profile:

```
mutation MyMutation {
  deleteProfile(input: {id: "USERS_WALLET_ADDRESS"}) {
    id
  }
}
```

Screenshot 2025-01-14 at 12 54 40

* Step 4: Refresh, then navigate to the colony dashboard, select a sub-domain where the user has reputation and check the "Top users" chart. The wallet address should be visible. (Compared to master where an empty string is rendered).

Screenshot 2025-01-14 at 12 56 53

Next lets check the full list of domains shows on the user popover when the user has permissions in the root domain.

* Step 5: We need to copy the wallet address of a user who has no reputation. The easiest way to do this is disconnect your dev wallet, then connect with dev wallet 4. Copy the wallet address.

Screenshot 2025-01-14 at 12 59 04

* Step 6: Then reconnect with dev wallet 1 so we can assign some permissions.
* Step 7: Create a manage permissions action and give the user some permissions in the general.

Screenshot 2025-01-14 at 13 01 10

* Step 8: Navigate to [http://localhost:9091/planex/members](http://localhost:9091/planex/members) and click on the user to open the user popover. Check the full list of domains appears as they will have inherited permissions in each domain. (Compared to master where only "General", or teams in which they had reputation / other permissions would show). You can also check here that the reputation badge is shown for users who have permissions even if they have 0 reputation.

Screenshot 2025-01-14 at 13 03 21

And lastly we want to check the members cards properly shown inherited permissions and align them more closely with the permissions badges that show in the user popover.

* Step 9: Assign Fry custom funding permissions in Serenity.

Screenshot 2025-01-14 at 13 06 06

* Step 10: Select the Serenity team filter and check the permissions badge shown for Fry is as expected.

Screenshot 2025-01-14 at 13 06 39

* Step 11: Assign Fry custom admin and arbitration in General.

Screenshot 2025-01-14 at 13 08 03

* Step 12: With the Serenity team filter selected, check the badge shows Payer to ensure it accounts for the inherited permissions.

Screenshot 2025-01-14 at 13 08 29

* Step 13: Switch to General and check it shows Custom.

Screenshot 2025-01-14 at 13 09 31

* Step 14: Install the multisig extension.
* Step 15: Assign Amy custom multisig funding permissions in Serenity.

Screenshot 2025-01-14 at 13 11 04

* Step 16: With the Serenity team filter selected, check the expected permissions badge is shown (note the different icon for multisig)

Screenshot 2025-01-14 at 13 11 36

* Step 17: Assign Amy custom multisig admin and arbitration in General.

Screenshot 2025-01-14 at 13 12 42

* Step 18: With the Serenity team filter selected, check the badge shows Payer to ensure it accounts for the inherited permissions. Then check General shows custom.

Screenshot 2025-01-14 at 13 13 12

* Step 19 - Assign multi-sig permissions to Leela in General.

Screenshot 2025-01-14 at 13 14 15

* Step 20 - Check both permissions badges are shown.

Screenshot 2025-01-14 at 13 14 31

* Step 21 - Resize the window to confirm the text on the badge is hidden when there is not sufficient space.

Screenshot 2025-01-14 at 13 15 43

## Diffs

**Changes** 🏗

* Top users chart now falls back to wallet address if no profile is found
* Member card now uses PermissionsTooltip rather than RolesTooltip
* PermissionsTooltip has been adjusted to conditionally show the role name

Resolves #3928 
Resolves #3905

### CODE REVIEW

File: src/components/v5/shared/UserInfoPopover/partials/PermissionTooltip/PermissionTooltip.tsx [hunk 1]
```diff
@@ -45,9 +52,24 @@ const PermissionTooltip: FC<PermissionTooltipProps> = ({
...
+    );
+  }
+
+  const role = getRole(mergedPermissions);
+
   return (
     <Tooltip
       placement="top"
+      // Add singleBadge container when there is only one badge
+      className="justify-end only:w-full only:@container/singleBadge"
```
Comment (mmioana) [inline src/components/v5/shared/UserInfoPopover/partials/PermissionTooltip/PermissionTooltip.tsx:72]: Very nice! 🤩

File: src/components/v5/shared/UserInfoPopover/partials/PermissionTooltip/PermissionTooltip.tsx [hunk 2]
```diff
@@ -58,7 +80,15 @@ const PermissionTooltip: FC<PermissionTooltipProps> = ({
     >
       <PermissionsBadge
         icon={isMultiSig ? UsersThree : User}
-        pillSize="small"
+        pillSize={showRoleLabel ? 'medium' : 'small'}
+        // If only one badge, show at a smaller container width
+        textClassName="hidden @[6rem]/singleBadge:block @[11rem]/cardDetails:block"
```
Comment (mmioana) [inline src/components/v5/shared/UserInfoPopover/partials/PermissionTooltip/PermissionTooltip.tsx:85]: 🤩

**Review by mmioana — CHANGES_REQUESTED** [review]
Really awesome work on this one @iamsamgibbs 🥇 

I've noticed an issue for a screen size of ~`1400px` when there is a single Permission badge and you hover over it, the text will collapse/expand when the tooltip is visible/invisible. Not sure if this is as intended, but if it is, I'll gladly approve your PR 🙌 

https://github.com/user-attachments/assets/70d831dc-87ab-4045-98be-143cc9ffd51f


Besides this everything works as expected 🎉 

Screenshot 2025-01-15 at 10 17 44
Screenshot 2025-01-15 at 10 18 17
Screenshot 2025-01-15 at 10 18 58
Screenshot 2025-01-15 at 10 20 48
Screenshot 2025-01-15 at 10 22 19
Screenshot 2025-01-15 at 10 23 15
Screenshot 2025-01-15 at 10 24 42

https://github.com/user-attachments/assets/f11fabf1-4513-4e1b-84ab-5370377659d9

Screenshot 2025-01-15 at 10 27 30

https://github.com/user-attachments/assets/7b467127-5148-4003-aa5a-3f70420a486d


https://github.com/user-attachments/assets/446b0fe2-54ea-4986-b055-b8a0d54510ab

Screenshot 2025-01-15 at 10 31 27

https://github.com/user-attachments/assets/ebe45186-3378-4190-90cc-c544ae9fab40

Screenshot 2025-01-15 at 10 33 27
Screenshot 2025-01-15 at 10 34 00
Screenshot 2025-01-15 at 10 34 13

**Comment by iamsamgibbs** [comment]
Thanks @mmioana , that definitely is an issue! (And was only happening at very specific breakpoints!) Should be fixed now, along with a logic bug I noticed whilst fixing this.

**Review by mmioana — CHANGES_REQUESTED** [review]
Thanks for your fast fix @iamsamgibbs 👏 

Can confirm now the pills no longer collapse/expand upon showing/hiding the tooltip

https://github.com/user-attachments/assets/2f73c98b-0036-4422-b0b7-66d321c98bbe

However, I did notice an issue for mobile as in sometimes when clicking on the right-most pill, the tooltip will introduce a page horizontal scroll

https://github.com/user-attachments/assets/06cab443-21e1-4f07-a9fb-a29879876677

While on `master` the tooltip has a left alignment, so no horizontal overflow

https://github.com/user-attachments/assets/32255b65-290c-4b56-b934-e2a625d1ff2c

If you would like to treat this in another issue, let me know and I'll approve this PR 🙌

**Comment by iamsamgibbs** [comment]
Thanks for picking up on this @mmioana ! It should be fixed now!

File: src/components/v5/shared/UserInfoPopover/partials/PermissionTooltip/PermissionTooltip.tsx [hunk 3]
```diff
@@ -71,6 +71,9 @@ const PermissionTooltip: FC<PermissionTooltipProps> = ({
       <Tooltip
         placement="top"
         className="w-fit"
+        popperOptions={{
+          strategy: 'fixed',
+        }}
```
Comment (mmioana) [inline src/components/v5/shared/UserInfoPopover/partials/PermissionTooltip/PermissionTooltip.tsx:76]: 💯

**Review by mmioana — APPROVED** [review]
Nice work @iamsamgibbs thanks for fixing that issue as well!

Everything looks and behaves as expected 💯 

https://github.com/user-attachments/assets/e1f11dcb-b546-40c0-a518-91d80d9b9cf6

**Review by rdig — APPROVED** [review]
Everything here is working as expected! Nicely done! This was a nice good chunk of work, just involving all the different cases you had to account for and test! :100: 

One note though, that if you want to have access to the "dev wallets", there's actually a faster way:

> Step 5: We need to copy the wallet address of a user who has no reputation. The easiest way to do this is disconnect your dev wallet, then connect with dev wallet 4. Copy the wallet address.

Just go to http://localhost:3006/ganache-accounts.json which is the "network files" docker instance and you'll have access to all of them

Here's the screenshots from testing:

Screenshot from 2025-01-17 13-36-08
Screenshot from 2025-01-17 13-36-38
Screenshot from 2025-01-17 13-37-30
Screenshot from 2025-01-17 13-38-08
Screenshot from 2025-01-17 13-38-15
Screenshot from 2025-01-17 13-40-47
Screenshot from 2025-01-17 13-41-32
Screenshot from 2025-01-17 13-41-39
Screenshot from 2025-01-17 13-42-41
Screenshot from 2025-01-17 13-42-59
Screenshot from 2025-01-17 13-43-07
Screenshot from 2025-01-17 13-44-07
Screenshot from 2025-01-17 13-44-21
Screenshot from 2025-01-17 13-44-25
Screenshot from 2025-01-17 13-44-32
Screenshot from 2025-01-17 13-44-40
Screenshot from 2025-01-17 13-45-51
Screenshot from 2025-01-17 13-45-55
Screenshot from 2025-01-17 13-46-08
Screenshot from 2025-01-17 13-46-15
Screenshot from 2025-01-17 13-47-00
Screenshot from 2025-01-17 13-47-13
Screenshot from 2025-01-17 13-47-20
Screenshot from 2025-01-17 13-47-28
Screenshot from 2025-01-17 14-07-44
Screenshot from 2025-01-17 14-07-53
Screenshot from 2025-01-17 14-07-58
Screenshot from 2025-01-17 14-08-20

**Review by davecreaser — APPROVED** [review]
Wow, super nice PR @iamsamgibbs, really nicely detailed testing steps for such a big amount of things fixed/to check. Thanks!

Had a look and everything looks good and is working great 🎉 



Screenshot 2025-01-21 at 14 17 32
Screenshot 2025-01-21 at 14 19 56
Screenshot 2025-01-21 at 14 20 38
Screenshot 2025-01-21 at 14 22 16
Screenshot 2025-01-21 at 14 22 28
Screenshot 2025-01-21 at 14 23 20
Screenshot 2025-01-21 at 14 23 25
Screenshot 2025-01-21 at 14 23 35
Screenshot 2025-01-21 at 14 24 30
Screenshot 2025-01-21 at 14 24 46
Screenshot 2025-01-21 at 14 25 40
Screenshot 2025-01-21 at 14 25 53
Screenshot 2025-01-21 at 14 25 58
Screenshot 2025-01-21 at 14 26 48
Screenshot 2025-01-21 at 14 27 02
Screenshot 2025-01-21 at 14 27 18
