### PR TITLE
Various colony creation flow fixes

### LINKED ISSUE #1279: Create a Colony onboarding flow UI fixes
## Description 

There are a number of UI fixes that are required for the Create a Colony flow to improve the consistency of UI elements and improve the overall experience of the CDapp before the beta launch.  The issues that are required include:

## Colony details page

- [x] Input description text doesn't match Figma.

image

- [x] All input fields should validate on submit and the primary CTA should not show in a disabled state. (This does not appear anywhere across the CDapp so please avoid using this approach to ensure user experience consistency)

- [x] Error states should not show on blur and only on submit. (This does not appear anywhere across the CDapp so please avoid using this approach to ensure user experience consistency)

- [x] Padding between the inputs does not match Figma.

image

## Create new native token

- [x] Icon sizes are too large.
image

- [x] Hover states are missing the text-blue-300 inner border - 
image

## Colony native token**

- [x] This step is missing the title and page description matching Figma.

image

- [x] The input fields should go full width of the container as per Figma.

image

- File upload has a few issues:

- [x] The avatar placeholder doesn't match Figma.
- [x] The padding between the avatar and the upload box doesn't match Figma.
- [x] When I upload a file (that's too large) and try another upload the form doesn't interact. I can not upload again. 
- [x] Hover state is missing as per the original component design - https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-V5?type=design&node-id=1266%3A85254&mode=dev&t=XOXSKM9TdW35BwEq-1 
- [x] Input showing as blue when I complete it:
image

## Confirm your Colony’s details page 

- [x] The width of this page is different from the others? The page width should be 530 for this whole onboarding funnel.
image

 
- [x] Button styles do not match Figma:
 
image

- [x] When I select on the 'edit' button in the Native token box, it takes me back to an empty existing token, it should go back to the first select tab.

image

### LINKED ISSUE #1305: File upload UI issues
## Description

The file upload UI form has broken along the way. It's used in the user account and the Colony creation follows, so fixing it would improve the appearance of this component. 

Issues:

1. The default state is missing t'he instructional text for upload limits and file formats.
2. The remove button doesn't match the text link as per the design. 

## Figma links to the component + interactions

https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-V5?type=design&node-id=2029%3A196910&mode=dev&t=brqRb02uKRH5EEbq-1

### PR DESCRIPTION
**Pull request by thomassdk**
## Description

This PR fixes the UI issues that were picked up in the colony creation flow, in doing so it was necessary to touch the AvatarUploader and the Input component.

Ideally the `AvatarUploader` will have more work done to it so that the `FileUpload` component can be easily extracted into its own component and work stand alone but for the launch this will do.

The Input component has been updated to match the new design so that there is no longer any layout shift when errors occur: https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-V5?type=design&node-id=2031-200644&mode=design&t=AK0K8sUe5MO1rdqu-0

Resolves #1305
Resolves #1279

### CODE REVIEW

File: src/components/v5/common/CreateColonyWizard/StepCreateToken.tsx [hunk 1]
```diff
@@ -12,10 +13,21 @@ import { ButtonRow, HeaderRow } from './shared';
...
 
+export const MSG = defineMessages({
+  heading: {
+    id: `${displayName}.heading`,
+    defaultMessage: 'Your Colony’s native token',
+  },
+  description: {
+    id: `${displayName}.description`,
+    defaultMessage:
+      'Your native token is your organization’s unit of ownership, and powers key features within your Colony.{br}{br}Tokens are initially locked and not transferable by recipients. You must unlock your token if you wish it to become tradable.',
```
Comment (chmanie) [inline src/components/v5/common/CreateColonyWizard/StepCreateToken.tsx:27]: Apostrophe

File: src/components/v5/common/CreateUserForm/CreateUserFormInputs.tsx [hunk 2]
```diff
@@ -11,18 +11,30 @@ const displayName = 'common.CreateUserFormInputs';
 const CreateUserFormInputs = () => {
   const {
     register,
-    formState: { errors, isSubmitting, dirtyFields },
+    formState: { errors, isSubmitting, dirtyFields, submitCount },
   } = useFormContext();
   const emailAddressError = errors.emailAddress?.message as string | undefined;
+  const showEmailAddressError = Boolean(
```
Comment (chmanie) [inline src/components/v5/common/CreateUserForm/CreateUserFormInputs.tsx:17]: If this is a recurring pattern, might be interesting to factor this out into a helper (doesn't need to be a hook though, we have so many of those).

File: src/components/v5/common/Fields/Input/Input.tsx [hunk 3]
```diff
@@ -106,7 +111,7 @@ const Input: FC<InputProps> = ({
       )}
 
       {/* This is to stop layout shift when error messages are shown */}
-      <div className="relative pb-9">
+      <div className="relative pb-[1.125rem]">
```
Comment (chmanie) [inline src/components/v5/common/Fields/Input/Input.tsx:114]: Are these 2px very important @melyndav? Otherwise I would recommend using `pb-4` (16px) or `pb-5` (20px). This helps us to stay consistent across all components.

**Review by chmanie — DISMISSED** [review]
Good work! I approve, but the important review here should come from @melyndav

File: src/components/v5/common/Fields/Input/Input.tsx (hunk 3 above)
Comment (melyndav) [reply src/components/v5/common/Fields/Input/Input.tsx:114]: @chmanie do you have a screenshot of the UI for this? It's hard to make a call on the padding change when I don't know what I'm looking. 👍

**Review by melyndav — CHANGES_REQUESTED** [review]
Hey @thomassdk!! Super work on these two massive PR's. Thank you!

A couple of minor changes just to keep consistency with PagePro's components.

- [x] For text inputs with descriptions, can we update this subtext to 400?
image


- [x] Can we match the padding under the description subtext to 8px? This should be consistent across all the inputs in this flow. 
image


- [x] Padding between the input title and the input should be 6px - it's currently showing as 4px (0.25rem)
image
 
 
- [x] This padding should be 24px. I looks like it's 18px + the 4px at the bottom of the input? I'm seeing this across most of the pages in this flow. 
image

- [x] These validation states within the input have the icon as 18x18 but factor in the bounding box in Figma. This makes the inner circle 13.5x13.5px. Can we reduce the icon does for all these validation states (success, alert and warning)

image

Figma:
image


- [x] The hover state is missing for the upload input (this could be a different PR, so let me know)
image

- [ ] ~Can we make this circle trigger the upload? Can we also add a hover state to it so the bg circle goes text-blue-400?
image~

- [x] The icon styling in the upload component is missing:
image
Figma:
image

- [x] When I upload a file that's too large, the UI breaks:
image


- [ ] When I upload a file that's too large and then select the trash icon inside the upload component, the component resets to the default state, but then doesn't allow me to upload another file. The whole component isn't interactable again. 
Animation1234567


Sing out if you want to have a call :)

**Review by ArmandoGraterol — APPROVED** [review]
LGTM 👍

**Review by melyndav — APPROVED** [review]
Super work on this @thomassdk. Approving this and we can look to resolve the upload library issues in a separatePR as discussed.

File: src/components/frame/v5/pages/UserProfilePage/partials/IconSuccessContent.tsx [hunk 4]
```diff
@@ -0,0 +1,38 @@
...
+const IconSuccessContent: FC<SuccessContentProps> = ({
+  open,
+  handleFileRemove,
+}) => {
+  const { formatMessage } = useIntl();
+
+  return (
+    <div className="flex items-center gap-2">
+      <Button mode="primarySolid" onClick={open}>
+        {formatMessage(MSG.change)}
```
Comment (chmanie) [inline src/components/frame/v5/pages/UserProfilePage/partials/IconSuccessContent.tsx:25]: I think we should use either Will's `formatText` or `FormattedMessage` in such cases.

File: src/components/v5/common/CreateColonyWizard/IconSuccessContent.tsx [hunk 5]
```diff
@@ -0,0 +1,52 @@
...
+      <div className={clsx('flex items-center sm:items-start gap-4')}>
+        <div className="sm:hidden text-gray-600 text-sm">{uploaderText}</div>
+      </div>
+      <div className="flex flex-col gap-2 w-full">
+        <div className="hidden sm:block text-gray-600 text-sm">
+          {uploaderText}
+        </div>
+        <div className="flex items-center gap-2">
+          <Button mode="primarySolid" onClick={open}>
+            {formatMessage(MSG.change)}
```
Comment (chmanie) [inline src/components/v5/common/CreateColonyWizard/IconSuccessContent.tsx:37]: See my comment above.

**Review by chmanie — APPROVED** [review]
I'm approving this. We can resolve the `formatMessage` issues another time. It's all over the place anyways.

**Review by rdig — APPROVED** [review]
