### PR TITLE
Fix: Mobile tab arrow alignment update

### LINKED ISSUE #3542: [Manage account - Mobiel QA] Arrows  should be more centre-aligned on Manage account
## Steps to reproduce

1. Navigate to Advanced Settings on a mobile device.
2. Observe the position of the arrow icons.

https://www.figma.com/design/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-v3?node-id=1782-9689&t=TNUwTMcnd6u8AU17-4

https://www.figma.com/design/C2grfQysdsYXz0j4rADR6K/Crypto-to-Fiat?node-id=4446-114929&node-type=frame&t=SD0CsH9hoAVCNb60-0

## Expected behaviour

* Arrows  should be more centre-aligned

## Actual behaviour

* There is a slight miss-alignment of the arrow where it should be more centre aligned

image

### PR DESCRIPTION
**Pull request by rumzledz**
## Description

Just a simple adjustment to how these components are aligned.

| Before | After |
| ---- | ---- |
| Screenshot 2024-10-31 at 22 48 04 | Screenshot 2024-10-31 at 22 47 40 |

## Testing

1. Visit the account page
2. Set the view to iPhone SE
3. Verify that the arrows are aligned along the same line as the tab copies:

image

Resolves #3542

### CODE REVIEW

File: src/components/shared/Extensions/Tabs/Tabs.tsx [hunk 1]
```diff
@@ -25,7 +25,7 @@ const Tabs: FC<PropsWithChildren<TabsProps>> = ({
         activeTab={activeTab}
         onTabClick={onTabClick}
         tabsUpperContainerClassName={clsx(
-          'before:content-[" "] relative flex w-full items-center p-0 font-semibold before:absolute before:bottom-0 before:left-0 before:block before:h-px before:w-full before:bg-gray-200',
+          'before:content-[" "] relative flex w-full items-start p-0 font-semibold before:absolute before:bottom-0 before:left-0 before:block before:h-px before:w-full before:bg-gray-200',
           upperContainerClassName,
         )}
         leftNavBtnClassName="absolute top-[50%] translate-y-[-50%] left-0 z-base"
```
Comment (mmioana) [inline src/components/shared/Extensions/Tabs/Tabs.tsx:31]: I think you need to use only `z-base` also for `leftNavBtnClassName`

**Review by mmioana — CHANGES_REQUESTED** [review]
Hey @rumzledz nice start on this issue 🙌 

Unfortunately it seems the `left` arrow tab is still not aligned, but I left a comment with the needed change


https://github.com/user-attachments/assets/75a9a297-e9ac-4a85-87d7-c0302455400c

File: src/components/shared/Extensions/Tabs/Tabs.tsx (hunk 1 above)
Comment (rumzledz) [reply src/components/shared/Extensions/Tabs/Tabs.tsx:31]: No actually we need to remove everything, apart from z-base 😅  I'll push 2 secs

Comment (rumzledz) [reply src/components/shared/Extensions/Tabs/Tabs.tsx:31]: Pushed! 🚀

**Review by mmioana — APPROVED** [review]
Awesome @rumzledz ✨ now both arrows are perfectly aligned


https://github.com/user-attachments/assets/dcdadead-0ca7-410a-b35c-8153d4671915

**Review by iamsamgibbs — CHANGES_REQUESTED** [review]
Unfortunately this has shifted the menu items along when they first load:

Screenshot 2024-11-01 at 11 43 50

Compared to master:
Screenshot 2024-11-01 at 11 44 07

**Comment by rumzledz** [comment]
> Unfortunately this has shifted the menu items along when they first load:

All right pushed! 🚀  @iamsamgibbs

**Review by iamsamgibbs — APPROVED** [review]
Looking good now! 🙌 

Screenshot 2024-11-01 at 12 24 11

**Review by rdig — APPROVED** [review]
Arrows seem to be aligned properly now. Nicely done

Screenshot from 2024-11-04 14-28-52

https://github.com/user-attachments/assets/5cccd8ab-1e2a-4875-9f18-ed756bc5437c

**Review by Nortsova — APPROVED** [review]
Great job 👍  Nicely done 
account-tab
