### PR TITLE
Fix motion staking issues

### LINKED ISSUE #1368: Validation of active tokens when staking on a motion
## Steps to reproduce
- Create an action using the Reputation decision method.
- When staking, try to stake more then your available active tokens balance.
- Currently you are able to initiate the transaction.

## Expected behavior
- The staking input should handle validation on a users available active tokens.
- It should show a validation error message with the text: "You don’t have enough active tokens. Activate more."
- The Activate more link should open the Activate tokens modal.

Figma design - https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-V5?type=design&node-id=16244-236851&mode=design&t=CVNn71ezPkGM1Y5u-4

image

## Actual behavior
- There is no validation of a users available active token balance when staking.

validation-staking

### LINKED ISSUE #1369: Handle rejected transactions when staking
## Steps to reproduce
- Create an action with the "Reputation" decision method.
- Start to stake, but instead reject the transaction in Metamask.
- You should no longer be able to stake as the button has been disabled.

## Expected behavior
- You should still be able to stake, even after rejecting the transaction.

## Actual behavior
- When rejecting a staking transaction you are no longer able to stake.

handle-rejected-transaction

### PR DESCRIPTION
**Pull request by jakubcolony**
## Description

This PR fixes issues as described in ~~#1368~~ (not anymore, automatic token activation was added in the meantime which rendered this unnecessary) and #1369. Additionally, it simplifies `TokensModalContext` and fixes an issue with displaying activated tokens balance in the staking widget.

For testing, please refer to the original issues.

Resolves #1368
Resolves #1369

### CODE REVIEW

**Review by arrenv — DISMISSED** [review]
Nice one @jakubcolony, works as expected.

I am just getting this error whenever I click the buttons in the token activation modal:

image

**Comment by rdig** [comment]
This needs / needed to be based off #1394 otherwise, most likely, changes are going to get overwritten

File: src/components/v5/common/ActionSidebar/partials/Motions/steps/StakingStep/partials/StakingForm/helpers.ts [hunk 1]
```diff
@@ -76,3 +76,24 @@ export const getPredictedPercentage = (
...
 };
+
+/**
+ * Function returning the max amount user can stake which is the smaller of
+ * the activated tokens balance and the remaining oppose or support stake amounts
+ */
+export const getMaxStakeAmount = (
+  voteType: MotionVote,
+  activatedTokens: BigNumber,
+  remainingStakes: string[],
```
Comment (bassgeta) [inline src/components/v5/common/ActionSidebar/partials/Motions/steps/StakingStep/partials/StakingForm/helpers.ts:87]: I don't have a huge issue with this, but maybe we could pass in remaining stakes in 2 parts, oppose and support remaining so it makes a bit more sense when reading it

**Review by bassgeta — DISMISSED** [review]
2 minor things which aren't related to functionality :D otherwise gj, looks solid :muscle:

File: src/components/v5/common/ActionSidebar/partials/Motions/steps/StakingStep/partials/StakingForm/helpers.ts (hunk 1 above)
Comment (jakubcolony) [reply src/components/v5/common/ActionSidebar/partials/Motions/steps/StakingStep/partials/StakingForm/helpers.ts:87]: I thought about it (more specifically fixing it at the root, so in the schema) but GraphQL doesn't seem to support tuples. Since it's kind of an established convention in the codebase already, I'll leave it as such

**Review by rdig — COMMENTED** [review]
I've tested this and all is good, but this is way out of date with `master`

Please rebase it _(and fix the merge conflicts)_, after which I'll approve it

**Review by rdig — APPROVED** [review]

**Review by ArmandoGraterol — APPROVED** [review]
Nice work Jakub 🎉
