### PR TITLE
Fix: remove comments number from agreement

### LINKED ISSUE #2505: Remove default 1 comment value from Agreements widget
## Steps to reproduce

1. Go to a colony dashboard.
2. Ensure there is an agreement.
3. Notice that, even with comments not currently being present, the comment icon shows a 1.

## Expected behaviour

* The comment icon and number can be hidden for now.

## Actual behaviour

* You are able to see a default 1 value for the comment number.

image

### PR DESCRIPTION
**Pull request by mmioana**
Remove comments number from colony home agreement card

## Description

- Remove comments number from colony home agreement card
- Add TODO to re-enable the comment number once this feature is implemented

## Testing

TODO: Check is comments number still shows for an agreement on the colony home page

* Step 1. Create an agreement
* Step 2. Go to colony dashboard
* Step 3. Check agreements section

Resolves #2505

### CODE REVIEW

**Review by melyndav — CHANGES_REQUESTED** [review]
Hi @mmioana! Great start on this one! The comment is no longer showing and all looks good. 👯

**Review by melyndav — DISMISSED** [review]

**Review by davecreaser — DISMISSED** [review]
Good idea to just comment it out for now. Problem solved :)

**Review by bassgeta — DISMISSED** [review]
Nice and straightforward :sunglasses:

File: src/components/v5/frame/ColonyHome/partials/Agreements/Agreements.tsx [hunk 1]
```diff
@@ -72,7 +71,8 @@ const Agreements = () => {
                 <span className="text-3">
                   {newestAgreement.decisionData?.title}
                 </span>
-                <MessageNumber message={1} />
+                {/* @TODO Re-enable once a Motion supports the comments feature */}
+                {/* <MessageNumber message={1} /> */}
```
Comment (rdig) [inline src/components/v5/frame/ColonyHome/partials/Agreements/Agreements.tsx:75]: Normally, I'd say to remove this altogether since we can always restore this from `git` history

**Review by rdig — DISMISSED** [review]
Can confirm the comment no longer shows. Thanks for removing the leftover code :)

Screenshot from 2024-06-19 21-10-56
Screenshot from 2024-06-19 21-11-03

**Review by bassgeta — APPROVED** [review]
No agreement comments shown on my end, so let's get this nice fix off to master! :tada:

**Comment by rumzledz** [comment]
No default comment count has dared to show itself on this branch. Merge it! 🚀 
image

**Review by rumzledz — APPROVED** [review]
