### PR TITLE
Replace link history if traveling between transactions

### LINKED ISSUE #602: Go back button from motions doesn't go back to colony home
To reproduce, ensure you have at least two different motions in the staked claims tab. Click back and forth between them a few times. 

Then click "go back" in the top left hand corner. It should "go back" to the colony, but it will instead replicate the native browser back button and take you back to the previous url, which was the other motion.

### PR DESCRIPTION
**Pull request by Julianahlk**
## Description

This solves the issue that when linking from one motion to the next using go to motion from the stakes tab, each motion is added to the history stack and the back button goes back to the previous motion.

if linking to a motion when already on a motion, the history stack will be replaced instead of pushed and now the back button will go to the previous location in the stack before navigating between motions.

Resolves #602

### CODE REVIEW

File: src/components/frame/TokenActivation/StakesTab/StakesListItem.tsx [hunk 1]
```diff
@@ -38,9 +39,15 @@ const StakesListItem = ({
   });
 
   const txHash = data?.getColonyActionByMotionId?.items[0]?.id ?? '';
+  const location = useLocation();
+  const replace = location.pathname.indexOf('/tx') !== -1;
```
Comment (jakubcolony) [inline src/components/frame/TokenActivation/StakesTab/StakesListItem.tsx:43]: How about a more descriptive name for this variable, e.g. `isMotionPage`? I feel like it'd make it easier to understand at first glance

**Review by jakubcolony — APPROVED** [review]
Nice one 👍

**Review by ArmandoGraterol — APPROVED** [review]
Nice fix 👍
