### PR TITLE
Open UserHub on pending button click

### LINKED ISSUE #2834: Pending button no longer opens transaction tab
## Steps to reproduce

1. Create a new transaction.
2. While the pending button is visible, click on it.
3. Note that it now no longer opens up the Transactions tab.

## Expected behaviour

* The pending transaction button in the header, it should open the transactions tab in the Userhub.

## Actual behaviour

* The pending transaction button in the header click no longer works.

image

### PR DESCRIPTION
**Pull request by chmanie**
## Description

This PR tries to solve the UserHub opening/closing issues by just using a single state for the visibility of the UserHub. This sadly makes things a little more complicated but there are ambitions to try to solve these issues on the UX side of things (using an improved Modal flow).

For now this should do it. We got rid of the dual state and of the ominous `data-openhubifclicked` attribute by adding some state management wizardry. We basically set the tab that should open in the UserHub from outside and then reset it once it's visible.

## Testing
1. Try to have a pending TX (e.g. use MetaMask and don't confirm)
2. Click the pending TX button and hope that the UserHub opens, showing the transactions list
3. Click outside the UserHub, it should close
4. Also click some other buttons within the UserHub (e.g. Activate tokens) and check if it behaves like it does on `master`.

## Diffs

**Changes** 🏗

- Fix UserHub open state

Resolves #2834

### CODE REVIEW

File: src/components/common/Extensions/UserHubButton/UserHubButton.tsx [hunk 1]
```diff
@@ -52,21 +55,14 @@ const UserHubButton: FC = () => {
...
-  const ref = useDetectClickOutside({
-    onTriggered: (e) => {
-      // This stops the hub closing when clicking the pending button (which is outside)
-      if (!(e.target as HTMLElement)?.getAttribute('data-openhubifclicked')) {
-        setIsUserHubOpen(false);
-      } else {
-        setIsUserHubOpen(true);
-      }
-    },
-  });
```
Comment (iamsamgibbs) [inline src/components/common/Extensions/UserHubButton/UserHubButton.tsx:69]: Good riddance 👋

File: src/components/frame/Extensions/layouts/ColonyLayout.tsx [hunk 2]
```diff
@@ -5,13 +5,15 @@ import React, {
   type PropsWithChildren,
   useCallback,
   useEffect,
+  useState,
   // useState,
```
Comment (iamsamgibbs) [inline src/components/frame/Extensions/layouts/ColonyLayout.tsx:9]: This can go

**Review by iamsamgibbs — APPROVED** [review]
Nicely done Chris! This is much nicer to work with than before.

Tested the pending transaction:

https://github.com/user-attachments/assets/a5a1a962-483e-4d64-887f-b57e35111246

Also tested it on mobile and if a failed transaction still automatically opens the userhub which is working great:

https://github.com/user-attachments/assets/2e3f8ecd-cae4-41d7-a7e9-3c404ccd6239

This is the only issue that stood out to me, it is very slow closing the userhub after the activate / withdraw modal is opened:

https://github.com/user-attachments/assets/5d5d5b7c-e5d8-49b4-8864-56039b684090

But I just checked this on QA and it is behaving the same there - not sure if there is anything simple that can be done here to improve this, but can leave it for another time as it already exists on master.

Unrelated to this PR, but I also noticed this issue when closing the userhub on mobile if you have the action sidebar open:

https://github.com/user-attachments/assets/f06100de-5145-40ef-9db5-51ef2e8a4b3d

File: src/components/frame/Extensions/layouts/ColonyLayout.tsx (hunk 2 above)
Comment (chmanie) [reply src/components/frame/Extensions/layouts/ColonyLayout.tsx]: Removed the comment and rebased, maybe you could re-approve?

**Review by iamsamgibbs — DISMISSED** [review]

**Review by jakubcolony — CHANGES_REQUESTED** [review]
Thanks for bringing some sanity to the UserHub @chmanie! 

The pending button now works flawlessly - I can click on any element of the button and it opens the transactions tab:

https://github.com/user-attachments/assets/1c824881-e504-4fad-b7e9-7bc1129af4f4

I noticed however the Completed button no longer triggers the UserHub, which is different to production:

https://github.com/user-attachments/assets/c51afd4d-9403-452e-a8ba-621787ba20c6


If you consider this a separate issue, ping me and I'll re-approve the pending button fix.

**Comment by chmanie** [comment]
> I noticed however the Completed button no longer triggers the UserHub, which is different to production

Ah no worries, I'll fix this!

**Comment by chmanie** [comment]
@jakubcolony sorted.

**Review by iamsamgibbs — APPROVED** [review]
Tested the fix, all good!

**Review by rdig — APPROVED** [review]
Works as advertised. Clicking on the pending pill brings up the correct transactions. Nicely done Chris!

[Screencast from 2024-08-07 23-52-19.webm](https://github.com/user-attachments/assets/1ff483ed-387d-4c7a-87b9-2ffc2769a2b5)

However I found two edge cases _(although they should be considered separatedly)_
- cancelling a action and not cancelling metamask will keep a pill  active, and if clicking on it will redirect you to an action that doesn't exist / 404 _(this is really edgy, I really don't think this will show up in a live environment ever)_
- cancelling metamask, or failing a transaction in some other way will add a failed transaction to the list. Clicking that failed transaction will bring you to a 404 page again. I think this can be easily replicated so I definitely think this needs to be fixed 

[Screencast from 2024-08-07 23-53-33.webm](https://github.com/user-attachments/assets/f22fa04e-875c-4996-a72c-1f72f073daa6)

**Comment by chmanie** [comment]
@rdig The 404 thing is tracked by @arrenv somewhere I just couldn't find it. Feel free to open an issue for the first bug, that sounds like a bit of an explorational task

**Review by jakubcolony — APPROVED** [review]
The Completed button triggers the user hub now, nice one @chmanie 💯
