### PR TITLE
Fix: Inconsistent balances across the ui

### LINKED ISSUE #2408: Inconsistent balances across the UI
## Steps to reproduce

1. Create a Payment builder action and fund it, don't release it.
2. Go to the balances page and pay attention to the balances updating.
3. Start to create a new Simple payment action.
4. Check the available funds from token drop down.

You will notice that there are multiple balances shown throughout the process. It would be good to understand the difference between the initial loaded value and the available funds in the token selection drop down.

## Expected behaviour

* The balances should be correct and consistent.
* Ideally, it would be good if the inclusion of funded expenditures don't load separately in the UI, to avoid confusion.

## Actual behaviour

* Balances are inconsistent between initial load, loaded state and available funds.

token-updating-inconsistent

image

### PR DESCRIPTION
**Pull request by davecreaser**
## Description

- Fix an issue where the balance was not being consistent in different places across the UI
- Add loading state to balance table

## Testing

- Go to the balances page note the balance.
- Create a Payment builder action (while still on balances page in the background) and fund it, but don't release it.
- Close the sidebar to go back to the balances page. The balance should still be the same.
- Start to create a new simple payment action (don't actually create it).
- Check the available funds from token drop down. This should be equal to the balance shown in the balance table minus the amounts currently held in expenditure funding.
- Close the sidebar to go back to the balances page.
- Refresh the page and be ready to check the loading state.
- Once the page reloads it should show a skeleton loader, and then the balances. These balances should not flicker between two numbers at all.

## Diffs

**New stuff** ✨

* New skeleton loader state in the balances page.

**Changes** 🏗

* Changes to handle cache updates when expenditures are funded.

Resolves #2408

### CODE REVIEW

**Review by iamsamgibbs — APPROVED** [review]
Nice work Dave! Code looks clean and working as expected.

Screenshot 2024-06-11 at 18 30 20
Screenshot 2024-06-11 at 18 32 46
Screenshot 2024-06-11 at 18 33 23

https://github.com/JoinColony/colonyCDapp/assets/34915414/a642570c-4005-428a-9d5c-f91d8b318a51

File: src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/PaymentBuilderWidget/PaymentBuilderWidget.tsx [hunk 1]
```diff
@@ -24,7 +25,12 @@ import { ExpenditureStep, type PaymentBuilderWidgetProps } from './types.ts';
 import { getCancelStepIndex, getExpenditureStep } from './utils.ts';
 
 const PaymentBuilderWidget: FC<PaymentBuilderWidgetProps> = ({ action }) => {
-  const { colony } = useColonyContext();
+  const { colony, refetchColony } = useColonyContext();
+  const { refetch: refetchExpenditures } = useGetColonyExpendituresQuery({
+    variables: {
+      colonyAddress: colony.colonyAddress,
+    },
+  });
```
Comment (jakubcolony) [inline src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/PaymentBuilderWidget/PaymentBuilderWidget.tsx:33]: Would it also work if you changed the fetch policy of that query inside `useColonyExpenditureBalances` to something like `cache-and-network`? That way we can avoid manually refetching from here.

**Review by jakubcolony — DISMISSED** [review]
Nice fix @davecreaser, all balances showing as expected:

https://github.com/JoinColony/colonyCDapp/assets/112586815/89528858-d74a-4b3b-be47-f16fa91c0b9c

File: src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/PaymentBuilderWidget/PaymentBuilderWidget.tsx (hunk 1 above)
Comment (davecreaser) [reply src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/PaymentBuilderWidget/PaymentBuilderWidget.tsx:33]: That's what I originally had, but then it leads back to the same issue with the table flickering an incorrect value when it's loaded, since the first one will be from the cache and then it'll grab it from the network. Also tried network-only, and whilst that worked, I didn't really like the refetching every single time, this seemed much cleaner. 🧹

File: src/components/frame/v5/pages/BalancePage/partials/BalanceTable/hooks.tsx [hunk 2]
```diff
@@ -116,6 +123,9 @@ export const useBalanceTableColumns = (
         cell: ({ row }) => {
           if (!row.original.token) return [];
 
+          if (row.original.loading)
+            return <div className="h-4 w-40 skeleton" />;
```
Comment (rdig) [inline src/components/frame/v5/pages/BalancePage/partials/BalanceTable/hooks.tsx:127]:
```suggestion
          if (row.original.loading) {
            return <div className="h-4 w-40 skeleton" />;
          }
```

But that's more of a nitpick than anything else

Comment (rdig) [reply src/components/frame/v5/pages/BalancePage/partials/BalanceTable/hooks.tsx:127]: And it applies to all other instances were you've used this pattern. 

Feel free to ignore as this is just a code style difference of oppinion

**Review by rdig — APPROVED** [review]
Some code style nitpicks, but other than that all seems good.

Nicely done.

Here's some screenshots from my testing

Screenshot from 2024-06-12 22-26-51
Screenshot from 2024-06-12 22-28-12
Screenshot from 2024-06-12 22-28-38
Screenshot from 2024-06-12 22-29-24
Screenshot from 2024-06-12 22-30-44

File: src/components/frame/v5/pages/BalancePage/partials/BalanceTable/hooks.tsx (hunk 2 above)
Comment (davecreaser) [reply src/components/frame/v5/pages/BalancePage/partials/BalanceTable/hooks.tsx:127]: Ah, I actually prefer with brackets too, I must've just done it quickly and it didn't register.

Also; I should change it as a matter of standards! https://github.com/JoinColony/ColonyFrontEndLivingStandard/blob/master/codeQuality/index.md#explicitly-scoping-if-statements

**Comment by davecreaser** [comment]
@rdig @jakubcolony @iamsamgibbs Reapproval is needed after fixing a codestyle issue please :)

**Review by iamsamgibbs — APPROVED** [review]

**Review by rdig — APPROVED** [review]
Re-approved

**Review by jakubcolony — APPROVED** [review]
