### PR TITLE
Account for Metamask not supporting the `eth_maxPriorityFeePerGas` call

### LINKED ISSUE #4147: The eth_maxPriorityFeePerGas gas not executing while using the Metamask wallet
## Steps to reproduce

1. Use Metamask wallet.
2. Open manage account -> Advanced.
3. Disable Colony pays my gas fees radio button.
4. Create simple payment with permission.
5. Create other actions.

Image

## Expected behaviour

* The payment process completes successfully, or an appropriate error message is displayed in the UI.
* The user is not left in an indefinite Pending state.

## Actual behaviour

* The Pending button remains stuck

### PR DESCRIPTION
**Pull request by rdig**
This issue came about after the introduction of #4123 which, while technically correct, runs into the a problem with Metamask, and more specifically Metamask's provider.

Even while running a manually set RPC endpoint which can be confirmed as supporting [EIP-1559](https://eips.ethereum.org/EIPS/eip-1559)

Screenshot from 2025-01-21 14-47-48

Metamask will **block the `eth_maxPriorityFeePerGas` call**

Screenshot from 2025-01-20 17-16-48

While waiting to see if this ever gets resolved _(see this PR MetaMask/metamask-extension#29818 by our very own @area)_ we are accounting for it by setting it to zero (`0`).

This means that the transaction sender will not pay anything extra, besides the required gas fee, for their transaction to be mined.

This works great on Arbitrum, Arbitrum Sepolia since they make user of a Sequencer, however, on something like Mainnet this won't work, and we'll need to find another way around it

More reading: https://docs.arbitrum.io/learn-more/faq#do-i-need-to-pay-a-tip-or-priority-fee-for-my-arbitrum-transactions

Screenshot from 2025-01-21 14-56-38

Screenshot from 2025-01-21 14-58-31

## Additional Fix

This issue actually highlighted a bug inside the `estimateGasCost` saga, where, if `maxFeePerGas` and `maxPriorityFeePerGas` were not available, we would skip updating the transaction's `options` object, however we would wait for said object to _finish_ updating which could never actually succeed.

I have fixed that as well, by moving the `take` call, which waits for the next `TRANSACTION_UPDATED_IN_DB` action, inside the logic check block.

## Testing

1. Run the dev environment: `npm run dev`
2. Create demo data: `node scripts/create-data.js`
3. Run the frontend: `npm run frontend`
4. Ensure you connect your Metamask wallet, and not your Dev wallet, and ensure you use one of the first 3 Dev wallets addresses with Metamask _(If you don't have them added, you can get them here:  http://localhost:3006/ganache-accounts.json)_
5. Go to the `planex` colony
6. Ensure you see the Metamask / gas estimator warnings _(which mean it couldn't make the `eth_maxPriorityFeePerGas` call)_ Screenshot from 2025-01-21 15-08-14
7. Ensure you see the Gas Debug Log with the `maxPriorityFeePerGas` set to `0` Screenshot from 2025-01-21 14-56-38
8. Send a transaction _(can be anything, payment, mint, extensions, etc)_
9. Ensure your TX Debug Log has the `overrides` correctly set, and inside the `overrides` you have your `maxPriorityFeePerGas` value set to `0`

_Note: that this can also be tested live on QA_

## Thanks

Special thanks to @area for actually looking into Metamask's codebase and providing a stop gas solution, as well as raising a PR with Metamask

Resolves #4147

### CODE REVIEW

File: src/redux/sagas/utils/getGasPrices.ts [hunk 1]
```diff
@@ -205,12 +228,37 @@ const fetchGasPrices = async (): Promise<GasPricesProps> => {
...
+    // have an incentive to include the transaction in a block via this "tip", or in the case of Arbitrum,
+    // a sequencer
+    // https://docs.arbitrum.io/learn-more/faq#do-i-need-to-pay-a-tip-or-priority-fee-for-my-arbitrum-transactions
+    //
+    // However this will definetly not work on Mainnet, Gnosis for example since there the miners
+    // are actively looking for this
+    //
+    // If we ever have to re-deploy to mainnet, this will need to be revisited and somehow fixed
+
+    let maxPriorityFeePerGas = BigNumber.from(0);
```
Comment (rdig) [inline src/redux/sagas/utils/getGasPrices.ts:248]: I'd wish I had some more time, so I could refactor this whole saga and avoid all this useless code repetition :disappointed:

**Review by rumzledz — APPROVED** [review]
Cheers for the easy to follow steps @rdig ! I can confirm that I can see the expected test results 💯 

## `eth_maxPriorityFeePerGas` and `maxPriorityFeePerGas` logs

Screenshot 2025-01-21 at 22 46 14

## TX DEBUG logs after sending a Transaction

Screenshot 2025-01-21 at 22 50 02

**Review by jakubcolony — APPROVED** [review]
Opening a PR to fix the underlying issue is next-level debugging... Well done to both you and @area! 👏 

Transactions with Metamask connected now go through fine both locally and in QA:

https://github.com/user-attachments/assets/f928299d-83d5-497c-be80-9b7e74ef0ab1


https://github.com/user-attachments/assets/cb34dcc4-973f-477e-89cf-3ff32076991f



`maxPriorityFeePerGas` is at 0 as expected:
image

File: src/redux/sagas/utils/getGasPrices.ts [hunk 2]
```diff
@@ -205,12 +228,37 @@ const fetchGasPrices = async (): Promise<GasPricesProps> => {
...
+    try {
+      // Ethers v5.7 just returns 1.5 GWei for maxPriorityFeePerGas. We should get it ourselves
+      const maxPriorityFeePerGasResponse = await userWallet.ethersProvider.send(
+        'eth_maxPriorityFeePerGas',
```
Comment (rdig) [inline src/redux/sagas/utils/getGasPrices.ts:252]: This should have been added as a enum

**Review by mmioana — APPROVED** [review]
Really nice work both you and @area have put for this issue! 💯 

I have followed your testing steps and could see the initial logs
Screenshot 2025-01-23 at 10 28 17
Also after creating a `Mint tokens` action, the transaction had the `overrides.maxPriorityFeePerGas` set to `0`
Screenshot 2025-01-23 at 10 28 58

@rdig I have noticed an error while running the `create-data` script, so not sure if it is related
Screenshot 2025-01-23 at 10 24 36

I'll approve this PR nonetheless 👍 nice!!

**Comment by rdig** [comment]
@mmioana the create data script error is not related, as those transactions go through a parallel system.

I have see it a few times, but it's pretty rare
