### PR TITLE
Crypto-to-fiat: Payments to liquidation address should show relevant member

### LINKED ISSUE #2733: Payments to member's liquidation address should show relevant member
## Steps to reproduce

1. Ensure member has a liquidation address that is enabled for automatic payments.
2. Make a payment to that member in USDC.
3. The payment will be made to the users liquidation address.
4. Notice the recipient in the completed action Recipient fields and the metadata in the completed action and activity feeds.

## Expected behaviour

* You should see the members username as it was selected during the payment creation in relevant locations for the payment i.e.:
    - Recipient field in the completed action.
    - Metadata in the completed action.
    - Metadata in the activity feeds.

## Actual behaviour

* You don't see the associated member, instead you see the liquidation address. Resulting in confusion to users as to who received the payment.

    image

    image

### PR DESCRIPTION
**Pull request by jakubcolony**
## Description

This PR fixes a number of issues around displaying the relevant user whose liquidation address a payment was made to. 

When payment is made to the liquidation address, it should be swapped with relevant user in the following places:
- Simple payment action (action description, recipient field)
- Advanced payment action (recipients in the table)
- Activity feed action descriptions

## Testing

Unless you're testing against Bridge production, there's no way to test this properly as the sandbox generated addresses are not valid ETH addresses.

For that reason, we'll create a liquidation address in the DB manually. In production, this will be done by the `checkKyc` handler whenever it finds that a user doesn't have an address linked to their bank account already.

```gql
mutation CreateLiqAdd {
  createLiquidationAddress(
    input: {
      chainId: 265669100,
      userAddress: "0xb77D57F4959eAfA0339424b83FcFaf9c15407461", # Change if not using Dev Wallet 1
      liquidationAddress: "0x87bDe603bF318B2eb2C88B161CA5c1718e712137" # Use any address you want
    }
  ) {
    id
  }
}
```

Make simple and advanced payments to the created liquidation address. In each of the places listed above, it should be replaced with your user's details.

https://github.com/user-attachments/assets/dbd7243a-f2a1-4d71-b75f-d23c44e781b0

https://github.com/user-attachments/assets/70e83485-7ec0-4663-981c-48e4c754cddd

**Note:** The recipient field's user popover will show the address twice instead of the username, it's an existing issue tracked by #2891.

Resolves #2733

### CODE REVIEW

File: amplify/backend/function/bridgeXYZMutation/src/handlers/checkKyc.js [hunk 1]
```diff
@@ -182,13 +179,29 @@ const checkKYCHandler = async (
...
+      if (liquidationAddressCreation.status === 201) {
+        externalAccountLiquidationAddress =
+          liquidationAddressCreationRes.address;
+
+        // create liquidation address entry in the database
+        await graphqlRequest(
+          createLiquidationAddress,
+          {
+            input: {
+              chainId: 42161,
```
Comment (jakubcolony) [inline amplify/backend/function/bridgeXYZMutation/src/handlers/checkKyc.js:191]: This will be made into an env variable once they're set up in lambdas

**Review by rdig — APPROVED** [review]
Working as expected. Nicely done.

I just created the liquidation address

Screenshot from 2024-08-08 17-56-03

Then I created a payment. While it was "pending", the address still was displayed as the one I've manually pasted in, but once the action was completed, it got replaced by the user profile

Screenshot from 2024-08-08 18-00-16
Screenshot from 2024-08-08 18-00-24
Screenshot from 2024-08-08 18-00-30

**Review by rumzledz — APPROVED** [review]
Great stuff @jakubcolony ! I connected Dev Wallet 1 and it correctly detects that it's Leela's liquidation address ✨ 

**Simple Payment**
2753_sp

**Advanced Payment**
2753_ap

**Review by bassgeta — APPROVED** [review]
Nicely done, I created a payment action to the liquidation address and then it loaded into `leela`.
image

:ship:
