### PR TITLE
fix: if split payment uses split by reputation, filter out if reputatation in that team is 0

### LINKED ISSUE #3717: [Split payment] User with zero reputation can be added to split payment with "Reputation Percentage" distribution
## Steps to reproduce

1. Go to the split payment section.
2. Set the distribution method to "Reputation Percentage."
3. Add a user with zero reputation to the recipient list.
4. Attempt to proceed with the payment creation.

## Expected behaviour

* User with zero reputation cannot be added to split payment with "Reputation Percentage" distribution

## Actual behaviour

* The system allows users with zero reputation to be added with "Reputation Percentage" distribution

image

Also, pay attention to how the amount changed after adding a new recipient without a reputation 

https://github.com/user-attachments/assets/cc600ee7-e8c5-4e3a-963e-1b634408a77d

### PR DESCRIPTION
**Pull request by bassgeta**
## Description

Basically I started propagating the `domainId` on to `UserSelect` and fixed a `find` statement.
Not sure if we should do this for form validation too? Seems a bit overkill for now.

## Testing

Right so it may be tricky with create data being semi-flaky and all, but let's go
1. After running the `create-data` script, open up `Wayne` (`Planex` would work too, just use a member with no reputation in a child team
image
image
2. Create a `Split payment` action, use `Reputation percentage` for `Distribution`. 
image
3. Verify that the member select has all the members when `General` is selected as the team
image
4. Verify that the members with 0 reputation in `Advanced technologies` are filtered out when choosing that as the `Team`
image

## Diffs

**Changes** 🏗

* `UserSelect` now doesn't fallback to reputation in `General`
* `SpliPaymentRecipientField` now passes the form's domainId to `UserSelect` and filters out 0 reputation members if decision method is `SplitPaymentDistributionType.Reputation`

Resolves  #3717

### CODE REVIEW

**Review by mmioana — DISMISSED** [review]
Really nice work on this one @bassgeta 🙌 

It all works as expected 💯 

Reputation in Wayne's `All teams`
Screenshot 2024-12-18 at 23 04 54

Members with reputation in `Advanced Technologies`
Screenshot 2024-12-18 at 23 04 58

Created a `Split payment` with `Reputation percentage` as distribution type in `General`
Screenshot 2024-12-18 at 23 05 38

Then selected `Advanced Technologies` and can confirm the user select updates the list accordingly
Screenshot 2024-12-18 at 23 05 55

Then removed reputation for `fry` in `Advanced Technologies`
Screenshot 2024-12-18 at 23 10 39

He's no longer among the members in `Advanced Technologies`
Screenshot 2024-12-18 at 23 10 45

And can confirm he no longer appears in the user select dropdown for the `Split payment`
Screenshot 2024-12-18 at 23 11 17

Nice work! 🥇

**Review by Nortsova — DISMISSED** [review]
Great work on this @bassgeta 🎉  

General:
image
Advanced technologies:
image

**Review by iamsamgibbs — APPROVED** [review]
Nice job filtering these out.

General - with reputation:
Screenshot 2025-01-09 at 13 50 06

Advanced Technologies - without reputation:
Screenshot 2025-01-09 at 13 50 23

However, you can still select the member by pasting their wallet address into the field, and then it seems like the reputation percentages aren't actually affected by the selected team. This can be a new issue though.

https://github.com/user-attachments/assets/d67b98c4-19a9-4d5d-abf2-21b716d3600c

**Review by mmioana — APPROVED** [review]
Still works as expected 💯 

Screenshot 2025-01-15 at 12 49 24
Screenshot 2025-01-15 at 12 49 47
Screenshot 2025-01-15 at 13 28 00
Screenshot 2025-01-15 at 14 38 46
Screenshot 2025-01-15 at 14 38 49
Screenshot 2025-01-15 at 14 39 08
Screenshot 2025-01-15 at 14 39 14
Screenshot 2025-01-15 at 14 41 00
Screenshot 2025-01-15 at 14 42 19
Screenshot 2025-01-15 at 14 42 31

**Review by iamsamgibbs — APPROVED** [review]
Nice job, all still working as expected:

Screenshot 2025-01-15 at 18 21 12
Screenshot 2025-01-15 at 18 21 19

File: src/components/v5/common/ActionSidebar/partials/forms/SplitPaymentForm/SplitPaymentForm.tsx [hunk 1]
```diff
@@ -24,7 +25,7 @@ const SplitPaymentForm: FC<ActionFormBaseProps> = ({ getFormOptions }) => {
   const hasNoDecisionMethods = useHasNoDecisionMethods();
 
   const { watch, trigger } = useFormContext();
-  const selectedTeam = watch('team');
+  const selectedTeam = watch(TEAM_FIELD_NAME);
```
Comment (davecreaser) [inline src/components/v5/common/ActionSidebar/partials/forms/SplitPaymentForm/SplitPaymentForm.tsx:28]: 🧹

**Review by davecreaser — APPROVED** [review]
Nice one @bassgeta, code looks nice and clean and it works as expected during testing. Good to go!

Screenshot 2025-01-17 at 19 20 04
Screenshot 2025-01-17 at 19 20 12
Screenshot 2025-01-17 at 19 21 06
Screenshot 2025-01-17 at 19 24 36
