### PR TITLE
Fix: Correctly identify and handle the "Unknown" notifications

### LINKED ISSUE #3571: [Notifications - QA] Unknown notification displayed in the notification panel
## Steps to reproduce

1. 2 users with role owner enable all notifications in the colony
2. User 1 Create an advanced or split payment as in the picture 1, 2below 
3. User 2 opens notifications

## Expected behaviour

* Each notification should display relevant information about the event, making it clear to the user.

## Actual behaviour

* Some notifications are displayed as "Unknown notification," providing no context or details.
image
image

image

### PR DESCRIPTION
**Pull request by rumzledz**
## Description

Whenever we create an expenditure (Advanced payment), we basically create 2 kinds of notifications in our Block Ingestor:

1. `NotificationType.Mention` notification via `sendMentionNotifications()` in `expenditureRecipientSet.ts`
2. `NotificationType.ExpenditureReadyForReview` notification via `sendExpenditureUpdateNotifications()` in `expenditureAdded.ts`

The reason why it was saying unknown is because we are simply not handling Mention notifications for Expenditures in the `Notification.tsx` file so all I'm doing is handling it here:

| Before | After |
| ---- | ---- |
| Screenshot 2024-11-05 at 08 45 24 | Screenshot 2024-11-05 at 08 44 47 |

## Testing

1. Give Amy Owner permissions in General
2. As Leela, create an Advanced Payment using this setup:

image

3. Log in as Amy
4. Open the Notifications tab
5. Verify that you no longer see the "Unknown" notification item
6. You can also checkout to `master` at this point to compare the result

Resolves #3571

### CODE REVIEW

File: src/components/v5/common/CompletedAction/partials/CompletedExpenditureContent/CompletedExpenditureContent.tsx [hunk 1]
```diff
@@ -88,8 +88,9 @@ const CompletedExpenditureContent: FC<CompletedExpenditureContentProps> = ({
   const tokensCount = getTokensNumber(expenditure);
   const stagedPaymentTokenSymbol =
     tokensCount === 1 &&
-    allTokens.find(({ token }) => token.tokenAddress === stages[0].tokenAddress)
-      ?.token.symbol;
+    allTokens.find(
+      ({ token }) => token.tokenAddress === stages[0]?.tokenAddress,
+    )?.token.symbol;
```
Comment (rumzledz) [inline src/components/v5/common/CompletedAction/partials/CompletedExpenditureContent/CompletedExpenditureContent.tsx:93]: Irrelevant fix but it's to prevent the Completed Action component from crashing. There's an isolated PR that also fixes this: https://github.com/JoinColony/colonyCDapp/pull/3627

File: src/components/common/Extensions/UserHub/partials/NotificationsTab/partials/Notification/Expenditure/ExpenditureNotification.tsx
Comment (mmioana) [inline src/components/common/Extensions/UserHub/partials/NotificationsTab/partials/Notification/Expenditure/ExpenditureNotification.tsx:1]: I'd suggest to split the `ActionNotificationMessage` into `PermissionsNotificationMessage` and `MentionNotificationMessage` and use the `MentionNotificationMessage` here.

Also, maybe the logic for retrieving the `creator`'s display name would be better suited to be added directly in the `MentionNotificationMessage` component

**Review by mmioana — CHANGES_REQUESTED** [review]
Awesome fix for this issue @rumzledz 🙌 🌟 

Tried out assigning roles and the notifications still show up
Screenshot 2024-11-05 at 10 03 07

And then created an advanced payment
Screenshot 2024-11-05 at 10 03 57
Screenshot 2024-11-05 at 10 04 04

And `amy` got her mention notification
Screenshot 2024-11-05 at 10 04 13

So, the only reason I'll reject this is for some refactoring that will help us better structure the notifications. I'm leaving below more details. However if you think it doesn't make sense, please reach out and I'll approve your PR 🙌

**Comment by rumzledz** [comment]
Shoutouts to @mmioana for the pair programming session and brainstorming ways to refactor the Notification mentions related components 🙌 🚀

**Review by mmioana — APPROVED** [review]
Approving these changes as me and @rumzledz had a pair programming session on this one 👍 nice nice!!! 💯

**Review by mmioana — APPROVED** [review]
Still working well after rebasing @rumzledz ✨ 

Screenshot 2024-11-05 at 16 59 29
Screenshot 2024-11-05 at 17 00 21
Screenshot 2024-11-05 at 17 00 44
Screenshot 2024-11-05 at 17 01 47

**Review by rdig — APPROVED** [review]
I can confirm I no longer see "Unknown" notifications. Nicely done!

Screenshot from 2024-11-06 17-41-04
Screenshot from 2024-11-06 17-41-42
Screenshot from 2024-11-06 17-41-58
Screenshot from 2024-11-06 17-42-07

**Review by Nortsova — APPROVED** [review]
Hey, thanks for this fix ✨ 

No "Unknown" notifications 🙌 
image
