### PR TITLE
Fix: Correctly sort timeframe bar chart items

### LINKED ISSUE #4087: [Dashboard] Total in and out chart bars are not correctly ordered
## Steps to reproduce

1. Go to a colony dashboard page, eg. http://localhost:9091/planex 
2. Check the `Total in and out` card chart
Screenshot 2025-01-14 at 12 33 37
You can see `January` is displayed before the previous months
However the `timeframe` array is correctly ordered for this query
Screenshot 2025-01-14 at 12 33 57

## Expected behaviour

* The bars from the `Total in and out` card chart should be ordered correctly by date

## Actual behaviour

* The bars from the `Total in and out` card chart are not ordered correctly by date

## Suggestions (optional)

The problem is related to the sorting after parsing the date label in `src/context/TotalInOutBalanceChartContext/TotalInOutBalanceChartContextProvider.tsx`

Screenshot 2025-01-14 at 12 46 06

### PR DESCRIPTION
**Pull request by mmioana**
## Description

- This PR aims to fix the `Total in and out` chart bars sorting.
The issue was caused by the fact that once the `GetDomainBalance` would retrieve the data, we would subtract from the `timeframe.key` the `Month` and then perform a sort based on this value. This would behave properly if the keys are within the same year, however, it would cause an incorrect sorting once a new year starts - issue that can be observed on `master`. To fix this, once the `GetDomainBalance` retrieves data we would map the items to the `BarChartDataItem` type, followed by a sort on the label (the `timeframe.key`) and only after mapping the label to the full date format `dd-MM-yyyy`. Then the `getMonthShortName` will be responsible to retrieve the short month label format (`Jan`, `Feb` etc.)

**On this branch**
Screenshot 2025-01-20 at 12 53 30

**Master**
Screenshot 2025-01-20 at 12 57 18

## Testing

TODO: Let's test our changes behave as expected. 

* Step 1. Go to http://localhost:9091/planex
* Step 2. Check the chart on the `Total in and out` card has `Jan` as the last item on the x-axis
Screenshot 2025-01-20 at 12 53 30
* Step 3. Let's test this behaves as expected also with some other values
* Step 4. Please replace  `domainBalanceData?.timeframe` from line `84` in `src/context/TotalInOutBalanceChartContext/TotalInOutBalanceChartContextProvider.tsx` with
```json
[{ "key": "10-12-2024", "value": undefined, }, { "key": "10-09-2024", "value": undefined, }, { "key": "01-10-2024", "value": undefined, }, { "key": "10-11-2024", "value": undefined, }]
```
* Step 5. Check the chart on the `Total in and out` card has `Sep`, `Oct`, `Nov` and `Dec` correctly sorted
Screenshot 2025-01-20 at 14 29 15

* Step 5. Now replace  `domainBalanceData?.timeframe` from line `84` in `src/context/TotalInOutBalanceChartContext/TotalInOutBalanceChartContextProvider.tsx` with
```json
[{ "key": "10-12-2024", "value": undefined, }, { "key": "10-09-2024", "value": undefined, }, { "key": "01-10-2024", "value": undefined, }, { "key": "10-12-2025", "value": undefined, }]
```
* Step 6. Check the chart on the `Total in and out` card has two entries for `Dec`, one for `2024` and one for `2025`
Screenshot 2025-01-20 at 14 36 35

> [!NOTE]
> This is more of an extreme case, that should never happen and will require label updates to include also the year for better UX. However, it is treated for the moment in a way to ensure data doesn't get overridden in case there are matching months from different years.

## Diffs

**New stuff** ✨

* `IntermediateBarChartDataItem` type for storing the `label` as `Date` until the sorting by date is performed

**Changes** 🏗

* Updated to mapping, sorting and label formatting for the bar chart items

Resolves #4087

### CODE REVIEW

File: src/components/v5/frame/ColonyHome/partials/TotalInOutBalance/utils.ts [hunk 1]
```diff
@@ -30,23 +43,28 @@ export const parseTimeframeKey = (key: string = '') => {
...
-export const getFallbackData = () => {
+export const mapToFormattedLabel = (item: IntermediateBarChartDataItem) => ({
+  ...item,
+  label: format(item.label, 'dd-MM-yyyy'),
+});
+
+export const getFallbackData = (): BarChartDataItem[] => {
   const now = new Date();
   const currentMonth = now.getMonth();
-  const fallbackData: any = [];
```
Comment (mmioana) [inline src/components/v5/frame/ColonyHome/partials/TotalInOutBalance/utils.ts:39]: Totally missed this before 🫠

**Review by davecreaser — APPROVED** [review]
Nice fix @mmioana!

All the sorting works great now:

Screenshot 2025-01-23 at 14 06 07
Screenshot 2025-01-23 at 14 07 08
Screenshot 2025-01-23 at 14 07 13
Screenshot 2025-01-23 at 14 07 36
Screenshot 2025-01-23 at 14 07 43

**Review by rdig — APPROVED** [review]
Very nice! Working as expected! :100: 

Screenshot from 2025-01-23 19-55-43
Screenshot from 2025-01-23 19-57-21
Screenshot from 2025-01-23 19-57-51

**Review by Nortsova — APPROVED** [review]
New year - new bug 😄

Nice catch and great solution 🙌 ✨ 
 
image

image

image
