### PR TITLE
Fix: No transaction action sidebar styling and behaviour

### LINKED ISSUE #3670: No transaction 404 styling and links
## Steps to reproduce

1. Enter in a transaction URL that does not exists. e.g. http://localhost:9091/planex?tx=0x
2. Note the layout of the transaction 404.

## Expected behaviour

* The styling of the action panel 404 should match the design - [Figma link](https://www.figma.com/design/5V8pr7iMwXsT9L3VAZsmUt/Actions-%26-Motions?node-id=23947-236415&t=bsEF0JbB2xNLxycb-4) 
* The "Create new action" link should open a new create action panel.

## Actual behaviour

* The styling of the action panel 404 is broken.
* The "Create new action" link does not do anything.

image

### PR DESCRIPTION
**Pull request by mmioana**
## Description

- This PR aims fixing the broken styling for the not found action sidebar content, as well as the navigation to creating a new action from its `Create a new action` link
 
https://github.com/user-attachments/assets/1a403449-6d33-4754-bcdd-94b0dc763208

## Testing

TODO: Please check the navigation to creating a new action works properly, UI adjustments match [Figma](https://www.figma.com/design/5V8pr7iMwXsT9L3VAZsmUt/Actions-%26-Motions?node-id=23947-236415&t=bsEF0JbB2xNLxycb-4) and then we'll proceed to some regression testing 🙌 

* Step 1. Navigate to http://localhost:9091/planex?tx=0x
* Step 2. Check the action sidebar content matches the [Figma](https://www.figma.com/design/5V8pr7iMwXsT9L3VAZsmUt/Actions-%26-Motions?node-id=23947-236415&t=bsEF0JbB2xNLxycb-4) 

Screenshot 2024-12-27 at 17 04 00

* Step 3. Click on `Create a new action` and make sure the action form is opened

https://github.com/user-attachments/assets/6ebdd2a8-0b73-45d6-a04a-d7a41354eabf

* Step 4. In `src/components/v5/common/ActionSidebar/ActionSidebar.tsx` at line `95` please update the timeout value to `1000`
Screenshot 2024-12-27 at 17 00 20

* Step 5. Navigate to http://localhost:9091/planex?tx=0x0ab68d8464728f01260ae8e37e8b1ea2263803fffebb1da300b7d7335abb4f34

Any `tx` value that doesn't already exist should be fine

* Step 6. Click on the `Create a new action` link and make sure it behaves correctly. Go back. Click on the `Go to activity page` link and make sure it behaves correctly. Go back. Click on `Retry` button.

https://github.com/user-attachments/assets/b48bdbf3-3cfb-4c01-a2a7-a27b60d83d5d

* Step 7. Now a bit of regression testing. Please create a mint tokens action.

Screenshot 2024-12-27 at 17 05 08

* Step 8. Make sure you can see the completed action screen and the action sidebar doesn't get closed by default.

Screenshot 2024-12-27 at 17 07 45

* Step 9. Open the notifications and click on the `Incoming funds` one. Make sure you get to the `Incoming funds` page and the action sidebar gets closed.

https://github.com/user-attachments/assets/353d6095-8ff6-4f1d-9cf3-3833c317cd34

## Diffs

**New stuff** ✨ 

* `ActionNotFound` component

**Changes** 🏗

* Replaced `useLocationChange` with `useLocationPathnameChange` as this was causing the action sidebar to get closed upon removing the `txHash` even though the pathname remained the same
* Add `className` to `FourOFourMessage`

Resolves #3670

### CODE REVIEW

File: src/components/v5/common/ActionSidebar/ActionSidebar.tsx [hunk 1]
```diff
@@ -118,65 +113,11 @@ const ActionSidebar: FC<PropsWithChildren<ActionSidebarProps>> = ({
...
-                </Button>
-              )
-            }
-          />
-        </div>
+        <ActionNotFound
+          isInvalidTransactionHash={isInvalidTransactionHash}
+          onCloseSidebar={toggleActionSidebarOff}
+          onRefetchAction={startPollingForAction}
+        />
```
Comment (davecreaser) [inline src/components/v5/common/ActionSidebar/ActionSidebar.tsx:120]: Good idea 🧹

**Review by davecreaser — APPROVED** [review]
Nice fix and nice cleanup @mmioana! Good idea to separate it out into a new component for sure.

Action not found looks and works good:
Screenshot 2024-12-31 at 15 42 25

https://github.com/user-attachments/assets/e7d128e4-60c6-4218-b5b2-0aad366769ce


And there's no regressions with closing the sidebar or completed actions:
Screenshot 2024-12-31 at 16 03 44
Screenshot 2024-12-31 at 16 04 41

**Review by bassgeta — APPROVED** [review]
Nice one with decoupling this into a separate component, a nice holiday cleanup :sunglasses: 
404 shows up :heavy_check_mark: 
image
Links  work correctly :heavy_check_mark: 

https://github.com/user-attachments/assets/4224b6ac-a0a6-4db5-a24c-814bbea10b23

Regressions also pass, I can navigate between actions without any issue :sunglasses:

**Review by iamsamgibbs — APPROVED** [review]
Nice job! This is a lot cleaner, and everything is working as expected.

New action link works
https://github.com/user-attachments/assets/eaf6d228-97b4-4ce5-9c40-148dd2ff2a77

Activity page link works
https://github.com/user-attachments/assets/983cd27f-8640-4ac1-bdb2-8d6dfc77374f

Incoming funds notification closes sidebar and navigates to the correct page
https://github.com/user-attachments/assets/ca721eec-7f2e-4e39-9d6a-7ec52ce6d864
