### PR TITLE
fix: form prefill and team name validation

### LINKED ISSUE #1793: Teams: Editing a team not prefilling data
Teamwork task: [Teams: Editing a team not prefilling data](https://tw.auroracreation.com/#/tasks/15763105)

## Description

Issue one: 
On the new Teams page recently deployed to production, when selecting the kebab menu and then 'Edit team' on a team, the side panel does not pre-fill the existing teams data (name and description). 

The scope of this issue is to prefill the associated data when a user selects to edit a specific team via the teams kebab menu icon. 

## Steps to reproduce

- In production, navigate to the teams page.
- Select the kebab menu icon on a team card.
- From the dropdown menu, select edit a team.
- The sidepanel should trigger but will display empty. 

Issue two:

The error state for the team name is showing inline as well as the error notification box at the bottom of the action. Please remove this inline error state so the error only shows in the main notification box at the bottom when the field has been left empty.

image

### PR DESCRIPTION
**Pull request by mksawic**
## Description

https://tw.auroracreation.com/app/tasks/15763105

**Changes** 🏗

* Cast domainNativeId into Number to correctly fill edit team form
* Fix team name validation 

Resolves #1793

### CODE REVIEW

**Review by melyndav — CHANGES_REQUESTED** [review]
Hey @mksawic nice work on this PR! 👍 

Can the team pill also be pre-filled? Everything else pre-fills when I select the team, but this is the only empty field

image

Because it's not prefilling the data, there is no validation state, meaning I can submit the action without needing a team selected. So resolving the above issue means this field can never be left empty. 

image

**Review by ArmandoGraterol — COMMENTED** [review]
Experiencing the same issues Mel already pointed out. I didn't spot anything else so I'll re-review once that's addressed

File: src/utils/domains.ts [hunk 1]
```diff
@@ -13,7 +13,7 @@ export const findDomainByNativeId = (
   }
   return domains
     .filter(notNull)
-    .find(({ nativeId }) => nativeId === domainNativeId);
+    .find(({ nativeId }) => nativeId === Number(domainNativeId));
```
Comment (bassgeta) [inline src/utils/domains.ts:16]: isn't domainNativeId already a number or undefined/null? if we cast `null` or `undefined` to Number we'll get 0, so this may give us a headache in the future

File: src/components/v5/common/ActionSidebar/partials/TeamsSelect/TeamsSelect.tsx [hunk 2]
```diff
@@ -38,7 +38,7 @@ const TeamsSelect: FC<TeamSelectProps> = ({
     },
   ] = useToggle();
   const selectedOption = teamsOptions.find(
-    (option) => option.value === selectedTeam,
+    (option) => option.value === Number(selectedTeam),
```
Comment (bassgeta) [inline src/components/v5/common/ActionSidebar/partials/TeamsSelect/TeamsSelect.tsx:41]: Is it possible for saving the value as a number directly?

**Review by bassgeta — CHANGES_REQUESTED** [review]

**Review by iamsamgibbs — DISMISSED** [review]
From a UI perspective, this is working great for me. Good work! Although please address bassgeta's concerns.

Screenshot 2024-01-31 at 10 50 37

**Review by melyndav — APPROVED** [review]
Working great for me now, thanks for fixing the team pre-fill. 👍  @mksawic approved!

**Review by ArmandoGraterol — APPROVED** [review]
LGTM 👍

**Review by warrencolliver — APPROVED** [review]
Looks good, I'll re-approve if necessary once Bassgeta's review has been considered

File: src/utils/domains.ts (hunk 1 above)
Comment (mksawic) [reply src/utils/domains.ts]: It was transformed into string in `useTeams` method when user clicked "Edit team" button.

File: src/components/v5/common/ActionSidebar/partials/TeamsSelect/TeamsSelect.tsx (hunk 2 above)
Comment (mksawic) [reply src/components/v5/common/ActionSidebar/partials/TeamsSelect/TeamsSelect.tsx]: As above. Id now is passed as number to EditTeamForm

**Review by bassgeta — APPROVED** [review]
