### PR TITLE
Fix: Prevent TX button from being stuck in a pending state

### LINKED ISSUE #3760: The Transaction Button can oftentimes be stuck in the Pending state
## Steps to reproduce

1. Install the Multi-Sig extension
2. Set the threshold to 2
3. Give Leela and Amy permissions to take actions via Multi-Sig
4. Create an Advanced Payment
5. Progress until you reach the Funding stage
6. Click the "Fund" button:

image

7. Select the Multi-Sig decision method:

image

8. Submit the modal
9. Remove your vote by clicking the Remove button:

image

10. Reject the motion
11. Repeat steps 4 - 10, at some point, the app's Transaction Button will be stuck in the Pending state:

perpetual-pending

12. Install the Reputation extension

## Expected behaviour

The app's Transaction Button should correctly reflect the correct global transaction state.

## Actual behaviour

The app's Transaction Button is stuck on the Pending state.

pending-after-reputation-installation

### PR DESCRIPTION
**Pull request by rumzledz**
## Description

I found that some grouped transactions do legitimately have transactions with a zero address hash so I removed the part inside `getGroupStatus` where it determines if a transaction group is considered to have succeeded if there are no transactions with an address zero hash.

perpetual-pending-fix

## Testing

> [!NOTE]
> If you do end up seeing the TX Button in a "stuck" pending state, verify if it is indeed pending by checking the same transaction inside the User Hub. If the transaction is marked as Pending inside the User Hub then, it really is in a "Pending" state. Maybe it's an environment issue or something 🤔 

1. Connect Leela's wallet
2. Install the Reputation extension
3. Uninstall it
4. Repeat steps 1-2 a couple of times and verify that the TX Button is not stuck in a Pending state
5. Install the Multi-Sig extension
6. Give Amy and Leela permissions to take actions via Multi-Sig
7. Create an advanced payment
8. Fund it via Multi-Sig
9. Remove your default Yay vote
10. Reject the Multi-Sig motion
11. Repeat steps 8-10
12. Verify that the TX Button is not stuck in a perpetual loading state

Resolves #3760

### CODE REVIEW

File: src/components/common/Extensions/UserHub/partials/TransactionsTab/partials/GroupedTransaction.tsx [hunk 1]
```diff
@@ -55,6 +56,8 @@ const GroupedTransaction: FC<GroupedTransactionProps> = ({
   const groupId = getGroupId(transactionGroup);
   const status = getGroupStatus(transactionGroup);
   const values = getGroupValues<TransactionType>(transactionGroup);
+  const hasZeroAddressTransaction =
+    getHasZeroAddressTransaction(transactionGroup);
```
Comment (rumzledz) [inline src/components/common/Extensions/UserHub/partials/TransactionsTab/partials/GroupedTransaction.tsx:60]: Still needed to preserve the fix done on https://github.com/JoinColony/colonyCDapp/pull/2945

**Review by iamsamgibbs — APPROVED** [review]
Nice job! I would have expected this to be a much more complex issue, so I'm glad it was a relatively small fix!

Tested installing and uninstalling the extension a bunch of times and the pending button no longer gets stuck.

I tried following the rest of your testing steps to create an advanced payment funding expenditure, but it is not possible on master (I'm guessing you originally worked on this on Kerry's branch?) So I instead did a couple of funding reputation motions instead without issue.

I tried clicking a few transactions from the transactions tab to make sure they were still clickable and all seems to still be working.

I believe @chmanie worked on this pending button quite a lot, so if possible might be good to get a sanity check from him that this change won't have any intended consequences!

**Review by mmioana — CHANGES_REQUESTED** [review]
Nice start on this issue @rumzledz 🙌 

Installing and un-installing the `Reputation Weighted` extension

https://github.com/user-attachments/assets/3866601c-7cba-4cac-b585-66ac88ad21a3


As @iamsamgibbs I couldn't test the `Multi-sig` funding step for an `Advanced payment` as I guess the base branch should've been [feat/3497-funding-expenditure-multisig](https://github.com/JoinColony/colonyCDapp/pull/3553)


Even though with your fix I couldn't reproduce any longer getting the `TX button` in a never-ending `Pending` state, I believe there is an issue if you try to open a transaction related to the extension installation. 
However @rumzledz  if you believe it makes more sense to treat it in a separate PR let me know and I'll approve 🙌 


https://github.com/user-attachments/assets/f7b3da5a-8b5b-4ead-83d2-a2bc80c45f69

**Comment by rumzledz** [comment]
Hey @iamsamgibbs ! That's a good shout! I'll speak to @chmanie just in case 🤙 

The issue that @mmioana mentioned about the User Hub is something that's already on `master`(I didn't introduce it on this PR) and I believe it's been there for quite a while. It's also a very different issue from the stuck Pending button. So I've requested that we create a different issue for it so we can deal with it separately 🙌

**Comment by chmanie** [comment]
I believe I was summoned?

**Comment by rumzledz** [comment]
@iamsamgibbs I have just received a 🦭 of approval from @chmanie 🚀

**Review by rdig — CHANGES_REQUESTED** [review]
I manage to get it stuck again while voting/revealing a motion

Granted, on all the other instances I've tried (installing, uninstalling extensions) the bending state went again after the transaction was finished, so I think it's almost there


https://github.com/user-attachments/assets/dee6e62a-34d5-492c-a650-aa83400549c7

**Review by rdig — APPROVED** [review]
Never mind, I can no longer replicate it.

Most likely you were correct in your assessment Romeo, that it could have been that the actual tx wasn't finished, hence why the pending state was still displaying

Here's another go at it, and after the transactions finish, the pending state goes away.

Nicely done!


https://github.com/user-attachments/assets/b8110d07-a1b0-4515-8800-c1bc16a72f95

**Comment by rumzledz** [comment]
@rdig @iamsamgibbs oh right I see! I saw a similar thing in some other PR I reviewed recently as well where there was a tiny window of opportunity for me to click the "Change vote" button before the form properly progresses to the next step. In any case, I'll stay vigilant about this pending state 👌
