### PR TITLE
Fix: Add form validation when removing permissions

### LINKED ISSUE #2241: Manage permissions action: Removing permissions state
Teamwork task: [Manage permissions action: Removing permissions state](https://tw.auroracreation.com/#/tasks/15881119)

## Description 

When I select a user and remove their permissions, the frontend in the completed action state have a case to cover this and just shows 'custom' action as a fallback as shown in the screenshot below. 

The scope of this PR is to add a case where there are no permissions, then it shows removed. 

image

You can replicate this issue by:

1. Open the Manage permissions action
2. Select a user with permissions
3. Select to remove the permissions option from the permissions dropdown
4. Complete the action and see that the UI doesn't handle showing the removal action

A secondary issue is to remove the extra space in the metadata
image
 
 
 ## Figma
 
image

https://www.figma.com/file/SaO0Zj6e7yGqLzjEsxqVhy/Permissions?type=design&node-id=20717-29092&mode=design&t=YMpH7KQuqTQqjAKA-4

### LINKED ISSUE #2339: Removing permissions from users with and without permissions
Teamwork task: [Removing permissions from users with and without permissions](https://tw.auroracreation.com/#/tasks/15917226)

## Steps to reproduce

1. Create a Manage permissions action.
2. Select a user who does not have any permissions.
3. Select the Permissions `Remove permissions`.
4. Complete the action.

## Expected behaviour

* There should be validation for if the user selected to remove permissions from the select team has no permissions.
* It should show the users permissions that are being removed.
* In the completed state, it would be great to show what permissions were removed.
   * The table will be different to the one that shows what actions could be performed. And should only show the permissions that was removed, e.g. Payer. as of design.

Figma link - Show users permissions being removed
https://www.figma.com/file/SaO0Zj6e7yGqLzjEsxqVhy/Permissions?type=design&node-id=21033-15030&mode=design&t=AY627sl2nwE6qp6q-4

Figma link - Show validation if user does not have permissions
https://www.figma.com/file/SaO0Zj6e7yGqLzjEsxqVhy/Permissions?type=design&node-id=21033-15227&mode=design&t=AY627sl2nwE6qp6q-4

image

## Actual behaviour

* The transaction will succeed, but you receive an Apollo error. The transaction does not move to a completed state though.
* If you add an annotation, you will get stuck in pending.

image

image

### LINKED ISSUE #2755: Validation for awarding permissions in a child team
### Description

When a user or contract is assigned permissions in a colony, those same permissions are also inherited by child teams. For example, if a member is assigned Funding permissions in the "Root/General" team, then in a child team, such as "Development", that user will also hold the Funding permission.

However, these Funding permissions cannot be removed from the child team specifically, which we now show a validation for. To further improve our validation, we would also like to prevent assigning permissions to users that they already hold in a parent team.

### Different permission types
As we have tiered permissions now, we need to account for the differences between the individual core permissions that a user can hold. It may make sense for them to hold some permissions in "Root/General" and another set in child teams, as long as they are not the same permissions.

**Simple tiered permission case**
- This case shows the handling of a like-for-like tiered permission being selected. [Figma link](https://www.figma.com/design/SaO0Zj6e7yGqLzjEsxqVhy/Permissions?node-id=22235-29385&t=LGHHOXNVu1tPmO8U-4)
image

**Simple custom permission case**
- This case shows the handling of a like-for-like custom permission. The toggle is on and disabled with a tooltip. [Figma link](https://www.figma.com/design/SaO0Zj6e7yGqLzjEsxqVhy/Permissions?node-id=22238-28226&t=LGHHOXNVu1tPmO8U-4)
image

### Partial tiered permissions
Additionally, we will also need to handle situations where some permissions are held in "Root/General" but more are required in the child team, and there is an overlap with the tiered permissions. For example, a user holds "Custom (Funding)" in "Root/General" and is now being assigned "Admin" in a child team. It would be misleading to just show "Admin", even though that is somewhat accurate, as when removing, you would not be able to remove "Admin" permissions.

Therefore, we would like to provide a validation error if a tiered permission is selected where there is an overlap, but also provide a way for users to still easily assign the desired permissions. To do this, we would like there to be a information to help guide the user to set the difference in required permissions, i.e., assigning only "Administration", "Architecture", and "Arbitration" in the child team while the "Custom (Funding)" in "Root/General" is disabled and toggled on with the tooltip.

- [Figma Link](https://www.figma.com/design/SaO0Zj6e7yGqLzjEsxqVhy/Permissions?node-id=22236-22939&t=LGHHOXNVu1tPmO8U-4)
image

### This issue is complete when...

- [ ] A validation message appears if a user already holds the same permission in a parent team for a tiered permission, preventing awarding the same permissions to the user in a child team.
- [ ] A disabled toggle state and tooltip are shown in a child team with inherited individual custom permissions, preventing awarding the same permissions to the user in a child team.
- [ ] If a tiered permission is selected in a child team, the user should be prompted to toggle the difference with custom permissions in the child team to simplify the UI and help provide the desired outcome.
- [ ] Multi-sig permissions are also considered, but are completely separate from these core permissions.

### LINKED ISSUE #3395: [Member permissions] 403 Error when assigning duplicate permissions to a user
## Steps to reproduce

1. Navigate to the Permissions page
2. Assign a specific permission (e.g., "Admin") to a user (e.g., Amy) in Team Andromeda
3. Attempt to assign the same permission ("Admin") to the same user (Amy) in Team Andromeda
4. Observe the 403 error message displayed

## Expected behaviour

* The system should allow the assignment of duplicate permissions without errors

## Actual behaviour

* 403 Forbidden error is displayed, and the permission assignment fails

image

### PR DESCRIPTION
**Pull request by rumzledz**
## Description

> [!NOTE]
> This PR is meant for actions made via the Permissions Decision Method
> There are `master` bugs related to the Reputation Decision Method which are present on this PR and they will be dealt with separately
> Multi-Sig will be dealt with separately

### Removing Root permissions from someone in a Parent domain
remove_root_domain

### Removing permissions from someone in a subdomain
remove_subdomain

## Testing

> [!IMPORTANT]
> - Make sure you have at least 2 Owners in your Colony's Parent domain because if you accidentally remove Root permissions from the only Owner in your Colony, you'll have to restart your env again
> - Give Fry the much coveted Owner permissions in team General
> - Give alex-the-ace the Payer permissions in team General
> - Give Amy the Admin permissions in team Andromeda
> - Give diana-dynamo these Custom permissions in team General
>   - Administration
>   - Arbitration
> - Give eddy-edge these Custom permissions in Serenity
>   - Architecture
>   - Arbitration

> [!NOTE]
> - The Redo action is now disabled for actions that have explicitly removed permissions from a user
> - When removing Root permissions from someone in a parent domain, we will now notify the user of the consequences and have them acknowledge our message before they can submit the form
> - Toggles for inherited permissions are now disabled

### 1. Selecting Remove Permissions for a member who has permissions for the selected team (Fry)
| Step | Expected Result |
| ---- | ---- |
| Set up the following fields<br />- Team: General<br />- Member: Fry<br />- Permissions: Remove permissions: | You should not see an error message |

### 2. Selecting Remove Permissions for a member who does not have permissions for the selected team (jasmine-jolt)
| Step | Expected Result |
| ---- | ---- |
| Set up the following fields<br />- Team: General<br />- Member: jasmine-jolt<br />- Permissions: Remove permissions: | Error message: "Member does not have permissions in this team" |

### 3. Checking that the Remove permission option persists when changing the Team & Member fields (Fry)
| Step | Expected Result |
| ---- | ---- |
| 1. Set up the following fields<br />- Team: General<br />- Member: Fry<br />- Permissions: Remove permissions: | |
| 2. Set the Team field to Andromeda | The Permissions field should still be set to Remove permissions |
| 3. Set the Member field to Leela | The Permissions field should still be set to Remove permissions |

### 4. Removing permissions from someone who has inherited permissions from the Parent domain (Fry)
| Step | Expected Result |
| ---- | ---- |
| 1. Set up the following fields<br />- Team: Andromeda<br />- Member: Fry<br />- Permissions: Remove permissions: | Error message: "Permissions inherited from a parent team, select the parent team to remove permissions." |

### 5. Upgrading a user's role, when the user has an inherited role (alex-the-ace)
| Step | Expected Result |
| ---- | ---- |
| 1. Set up the following fields<br />- Team: Andromeda<br />- Member: alex-the-ace<br />- Permissions: Admin | Error message: "This member already has Payer permissions inherited from a parent team. You can select the Custom permission type and enable the Architecture permission to have the required permissions in this team." |

### 6. Downgrading a user's role, when the user has an inherited role (alex-the-ace)
| Step | Expected Result |
| ---- | ---- |
| 1. Set up the following fields<br />- Team: Andromeda<br />- Member: alex-the-ace<br />- Permissions: Mod: | Error message: "Permissions inherited from a parent team, select the parent team to remove permissions." |

### 7. Applying the same inherited role for a user (alex-the-ace)
| Step | Expected Result |
| ---- | ---- |
| 1. Set up the following fields<br />- Team: Andromeda<br />- Member: alex-the-ace<br />- Permissions: Payer: | Error message: "This member already has Payer permissions inherited from the parent team" |

### 8. Upgrading a user's role, when the user has inherited Custom permissions (diana-dynamo)
| Step | Expected Result |
| ---- | ---- |
| 1. Set up the following fields<br />- Team: Andromeda<br />- Member: diana-dynamo<br />- Permissions: Admin | Error message: "This member already has Custom (Arbitration and Administration) permissions inherited from a parent team. You can select the Custom permission type and enable the Architecture and Funding permissions to have the required permissions in this team." |

### 9. Downgrading a user's role, when the user has inherited Custom permissions (diana-dynamo)
| Step | Expected Result |
| ---- | ---- |
| 1. Set up the following fields<br />- Team: Andromeda<br />- Member: diana-dynamo<br />- Permissions: Mod: | Error message: "Permissions inherited from a parent team, select the parent team to remove permissions." |

### 10. Applying the same inherited permissions for a user (diana-dynamo)
| Step | Expected Result |
| ---- | ---- |
| 1. Set up the following fields<br />- Team: Andromeda<br />- Member: diana-dynamo<br />- Permissions: Custom: | |
| 2. Submit the form | Error message: "This member already has these custom permissions inherited from the parent team" |

### 11. Checking if the inherited permission toggles are disabled (diana-dynamo)
| Step | Expected Result |
| ---- | ---- |
| 1. Set up the following fields<br />- Team: Andromeda<br />- Member: diana-dynamo<br />- Permissions: Custom: | |
| 2. Hover over the Administration and Arbitration toggles | You should see a tooltip that says: "Permission already inherited from a parent team" |
| 3. Click the Administration and Arbitration toggles | Nothing should happen as they are disabled |

### 12. Removing Root permissions from someone who does not have inherited permissions from a Parent domain (Amy)
| Step | Expected Result |
| ---- | ---- |
| 1. Set up the following fields<br />- Team: Andromeda<br />- Member: Amy<br />- Permissions: Remove permissions: | You should see a table with the following UI<br />image<br />- it's basically the bullet-pointed list of Colony actions pertinent to the user's Role, in this case it's Admin<br />- The table body copy should say "Removal of the following Colony actions"<br />- The table header should say "Remove {role} type" |
| 2. Fill in all other required fields | |
| 3. Submit the form | You should see a table with the following UI<br />Screenshot 2024-07-25 at 16 04 19<br />- The Redo action button should not be available<br />- You should see the same table UI as you did prior to submission |

### 13. Removing Root permissions from someone in a Parent domain (Fry)
| Step | Expected Result |
| ---- | ---- |
| 1. Set up the following fields<br />- Team: General<br />- Member: Fry<br />- Permissions: Custom permissions: | |
| 2. Fill in all other required fields | |
| 3. In the Custom Permissions table, toggle off Root | |
| 4. Submit the form | You should see the following Modal:<br />image<br />- You should not be able to click the "Update permissions" button |
| 5. Close the modal | |
| 6. Set the Permissions field to Remove permissions | |
| 7. Submit the form | You should see the following Modal:<br />image<br />- You should not be able to click the "Update permissions" button |
| 8. Set the Permissions field to Admin | |
| 9 Submit the form | You should see the following Modal:<br />image<br />- You should not be able to click the "Update permissions" button<br />- Basically, you should see the permissions you will lose, in this case, downgrading to Admin permissions will take away your Root & Recover permissions |
| 8. Tick the "I understand the risk and want to remove Root permissions" checkbox | The Update permissions button should now be enabled |
| 9. Click the Update permissions button | The modal closes and the form is submitted |

### 14. Upgrading Custom permissions to a Role (diana-dynamo)
| Step | Expected Result |
| ---- | ---- |
| 1. Set up the following fields<br />- Team: Andromeda<br />- Member: diana-dynamo<br />- Permissions: Custom<br />- Toggle on Funding | The copy underneath the Action title should say "Assign Payer permissions for diana-dynamo in Andromeda by leela" |
| 2. Submit the form | |
| 3. Redo the action | Screenshot 2024-07-24 at 02 36 55 |
| 4. Wait for the Action form to come up | The permissions field should say "Payer" |
| 5. Submit the form | Error message: "This member already has these permissions"<br />This should not say inherited anymore since the Custom Permissions are customised on Team Andromeda |
| 6. Set the Permissions field to Custom | - Error message: "This member already has these permissions"<br />- The Administration & Arbitration toggles are still disabled because these are inherited from the Parent domain<br />- The Funding toggle is switched on and it should be editable<br />- The Architecture toggle is switched off but you should be able to edit it |
| 7. Set the Team field to Serenity | Error message: "This member already has these custom permissions inherited from the parent team"<br />Which makes sense because the Custom Permissions for this domain are left untouched and are the same as the Parent domain |

### 15. Checking the disabled state of Permissions toggles in the Completed Action component (eddy-edge)
| Step | Expected Result |
| ---- | ---- |
| 1. Set up the following fields<br />- Team: Serenity<br />- Member: eddy-edge<br />- Permissions: Custom: | |
| 2. Switch off the Architecture toggle | |
| 3. Submit the form | - On the Completed Action component, you should only see Arbitration switched on<br />- Even though the Arbitration toggle is disabled, verify that it is not greyed out |

## Diffs

**Changes** 🏗

- Exposed the Action Form's Primary button props via `getFormOptions` 
- There's a mixture of references to Colony Roles, most notably "roles" or "permissions". In this PR, I have decided to refer to Colony Roles as "Permissions" to help differentiate it from a User Role which is our syntactic sugar to describe a set of permissions
- With the Manage Permissions form, we have a couple of instances where we have to reference a user's role from a DB along with the current role that's selected on the form. So I decided to prepend role/permissions-related variables with either "db" or "form" to differentiate their source I believe this helps with the readability.

Resolves #2339
Resolves #2241 
Resolves #2755
Resolves #3395

### CODE REVIEW

**Review by arrenv — CHANGES_REQUESTED** [review]
@rumzledz Great work on this, I appreciate your hard work and for working through the cases.

Everything seems to work as expected, in which the warning and confirmation modal appears in the situation whenever the `Root` permission is removed.

My only request would be to close down the modal on clicking the confirmation. That way we return to the action panel, and users can access their Userhub without having to have it float over the top.

image

**Review by iamsamgibbs — CHANGES_REQUESTED** [review]
Nice work with this @rumzledz ! 🎉  This form is looking a lot nicer with these reworks. I agree with all your decisions around naming choices.

Following your testing steps everything works as expected.

Screenshot 2024-07-23 at 09 57 04

Screenshot 2024-07-23 at 09 57 14

Screenshot 2024-07-23 at 10 00 08

Screenshot 2024-07-23 at 10 02 34

I have found one issue with the pill here, the `Admin` set of permissions is being removed here, but the `Custom` pill shows:

Screenshot 2024-07-23 at 10 01 10

There is a bigger issue with the inherited permissions. In this example, I have given custom permissions not including roles 5 or 6 in General. I have a sub domain with just role 6, another with 5 and 6 plus some other roles. With the way things are currently setup, it is impossible to remove roles 5 or 6 from the sub-domains as the form assumes they are inheriting their roles from General.

https://github.com/user-attachments/assets/927b46e8-860e-4bb0-8afe-5a0e2fd64849

**Comment by rumzledz** [comment]
> There is a bigger issue with the inherited permissions. In this example, I have given custom permissions not including roles 5 or 6 in General. I have a sub domain with just role 6, another with 5 and 6 plus some other roles. With the way things are currently setup, it is impossible to remove roles 5 or 6 from the sub-domains as the form assumes they are inheriting their roles from General.

Thanks for this @iamsamgibbs , let me take a trip back to Arren's inbox to discuss this and other bits of knowledge that I haven't grasped yet!

**Comment by rumzledz** [comment]
image
Nice catch @iamsamgibbs! I'll see what's going on here 🔎

**Review by melyndav — CHANGES_REQUESTED** [review]
Hey @rumzledz, nice start on this PR. A couple points of feedback that additional to @arrenv and @iamsamgibbs notes. 

1. The title font size in the removal confirmation modal is a bit bigger than what's in Figma and what's consistent with the other global modals.

**Figma:** 

image

---

2. The font in the p should match Figma (gray-600)

image

**Figma:**

image

---

3. The default state of the table when the 'remove permission' option is selected should match what we've got in Figma. This will avoid the duplicate table showing in the confirmation modal. 

Link to design: https://www.figma.com/design/SaO0Zj6e7yGqLzjEsxqVhy/Permissions?node-id=21336-77392&t=sxwbLXpC1zDPn27F-4 

image

---

4. I also assigned 1 custom (admin) permission to Jasmin Jolt fromt he custom table. However the 'Mod' pill shows up in the table (I think this might have been raised).

image



Wanted to leave a final comment on how nicely formatted your PR's are! Really easy to follow and also visually appealing. 🙌

**Comment by rumzledz** [comment]
Hey @melyndav thanks for reviewing this!
1 & 2: Whoops!
3. All right, got it now! I'll strictly reserve the new table design just for Custom permissions
4. This might be a bit tricky because just having Administration permissions is a 1:1 match for being a Mod but all right, I'll see what I can do 👌

**Comment by melyndav** [comment]
> Hey @melyndav thanks for reviewing this! 1 & 2: Whoops! 3. All right, got it now! I'll strictly reserve the new table design just for Custom permissions 4. This might be a bit tricky because just having Administration permissions is a 1:1 match for being a Mod but all right, I'll see what I can do 👌

For #4 I'll super confirm this with Arren as it was a confusing UX but understand there are limitations. I will get back to you. 👍

**Review by iamsamgibbs — DISMISSED** [review]
Nice work on this huge rework! Thank you for the very thorough testing steps, followed them all without issue and couldn't think of any further scenarios to test.

I only noticed one small issue, but I think it should be opened in a new issue to get this one merged in:

When redoing the action, and typing in the members dropdown it should clear the field but it doesn't, so you get the error message that member is a required field even though it appears to have a value. (This only happens when redoing the action). 

https://github.com/user-attachments/assets/707691a5-79b6-43ab-a118-38197c8970f5

Great job!

**Review by melyndav — CHANGES_REQUESTED** [review]
Hey @rumzledz appreciate your continued work on this one, I know it's been a big one, and I've appreciated all your Discord comms to get this one sorted. So epic effort here! 

Just some minor pick-ups:

1. In the table during the action creation, the table heading 'Remove Custom type' - type needs to say _permissions._ 

image

Figma:
image


2. When it's a 'Custom' permission bundle being removed, can we show the custom pill in the confirmation modal? I feel like it was there previously, but it's not showing for me now.

image
 
Figma:

image

**Review by iamsamgibbs — CHANGES_REQUESTED** [review]
Mel's issues appear resolved. 🎉

Screenshot 2024-07-29 at 09 51 18

Screenshot 2024-07-29 at 09 52 49

I've found two new issues though. The first half of this video shows the permissions table always showing the "custom" pill regardless of the selected permissions type (later in the video when I switch to Fry it does show the correct pill, so it doesn't seem to always happen). The second half shows when you switch to a user with custom permissions (Amy) then switch to a user with no permissions, the "custom" type stays selected rather than resetting the field.

https://github.com/user-attachments/assets/eb27a832-0e4d-4225-9e50-b86a70b9e38e

**Comment by rumzledz** [comment]
> The second half shows when you switch to a user with custom permissions (Amy) then switch to a user with no permissions, the "custom" type stays selected rather than resetting the field

@iamsamgibbs aw man, I think this is because of the actual function we use to retrieve the user's role. The way it's written is the default role value is "custom" even if you don't have permissions 😕 but all right, I'll try to do something about that 👌

**Review by iamsamgibbs — DISMISSED** [review]
Thanks for fixing the previous issue! I've followed through all the testing steps another time and all is still working as expected.

**Review by melyndav — DISMISSED** [review]
Re-reviewed and all is looking good. Appreciate you picking up my previous comment and fixing the UI @rumzledz! 👍

**Review by iamsamgibbs — COMMENTED** [review]
Great work on this @rumzledz - I know there has been a ton of work put into this and it has changed about 100 times, so it's great to see this nearly closed out.

#3070 + #2967 + #2339 + #2241 + 2755 - I followed the testing steps from all of these issues without any problems when assigning both core permissions and multi-sig permissions.

Great job! I've not tested the original testing steps in this issue - I'm assuming someone else will check through those whilst reviewing, but I'm also happy to re-review and go through those specific steps too.

I ran into one issue which hasn't been mentioned anywhere before, so feel free to tackle this as a separate issue, but if you assign "Payer" permissions in "Andromeda", then assign "Admin" permissions in "General", then attempt to remove the "Payer" permissions from "Andromeda" you will get this error:

Screenshot 2024-09-11 at 18 18 59

I think this was maybe an intentional decision at one point, but the contracts allow it so we should remove this restriction.

Here's a collection of screenshots from my testing for your enjoyment:

Screenshot 2024-09-11 at 18 13 11
Screenshot 2024-09-11 at 18 16 37
Screenshot 2024-09-11 at 18 18 20
Screenshot 2024-09-11 at 18 18 59

**Comment by rumzledz** [comment]
> I think this was maybe an intentional decision at one point, but the contracts allow it so we should remove this restriction.

Okay this will be much easier to explain in a call tomorrow but TLDR: Yes, this PR aims to have a very deliberate logic that prevents inherited permissions from being downgraded or removed. What happened here was a user already has an existing role for a subdomain which is on a lower tier compared to the one that was subsequently set on the root domain. And so the validation is getting confused 😆

I'll speak to product tomorrow to see how we can deal with this scenario 👌 Thanks for this @iamsamgibbs !

**Comment by rumzledz** [comment]
@iamsamgibbs all right after speaking with Arren, here's the new issue as promised #3083. It comes with its own complexities as an edge case so as discussed, it will be dealt with separately 👌

**Review by iamsamgibbs — DISMISSED** [review]
Nice job!

One small issue with testing step 6. This might be better to address as a separate PR for the sake of getting this merged. The error message appears as expected, but disappears when changing any other field.

https://github.com/user-attachments/assets/0485a37e-997b-45f9-a0a4-f22ea064265b

Otherwise I think we are maybe good?!

Proof of testing

Step 1:
Screenshot 2024-09-17 at 14 17 47

Step 2:
Screenshot 2024-09-17 at 14 18 32

Step 3:
No screenshot

Step 4:
Screenshot 2024-09-17 at 14 32 39

Step 5:
Screenshot 2024-09-17 at 14 33 12

Step 6:
Has an issue

Step 7:
Screenshot 2024-09-17 at 14 34 37

Step 8:
Screenshot 2024-09-17 at 14 35 31

Step 9:
Screenshot 2024-09-17 at 14 39 41

Step 10:
Screenshot 2024-09-17 at 14 40 40

Step 11:
Screenshot 2024-09-17 at 14 41 04

Step 12:
Screenshot 2024-09-17 at 14 41 36
Screenshot 2024-09-17 at 14 41 53

Step 13:
Screenshot 2024-09-17 at 14 42 42
Screenshot 2024-09-17 at 14 42 56
Screenshot 2024-09-17 at 14 43 06

Step 14:
Screenshot 2024-09-17 at 14 45 05
Screenshot 2024-09-17 at 14 45 31
Screenshot 2024-09-17 at 14 45 51
Screenshot 2024-09-17 at 14 52 46

**Review by rdig — CHANGES_REQUESTED** [review]
So codewise this is all good. You deserve praise for just having to deal with this mess of components.

I've ran the setup phase, as well as all the test steps, but cannot replicate test steps: 10, 12, 13 and 15

I suspect their parameters changed through all the subsequent changes you've made to the PR and the description was not updated.

If that's the case, just let me know, and I'll re-run those steps with the new instructions.

**Setup phase:**

Screenshot from 2024-09-19 09-51-28
Screenshot from 2024-09-19 09-52-04
Screenshot from 2024-09-19 09-52-34
Screenshot from 2024-09-19 09-53-22
Screenshot from 2024-09-19 09-54-41

**Test 1:**

Screenshot from 2024-09-19 09-56-44
Screenshot from 2024-09-19 09-57-02

**Test 2:**

Screenshot from 2024-09-19 09-59-48

**Test 3:** 

Screenshot from 2024-09-19 10-01-55
Screenshot from 2024-09-19 10-02-00
Screenshot from 2024-09-19 10-02-06

**Test 4:**

image

**Test 5:**

image

**Test 6:**

image

**Test 7:**

image

**Test 8:**

image

**Test 9:**

image

**Test 10:**

**Cannot replicate!**: No error message shows up

image

**Test 11:**

Screenshot from 2024-09-19 10-13-05
Screenshot from 2024-09-19 10-13-10

**Test 12:**

**Cannot replicate!**: Getting an error, preventing me from submitting the form

image

**Test 13:**

**Cannot replicate!**: I was able to submit the form / modal

image
image
image

**Test 14:**

image
image
image
image
image
image

**Test 15:**

**Cannot replicate**: Cannot switch off the Architecture toggle

image

**Comment by rumzledz** [comment]
Hey @rdig! I forgot to mention that I retested steps 10, 12, 13 & 15 yesterday before rebasing and I was able to do them. I've rebased yesterday, retested and I'm still able to do them. Hopefully you'll be able to see it working again when you retest 🤞

**Review by iamsamgibbs — DISMISSED** [review]
Great job dealing with all of this @rumzledz ! Let's get it merged!

The only weird behaviour I've noticed is the validation on the permissions field disappearing when the title is updated, but I think this can be addressed as a separate issue.

https://github.com/user-attachments/assets/8b9edd74-45af-4d75-baa6-e29f130c7821

I did a tiny bit of multi-sig testing and it seems like there are no issues there:

https://github.com/user-attachments/assets/a298a07c-69e5-4e7f-80e6-fde91035acd2

I did screenshot and record all of the testing steps, but I won't dump them all here as it'll end up as a huge reply, but all the testing steps work as expected.

Great job! I can't believe this form will finally be fixed forever once this is merged and there will never be another issue with it again! :)

**Review by Nortsova — APPROVED** [review]
Hey @rumzledz 🙌  Thank you for this huge PR and really good described test cases. It was a pleasure to review this one 😃  I can't wait to have it merged 🎉  

I tested it both regular and Multi-sig. There are a tiny comments in the bottom of this review, but I would be happy if we can create separate tickets for that (if it is a bug actually). 

Thank you so much for your work 🙌 

#2 Remove permissions error:
image

#3. After selected fry and general "Remove permissions" selection was still present, error was there:
image
I tried the same with leela who has a permissions in general and error disapeared: 
image

#4, 6 Fry is Owner in General
Here is removing permissions error in child domain: 
image

And downgrading role:
image

#5 Upgrading role error:
image

#7 The same role error:
image

#8 User have custom permissions in parent domain:
image

#9 Downgrading when user has Custom in parent domain:
image

#10 The same Custom permissions in parent domain:
image

#11 Toggle tooltip: 
image

#12 removing permissions from amy who doesn't have inherited permissions
image
No "Redo" button:
image

#13 Remove Root permission from fry by toggling off this permission in Custom:
image
Selected Admin role (downgrade) 
image

#14 Before I submited form the copy underneath the Action title was "Assign Admin permissions for diana-dynamo in Andromeda by leela", after I submitted Action Completed form says "Assign Custom permissions for diana-dynamo in Andromeda by leela" 
image
p.s. Admin role is correct here because I already added "Architecture" permission to her.

Redo says Payer:
image

#15 Completed actions toggles are correct:
image





-------------
I don't know if this was intended, but here the case where Remove Permissions doesn't call modal:
Fry is Owner in General
Select Custom
Toggle off Root (submit)
Come back to this form ("Redo" button)
Select "Remove permissions"
Submit (No modal shows)

The same was happen in this case:
Fry Owner in General
Downgrade Fry to admin in General (submit) - Warning modal is shown
Press "Redo"
Downgrade to Payer - No modal

One more thing, I would propose to update styles for disabled Custom permissions: 
image

File: src/utils/strings.ts
Comment (mmioana) [inline src/utils/strings.ts:1]: I'm wondering if it would make sense to make use of `react-intl` pluralisation feature and also create a message descriptor for the `and`?

**Review by mmioana — APPROVED** [review]
Awesome work and a great deal of effort on this one @rumzledz 👏 🥇 

Went through all your well documented testing steps and can confirm everything works as expected

`Setting up the dev env`

Screenshot 2024-10-28 at 13 58 01
Screenshot 2024-10-28 at 13 58 40
Screenshot 2024-10-28 at 13 59 14
Screenshot 2024-10-28 at 13 59 53
Screenshot 2024-10-28 at 14 00 39

1. Selecting Remove Permissions for a member who has permissions for the selected team (Fry)
Screenshot 2024-10-28 at 14 01 57
Screenshot 2024-10-28 at 14 02 01

2. Selecting Remove Permissions for a member who does not have permissions for the selected team (jasmine-jolt)
Screenshot 2024-10-28 at 14 03 06

3. Checking that the Remove permission option persists when changing the Team & Member fields (Fry)


https://github.com/user-attachments/assets/23f1ed55-c767-498a-9a7b-133fca694215

4. Removing permissions from someone who has inherited permissions from the Parent domain (Fry)
Screenshot 2024-10-28 at 14 04 36

5. Upgrading a user's role, when the user has an inherited role (alex-the-ace)
Screenshot 2024-10-28 at 14 05 46

6. Downgrading a user's role, when the user has an inherited role (alex-the-ace)
Screenshot 2024-10-28 at 14 06 02

7. Applying the same inherited role for a user (alex-the-ace)
Screenshot 2024-10-28 at 14 06 24

8. Upgrading a user's role, when the user has inherited Custom permissions (diana-dynamo)
Screenshot 2024-10-28 at 14 06 47

9. Downgrading a user's role, when the user has inherited Custom permissions (diana-dynamo)
Screenshot 2024-10-28 at 14 07 03

10. Applying the same inherited permissions for a user (diana-dynamo)

https://github.com/user-attachments/assets/a5cd1af1-d350-4b57-bd48-a8febfbd9aee

11. Checking if the inherited permission toggles are disabled (diana-dynamo)

https://github.com/user-attachments/assets/f68357f4-49f1-408e-8a49-60744e526f6b


12. Removing Root permissions from someone who does not have inherited permissions from a Parent domain (Amy)
Screenshot 2024-10-28 at 14 09 15
Screenshot 2024-10-28 at 14 09 31
Screenshot 2024-10-28 at 14 09 45

13. Removing Root permissions from someone in a Parent domain (Fry)
Screenshot 2024-10-28 at 14 10 29
Screenshot 2024-10-28 at 14 10 34
Screenshot 2024-10-28 at 14 10 43
Screenshot 2024-10-28 at 14 11 24
Screenshot 2024-10-28 at 14 12 56
Screenshot 2024-10-28 at 14 13 08
Screenshot 2024-10-28 at 14 13 15

14. Upgrading Custom permissions to a Role (diana-dynamo)

Screenshot 2024-10-28 at 14 13 54
Screenshot 2024-10-28 at 14 13 59
Screenshot 2024-10-28 at 14 14 18
Screenshot 2024-10-28 at 14 14 39
Screenshot 2024-10-28 at 14 14 57
Screenshot 2024-10-28 at 14 15 20

https://github.com/user-attachments/assets/738f3c19-1c2c-4b0b-ab0d-c2a02ada882d

15. Checking the disabled state of Permissions toggles in the Completed Action component (eddy-edge)
Screenshot 2024-10-28 at 14 16 05
Screenshot 2024-10-28 at 14 16 53


Left a small refactoring comment, but that can be treated as a separate issue/improvement 👍 @rumzledz

File: src/components/v5/common/ActionSidebar/hooks/useActionFormProps.ts [hunk 1]
```diff
@@ -19,13 +19,12 @@ const useActionFormProps = (
...
 ) => {
   const prevActionTypeRef = useRef<Action | undefined>();
-  const navigate = useNavigate();
   const [actionFormProps, setActionFormProps] = useState<ActionFormOptions>({
     actionType: ActionTypes.ACTION_EXPENDITURE_PAYMENT,
     defaultValues,
     mode: 'onChange',
-    onSuccess: () => {},
     validationSchema: ACTION_BASE_VALIDATION_SCHEMA,
+    onSuccess: () => {},
```
Comment (mmioana) [inline src/components/v5/common/ActionSidebar/hooks/useActionFormProps.ts:27]: Please add `noop` here

**Review by iamsamgibbs — APPROVED** [review]
Gone through most of the testing steps again since the rebase and all still working well! 🚢

**Review by rdig — APPROVED** [review]
Retested all the steps that I couldn't before and everything now works as you laid out in your testing plan. Very nice.

Thank for your patience and determination to see this to the end.

:100: 

**Setup Phase**

Screenshot from 2024-10-28 21-43-17
Screenshot from 2024-10-28 21-43-48
Screenshot from 2024-10-28 21-44-30
Screenshot from 2024-10-28 21-45-13
Screenshot from 2024-10-28 21-45-58

**Test 10**

Screenshot from 2024-10-28 21-48-16
Screenshot from 2024-10-28 21-48-26

**Test 12**

Screenshot from 2024-10-28 21-49-51
Screenshot from 2024-10-28 21-50-01

**Test 13**

Screenshot from 2024-10-28 21-50-47
Screenshot from 2024-10-28 21-51-15
Screenshot from 2024-10-28 21-51-29
Screenshot from 2024-10-28 21-51-46

**Test 15**

Screenshot from 2024-10-28 21-54-20

**Review by Nortsova — APPROVED** [review]
I did small retest and it seems it still working as expected 👍 

Lest merge 🎉  🥳
