### PR TITLE
fix: Add addresses to a Colony even if they are not members

### LINKED ISSUE #2314: Ability to add addresses to verified members list
## Steps to reproduce

1. Create a Manage verified members action.
2. Enter an address into the select member field.
3. It will validate with an error that the address is not found in the members list.

## Expected behaviour

* You should be able to verify addresses, even if they are not members.
* This should also account for if a member leaves a colony and deletes their username.

## Actual behaviour

* You are not able to add addresses to the verified members list.

image

### PR DESCRIPTION
**Pull request by rumzledz**
## Description

This will allow any entity with a wallet address to be a added as a Colony contributor.

verifying_non_member

### Pre-requisite
1. Comment out the `block-ingestor` block in the `colony-cdapp-dev-env-orchestration.yaml` file
image
2. Run `npm run dev` as usual
3. On a separate terminal tab, go to the directory where you've cloned the `block-ingestor` repo and checkout to branch `fix/2314-remove-whitelist-references`
```bash
git fetch
git checkout fix/2314-remove-whitelist-references
```
4. Run `npm run dev`

### Making sure invites still work
1. Create a new Colony
2. Generate an invite link for this Colony
3. Log into a different dev wallet and visit the invite link
4. Join the Colony
5. Make sure that nothing is broken with that flow

### Adding a non-Colony member address
1. Start the Manage Verified Members action
2. Copy the wallet address for another account that is NOT currently a contributor to your Colony
3. Submit the form
4. Make sure that the address is added as Contributor to your Colony
5. Log in using the the dev wallet you just added as a Contributor
6. Make sure you cannot can access the Colony at this point
7. Create an invite URL for Colony X, visit it and join it
8. Verify that:
  a.) you can see yourself as a verified contributor for Colony X
  b.) Running this query in GraphQL explorer will show `isVerified: true` and `hasPermissions: false` for the contributor and make sure you're looking at the correct colony for the contributor
  ```
  query GetContributorByAddress {
    getContributorsByAddress(
      contributorAddress: "{enter the contributor's wallet address}"
    ) {
      items {
        isVerified
        user {
          profile {
            displayName
          }
        }
        hasPermissions
        colony {
          name
        }
      }
    }
  }
  ```
Screenshot 2024-05-31 at 15 33 53

## Diffs

**New stuff** ✨

- A new hook called `useIsContributor` which checks if a wallet address is a Contributor for a Colony. It uses @bassgeta's `useJoinedColonies` hook under the hood. It's really just a convenience hook and is currently used for routing a user to a Colony's actual page or its visitor page.

```typescript
const { isContributor, loading: isContributorLoading } = useIsContributor({
  colonyAddress,
  walletAddress: user?.walletAddress,
});
```

**Changes** 🏗

- If a contribute leaves a Colony and re-joins the Colony via an invite, the `validateUserInvite` lambda now sets the contributor's `isWatching` field to true so they can access the Colony.

```typescript
if (contributorExistenceCheckQuery?.data?.getColonyContributor) {
  // If the user has already been a contributor for a Colony before,
  // switching their isWatching field to true will allow them to access it again
  const colonyMemberIsWatchingMutation = await graphqlRequest(
    updateColonyContributor,
    {
      input: {
        id: getColonyContributorId(colonyAddress, userAddress),
        isWatching: true,
      },
    },
    graphqlURL,
    apiKey,
  );

  if (
    colonyMemberIsWatchingMutation.errors ||
    !colonyMemberIsWatchingMutation.data
  ) {
    const [error] = colonyMemberIsWatchingMutation.errors;

    throw new Error(
      error?.message || 'Could not set contributor isWatching field to true',
    );
  }

  return true;
}
```

**Deletions** ⚰️

- All references for anything related to whitelisting addresses for a Colony have been removed.

## TODO

- Liaise with a fellow dev (most likely @jakubcolony) to make sure that this PR gets merged in at the same time as [block-ingestor#230](https://github.com/JoinColony/block-ingestor/pull/230) since that they are dependent on each other.

Resolves #2314

### CODE REVIEW

File: src/hooks/useIsContributor.ts [hunk 1]
```diff
@@ -0,0 +1,19 @@
...
+const useIsContributor = ({
+  walletAddress = '',
+  colonyAddress = '',
+}: {
+  walletAddress: string | undefined;
+  colonyAddress: string | undefined;
+}) => {
+  const { joinedColonies, loading } = useJoinedColonies(walletAddress);
+
+  const isContributor = joinedColonies
```
Comment (bassgeta) [inline src/hooks/useIsContributor.ts:12]: maybe we could use [array.some](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some)

File: src/redux/sagas/actions/manageVerifiedRecipients.ts [hunk 2]
```diff
@@ -45,7 +45,6 @@ function* manageVerifiedRecipients({
     verifiedAddresses = [],
```
Comment (bassgeta) [inline src/redux/sagas/actions/manageVerifiedRecipients.ts:45]: I think we can actually remove this entire saga and all of its' typedefs

**Review by bassgeta — CHANGES_REQUESTED** [review]
Red lines for days, nice one!
We can probably remove even more things if you're feeling like it, dropped a comment below :point_down: 
Also, feel free to add the latest block-ingestor commit hash to `colony-cdapp-dev-env-block-ingestor`, so you won't need to stop the docker image manually

File: src/hooks/useIsContributor.ts (hunk 1 above)
Comment (rumzledz) [reply src/hooks/useIsContributor.ts]: Great shout @bassgeta ! Pushed!

File: src/redux/sagas/actions/manageVerifiedRecipients.ts (hunk 2 above)
Comment (rumzledz) [reply src/redux/sagas/actions/manageVerifiedRecipients.ts]: Eradicated 👌

File: amplify/backend/api/colonycdapp/schema.graphql [hunk 3]
```diff
@@ -1557,7 +1522,6 @@ enum ClientType {
   TokenClient
   TokenLockingClient
   VotingReputationClient
-  WhitelistClient
```
[the remark this answers is not in the document]
Comment (rumzledz) [reply amplify/backend/api/colonycdapp/schema.graphql:1560]: Hey @iamsamgibbs I have just spoken to Arren so he wants is so that new Contributors who were added via the Manage Verified members flow shouldn't be able to view the Colony right away. They should still have to go through the invite process.

I have amended the block ingestor to reflect this. Can you please re-test this when you have the chance? Thank you! :)

[the remark this answers is not in the document]
Comment (jakubcolony) [reply amplify/backend/api/colonycdapp/schema.graphql:1560]: @rumzledz WhitelistClient refers to one of the extensions (smart contract) that we do not use anymore, but it might be a good idea to keep it in for legacy purposes.

**Review by jakubcolony — CHANGES_REQUESTED** [review]
Great piece of work @rumzledz, functionally almost all works as expected, apart from the fact that newly added addresses are not saved as verified:

image

I'm pretty sure it's because of the `createColonyContributor` call in block-ingestor, I left a separate comment there.

On a side note, when you modify the schema or block-ingestor it's usually handy to provide a query as part of testing instructions as it allows both you and the reviewers to double-check data correctness.

File: amplify/backend/function/validateUserInvite/src/index.js [hunk 4]
```diff
@@ -117,7 +97,30 @@ exports.handler = async (event) => {
...
+      graphqlURL,
+      apiKey,
+    );
+
+    if (
+      colonyMemberIsWatchingMutation.errors ||
+      !colonyMemberIsWatchingMutation.data
+    ) {
+      throw new Error(
+        colonyMemberIsWatchingMutation?.message ||
```
Comment (jakubcolony) [inline amplify/backend/function/validateUserInvite/src/index.js:119]: We ought to get TypeScript into lambdas at some point to catch those early. 

I think this should be:
```ts
colonyMemberIsWatchingMutation.errors[0]?.message
```

**Review by jakubcolony — CHANGES_REQUESTED** [review]
Nice one, just one little fix and we're good to go!

File: amplify/backend/function/validateUserInvite/src/index.js (hunk 4 above)
Comment (rumzledz) [reply amplify/backend/function/validateUserInvite/src/index.js:119]: Ah yes.... my bad 🤦‍♂️

**Review by jakubcolony — DISMISSED** [review]

**Review by iamsamgibbs — APPROVED** [review]
This looks good to me! I've realised we can also remove `RemoveMemberFromColonyWhitelist` from the auth proxy now that it is removed here: https://github.com/JoinColony/colonyCDappAuthProxy/blob/778b274a585c8295e997be18a73da706562c3a57/src/routes/graphql/mutations.ts#L98

File: amplify/backend/api/colonycdapp/schema.graphql [hunk 5]
```diff
@@ -1514,10 +1483,6 @@ type ColonyMetadataChangelog {
   """
   hasAvatarChanged: Boolean!
   """
-  Whether entries in the address book (whitelist) have changed
-  """
-  hasWhitelistChanged: Boolean!
```
Comment (rdig) [inline amplify/backend/api/colonycdapp/schema.graphql:1519]: Will updating this schema require migration ?

File: amplify/backend/function/validateUserInvite/src/index.js [hunk 6]
```diff
@@ -117,7 +97,31 @@ exports.handler = async (event) => {
...
+    );
+
+    if (
+      colonyMemberIsWatchingMutation.errors ||
+      !colonyMemberIsWatchingMutation.data
+    ) {
+      const [error] = colonyMemberIsWatchingMutation.errors;
+
+      throw new Error(
+        error?.message || 'Could not set contributor isWatching field to true',
```
Comment (rdig) [inline amplify/backend/function/validateUserInvite/src/index.js:121]: So I don't think this is right. Since this is a graphql operation it should actually return `null` 

That's how graphql queries/mutation handle if the're an error processing them.

Also, since this is an lambda, you can safely log out errors to the console, as those will not be exposed in the client but rather in the AWS Cloudwatch logs, which helps us debug in production

**Review by rdig — APPROVED** [review]
I'm mostly good with this, but do take into account my comment about the lambda return before you merge

**Review by bassgeta — APPROVED** [review]

**Comment by rumzledz** [comment]
Apologies @JoinColony/dapp-team I had to rebase and update the block ingestor hash as it was pointing to the wrong commit. Can I please get another ✅ then I'll merge asap. Thank you 🙏

**Review by iamsamgibbs — APPROVED** [review]
This looks good, followed the testing steps provided and can verify colony creation and invite flow still works, and I was able to add Fry as a verified member without giving him access to the colony.

Screenshot 2024-06-05 at 09 12 01

Screenshot 2024-06-05 at 09 11 41

Was then able to follow the invite flow for Fry and join correctly.

Screenshot 2024-06-05 at 09 12 40
Screenshot 2024-06-05 at 09 13 32

I think this is basically good to go! Just make sure to create a PR for the auth proxy to remove references to removeMemberFromColony now that it is gone.

**Review by iamsamgibbs — APPROVED** [review]
Still working 👍

**Review by bassgeta — APPROVED** [review]
Still working, let's get this merged :ship:

**Review by davecreaser — APPROVED** [review]
Screenshot 2024-06-07 at 14 15 41

Tested the full flow and all is working as expected. Great job @rumzledz !
