### PR TITLE
Fix `temp-create-data` script

### LINKED ISSUE #463: Fix `temp-create-data` script
Following the latest version upgrade of `colony-js`, the `temp-create-data` no longer works and gives the following error:

```
Error: Cannot find module '../node_modules/@colony/colony-js/dist/cjs/contracts/factories/latest/MetaTxToken__factory.js'
```

Fixing it most likely requires finding out where the `MetaTxToken__factory` lives now (@chmanie you might be able to help here) and updating the import in the script

### PR DESCRIPTION
**Pull request by jakubcolony**
## Description

Following the most recent `colony-js` update in the CDapp, the script got broken. This PR fixes the imports that caused it to fail.

To test, start the dev env and run the script.

Thanks to @chmanie for his assistance.

Resolves #463

### CODE REVIEW

File: scripts/temp-create-data.js [hunk 1]
```diff
@@ -1,9 +1,18 @@
...
+  utils,
+  Wallet,
+  Contract,
+  ContractFactory,
+  providers,
+  BigNumber,
+} = require('ethers');
+
+const colonyJSIColonyNetwork = require('../node_modules/@colony/colony-js/dist/cjs/contracts/factories/IColonyNetwork__factory.js');
+const colonyJSIColony = require('../node_modules/@colony/colony-js/dist/cjs/contracts/IColony/9/factories/IColony__factory.js');
```
Comment (jakubcolony) [inline scripts/temp-create-data.js:11]: These and lines 278-279 and 402 are the only changes. The rest are prettier doing its formatting

**Comment by willm30** [comment]
Nice, I noticed this today and was going to do the same

**Review by Julianahlk — APPROVED** [review]
👍
