### PR TITLE
[Arbitrary Txs] Fix array encoding issue

### LINKED ISSUE #4124: [Arbitrary Txs] Array encoding issue
## Steps to reproduce

Reproducing this is kinda cumbersome, with the easiest way being deploying our own test contract.

Follow steps 1-5 from #3966, but replace the contents of `TestContract.sol` with the following:

```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

contract TestContract {
    function testFunction(uint256[] memory numbers) public {}
}
```

Once the contract is deployed, add a transaction with its address and the following JSON ABI:
```json
[
  {
    "inputs": [
      {
        "internalType": "uint256[]",
        "name": "numbers",
        "type": "uint256[]"
      }
    ],
    "name": "testFunction",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
]
```

Select the `testFunction` and enter any value that is a valid array of integers (`[]`, `[1, 2, 3]`, and so on).

Submit the form.

## Expected behaviour

The transaction goes through successfully.

## Actual behaviour

The saga throws an error and silently fails. This is because ethers' `encodeFunctionData` is expecting a first-class array but it is passed the string representation instead.

### PR DESCRIPTION
**Pull request by jakubcolony**
## Description

This PR fixes an issue with array encoding when creating arbitrary transactions. The cause of the issue was passing a string representation of an array (e.g. `"[]"`) instead of a "first-class" JS array.

It also improves the decoding of array arguments when showing a completed action.

## Testing

To ensure thorough coverage, we'll deploy a test contract that has a function with nearly all possible argument types.

### Deploying test contract

1. Ensure your dev env is fully running.
2. Create a new file called `TestContract.sol` in your CDapp root directory with the following contents:
```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

contract TestContract {
    function testFunction(
        uint256 uint256Arg,
        uint256[] memory uint256ArrayArg,
        uint256[][] memory uint256NestedArrayArg,
        bool boolArg,
        bool[] memory boolArrayArg,
        address addressArg,
        address[] memory addressArrayArg,
        bytes memory bytesArg,
        bytes[] memory bytesArrayArg,
        string memory stringArg,
        string[] memory stringArrayArg
    ) public {}
}
```
3. Run the following in your terminal to copy the contract over to the network container and compile it:
```bash
docker cp TestContract.sol network:/colonyCDappBackend/colonyNetwork/contracts && docker exec -it -w /colonyCDappBackend/colonyNetwork network npx hardhat compile
```
4. Start the hardhat console with `npm run hardhat`, then run the following code line-by-line:
```js
cf = await ethers.getContractFactory('TestContract')
c = await cf.deploy()
c.address
```
The last expression will print the address of the newly deployed contract. Copy it for later use.

### Testing arbitrary transactions

1. Create new arbitrary transaction action.
2. In the modal, paste the deployed contract address and the following JSON ABI:
```json
[
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "uint256Arg",
        "type": "uint256"
      },
      {
        "internalType": "uint256[]",
        "name": "uint256ArrayArg",
        "type": "uint256[]"
      },
      {
        "internalType": "uint256[][]",
        "name": "uint256NestedArrayArg",
        "type": "uint256[][]"
      },
      {
        "internalType": "bool",
        "name": "boolArg",
        "type": "bool"
      },
      {
        "internalType": "bool[]",
        "name": "boolArrayArg",
        "type": "bool[]"
      },
      {
        "internalType": "address",
        "name": "addressArg",
        "type": "address"
      },
      {
        "internalType": "address[]",
        "name": "addressArrayArg",
        "type": "address[]"
      },
      {
        "internalType": "bytes",
        "name": "bytesArg",
        "type": "bytes"
      },
      {
        "internalType": "bytes[]",
        "name": "bytesArrayArg",
        "type": "bytes[]"
      },
      {
        "internalType": "string",
        "name": "stringArg",
        "type": "string"
      },
      {
        "internalType": "string[]",
        "name": "stringArrayArg",
        "type": "string[]"
      }
    ],
    "name": "testFunction",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
]
```

3. Select `testFunction` from the dropdown, and fill the fields with correct values according to their type. For example:
- uint256Arg: `123456789`
- uint256ArrayArg: `[123, 456, 789]`
- uint256NestedArrayArg: `[[1, 2], [3, 4, 5]]`
- boolArg: `true`
- boolArrayArg: `[true, false, true]`
- addressArg: `0x742d35Cc6634C0532925a3b844Bc454e4438f44e`
- addressArrayArg: `[0x742d35Cc6634C0532925a3b844Bc454e4438f44e, 0x5B38Da6a701c568545dCfcB03FcB875f56beddC4]`
- bytesArg: `0xFF`
- bytesArrayArg: `[0xFF, 0xAA]`
- stringArg: `Hello World`
- stringArrayArg: `["Hello", "World", "Blockchain"]`

4. Submit the form. The transaction should go through and you should see the decoded arguments in the temporary completed action view.

5. Repeat the steps using reputation or multi-sig decision method (both use the same code).

image

Resolves #4124

### CODE REVIEW

File: src/redux/sagas/utils/arbitraryTxs.ts [hunk 1]
```diff
@@ -0,0 +1,80 @@
+import { Interface } from 'ethers/lib/utils';
+
+import { type AddTransactionTableModel } from '~v5/common/ActionSidebar/partials/forms/ArbitraryTxsForm/types.ts';
+
+/**
+ * Parses a string representation of an array into an array of values.
+ * It supports nested arrays and handles strings within arrays.
+ */
+const getArrayFromString = (value: string, type: string) => {
```
Comment (jakubcolony) [inline src/redux/sagas/utils/arbitraryTxs.ts:9]: This is loosely based on [Dapp implementation](https://github.com/JoinColony/colonyDapp/blob/c9ee24059989f5c285be700799242443986992fb/src/utils/safes/contractParserValidation.ts#L61) but has further improvements such as actually parsing nested arrays and handling potentially confusing strings containing commas and brackets (e.g. `["[", ","]`).

**Review by Nortsova — DISMISSED** [review]
Great work! Thanks for fixing this bug and testing every possible arg type 👏 

Created a Custom transaction with all following arguments:
image

Successfully decoded:
image

Multi-sig works good too:
image

File: src/redux/sagas/utils/arbitraryTxs.ts [hunk 2]
```diff
@@ -0,0 +1,80 @@
...
+  if (value === '[]') {
+    return [];
+  }
+
+  if (!value.startsWith('[') || !value.endsWith(']')) {
+    throw new Error('Invalid array format');
```
Comment (Nortsova) [inline src/redux/sagas/utils/arbitraryTxs.ts:15]: I would propose moving this to translation.

**Review by mmioana — APPROVED** [review]
Amazing work @jakubcolony 🥇 

Created a custom transaction via `Permissions` with the provided values
Screenshot 2025-01-21 at 10 30 59
Created another custom transaction via `Reputation`
Screenshot 2025-01-21 at 10 32 58

Really nice implementation for the `getArrayFromString` utils 👍

**Review by Nortsova — APPROVED** [review]
Reapproving after base branch changed ✅ 

image

**Review by iamsamgibbs — APPROVED** [review]
Great job with this and thanks for providing the test contract, super helpful! Nice implementation of `getArrayFromString` too.

Screenshot 2025-01-21 at 11 42 07

Screenshot 2025-01-21 at 11 42 33

Screenshot 2025-01-21 at 11 44 39

File: src/redux/sagas/utils/arbitraryTxs.ts (hunk 2 above)
Comment (jakubcolony) [reply src/redux/sagas/utils/arbitraryTxs.ts:15]: Thanks for the suggestion! I had a look throughout the codebase and could not see a pattern of using translations for thrown errors. I also think of this error as a last resort, invalid arrays should have been validated in the UI before getting to this util.
