### PR TITLE
fix: Not able to finalize agreements

### LINKED ISSUE #1876: Not able to "Finalize" agreements
## Steps to reproduce

1. Create a new Agreement.
2. Go through the whole process of supporting the Agreement.
3. Click on the "Finalize" button.
4. You won't be able to finalize or return stakes, and there will be an error in the console.

Note: There is no transaction that is being performed or needing to be performed other then the returning of stakes. The usage of the "Finalize" text here is keep it consistent with other actions.

## Expected behaviour

* When in the "Finalize" step, clicking the "Finalize" button should only return all user stakes.
* When all stakes have been returned, there should not be a finalize button anymore. 
* This should be the same process when the Agreement has failed. i.e. stakes can be returned when clicking "Finalize".

## Actual behaviour

* You are not able to finalize the agreement and stakes are not able to be returned.
* If you claim back stakes via the Userhub stakes tab and return to the finalize step of the agreement, the finalize button will still be visible despite there being no stakes left to be returned.

### PR DESCRIPTION
**Pull request by warrencolliver**
## Description

This PR fixes the issue which was occuring when trying to finalize an agreement / decision action. this was done by adding a condition so agreements used `MOTION_CLAIM` instead of `MOTION_FINALIZE`. By doing this the stakes can be returned to the user and the agreement is closed. When the agreement is at the 'Finalize' step, the button should also be labelled 'Return Stakes' rather than 'Claim' like other actions. 

## Testing

* Install reputation extension
* Create agreement motion and go through the steps
* Get to finalize step, and return the stakes

Expected result: you should not see any errors and the stakes are returned to the user:
finalizeagreements

You can also repeat these steps but instead of claiming via the motion 'Return stakes' claim via the user hub and check if the decision finalizes without any issues.

## Diffs

**Changes** 🏗
Decision motion check added into finalizeStep to use MOTION_CLAIM to theoretically 'finalize' the motion  

Resolves #1876

### CODE REVIEW

**Review by iamsamgibbs — CHANGES_REQUESTED** [review]
This looks good and all works as expected! Just one small change: would be better if `formatText` took in an id from `src/il8n/en.json`

**Review by iamsamgibbs — APPROVED** [review]

File: src/components/v5/common/ActionSidebar/partials/Motions/steps/FinalizeStep/FinalizeStep.tsx [hunk 1]
```diff
@@ -84,7 +85,8 @@ const FinalizeStep: FC<FinalizeStepProps> = ({
   };
   if (
     actionData.motionData.isFinalized ||
-    actionData.motionData.motionStateHistory.hasFailedNotFinalizable
+    actionData.motionData.motionStateHistory.hasFailedNotFinalizable ||
+    actionData.type === ColonyActionType.CreateDecisionMotion
```
Comment (bassgeta) [inline src/components/v5/common/ActionSidebar/partials/Motions/steps/FinalizeStep/FinalizeStep.tsx:89]: maybe we could put this (perhaps some other too) into boolean variables for improved readability

**Review by bassgeta — CHANGES_REQUESTED** [review]
Works like a charm, just dropped a comment if we may want to wrap some if statements into variables for more readability. Not necessary tho, just some QoL improvements :)

File: src/components/v5/common/ActionSidebar/partials/Motions/steps/FinalizeStep/FinalizeStep.tsx [hunk 2]
```diff
@@ -175,28 +180,32 @@ const FinalizeStep: FC<FinalizeStepProps> = ({
...
-                        text={formatText({
-                          id: buttonTextId,
-                        })}
+                        text={
+                          isMotionAgreement
+                            ? formatText({
+                                id: 'motion.finalizeStep.returnStakes',
+                              })
+                            : formatText({ id: buttonTextId })
+                        }
```
Comment (ArmandoGraterol) [inline src/components/v5/common/ActionSidebar/partials/Motions/steps/FinalizeStep/FinalizeStep.tsx:208]: A small nitpick but this way we avoid repetition:
```
formatText({ id: isMotionAgreement ? 'motion.finalizeStep.returnStakes' : buttonTextId })
```

**Review by ArmandoGraterol — CHANGES_REQUESTED** [review]
Nice job Warren! Just left a nitpick but after that this should be good to go from my side

**Review by ArmandoGraterol — DISMISSED** [review]
LGTM 👍 Thank you for the changes

**Review by iamsamgibbs — APPROVED** [review]
Looks good to me!
