### PR TITLE
fix: Update the total balances currency conversion arithmetic

### LINKED ISSUE #2334: Currency conversion balances are not showing correctly on dashboard
## Description

Currency conversion balances are not showing correctly on dashboard.

This is noticeable in this colony - https://app.colony.io/boston

This was resolved in this PR previously, but for the balances page - https://github.com/JoinColony/colonyCDapp/issues/1936

## Expected behaviour

* You should see accurate total funds balance in the user denominated currency.

## Actual behaviour

* Total funds balance is not showing accurately in the users denominated currency.

image

### PR DESCRIPTION
**Pull request by rumzledz**
## Description

Previously, we were converting the wei version of the balance by its currency equivalent which was producing a "wei-like" format of the conversion price.

In this PR, it is now first converting the wei version of the balance to its unit version before applying the final currency conversion.
 
## Testing

1. Visit your Colony's Balances page
2. Take note of the "Total funds" value
3. Click on the the Total Funds cell
4. Verify that it matches the "Balance" value for ETH

## Diffs

**Changes** 🏗

Added an extra step to first derive the non-wei value of the token's balance prior to finalising its currency conversion.

| before | after |
| ------ | ------ |
| Screenshot 2024-05-23 at 00 15 39 | image |

Resolves #2334

### CODE REVIEW

File: src/components/v5/frame/ColonyHome/partials/TokenBalance/hooks.ts [hunk 1]
```diff
@@ -27,7 +27,11 @@ const calculateTotalFunds = async (
           isError = true;
         }
 
-        return (await total).add(new Decimal(balance).mul(currentPrice ?? 0));
+        const balanceInWeiToToken = new Decimal(balance).div(10 ** decimals);
```
Comment (jakubcolony) [inline src/components/v5/frame/ColonyHome/partials/TokenBalance/hooks.ts:30]: It's gonna be a nit-pick, it all works correct but since you're dividing by 10^decimals, the result is ETH rather than WEI. Would you mind updating the naming to reflect that?

**Review by jakubcolony — APPROVED** [review]
The balance looks correct now, great work!
Screenshot 2024-05-23 at 11 25 32

I also checked the balance table to make sure there was no regression there:
Screenshot 2024-05-23 at 11 25 39

File: src/components/v5/frame/ColonyHome/partials/TokenBalance/hooks.ts (hunk 1 above)
Comment (rumzledz) [reply src/components/v5/frame/ColonyHome/partials/TokenBalance/hooks.ts:30]: @jakubcolony oh I was under the impression that because this loop is going through your balances, I thought that you will also have non-ETH token balances in there with their own respective decimals as well which is why I wanted to call it something generic like "Token"

Comment (rumzledz) [reply src/components/v5/frame/ColonyHome/partials/TokenBalance/hooks.ts]: @jakubcolony thanks for explaining that ETH could also mean the actual token unit, and is not just talking specifically about the Ethereum token! Changes pushed! 🚀

**Review by jakubcolony — APPROVED** [review]

**Review by rdig — APPROVED** [review]
All good.

However, as a side note I want to mention that we really should stop using `Decimals` as a lib as it's really error prone.

We should change it instead to just be used via BigNumber (or BigInt, if we refactor everything)
