### PR TITLE
Fix: Modal button alignment on mobile

### LINKED ISSUE #3291: Mobile: Activate & Withdraw token modal button alignments
## Description

On mobile, the CTA buttons within the 'Activate' and 'Withdraw' modals that are triggered from inside the user hub, should be stickied to the bottom of the screen to keep a consistent UX across the application. 

**Currently on production:**

image
image

What the main CTA and cancel buttons should be as per Figma:

image
image

Figma links: https://www.figma.com/design/5V8pr7iMwXsT9L3VAZsmUt/Actions%2C-Motions-%26-Finances?node-id=27608-299118&t=NI6ujUbP6pUmUaZy-4

### PR DESCRIPTION
**Pull request by iamsamgibbs**
## Description

On mobile, the CTA buttons for all modals should be aligned to the bottom.

## Testing

Check any modals on mobile and ensure the buttons are aligned to the bottom.

* Activate tokens (accessed via userhub)
* Withdraw tokens (accessed via userhub)
* Uninstall extension confirmation
* Re-enable extension confirmation

(Note there is a separate issue for the UserHub icons blocking the close modal button which is out of scope for this PR - #3440)

Screenshot 2024-10-23 at 15 44 38

Confirm that modals have not broken on desktop, or that other modals which do not have buttons (such as the activity feed filters) still work as expected.

## Diffs

**Changes** 🏗

* Modal should take up full height on mobile and align buttons to bottom

Resolves #3291

### CODE REVIEW

**Review by mmioana — APPROVED** [review]
Thanks for the changes @iamsamgibbs now the action buttons are shown to the bottom of the modal 😍 

The tokens modals on mobile and desktop ✅ 
Screenshot 2024-10-24 at 12 03 46
Screenshot 2024-10-24 at 12 03 57
Screenshot 2024-10-24 at 12 04 20
Screenshot 2024-10-24 at 12 04 27

The extension modals ✅ 
Screenshot 2024-10-24 at 12 05 16
Screenshot 2024-10-24 at 12 05 25
Screenshot 2024-10-24 at 12 05 39
Screenshot 2024-10-24 at 12 05 43
Screenshot 2024-10-24 at 12 05 51
Screenshot 2024-10-24 at 12 05 58

And also checked the members modal that is shown on mobile ✅ 
Screenshot 2024-10-24 at 12 09 05

Nice job fixing this issue! 🎉

**Review by rdig — APPROVED** [review]
Everything seems to be aligned properly to the bottom now. Nicely done.

Screenshot from 2024-10-24 20-25-39
Screenshot from 2024-10-24 20-25-52
Screenshot from 2024-10-24 20-25-54
Screenshot from 2024-10-24 20-26-13
Screenshot from 2024-10-24 20-26-23
Screenshot from 2024-10-24 20-27-18

File: src/components/v5/shared/Modal/Modal.tsx [hunk 1]
```diff
@@ -92,7 +92,7 @@ const Modal: FC<PropsWithChildren<ModalProps>> = ({
           />
           <div
             className={clsx(
-              'flex w-full flex-grow flex-col [-webkit-overflow-scrolling:touch]',
+              'flex h-full w-full flex-grow flex-col [-webkit-overflow-scrolling:touch]',
```
Comment (rumzledz) [inline src/components/v5/shared/Modal/Modal.tsx:95]: 👌

**Review by rumzledz — APPROVED** [review]
Clean fix @iamsamgibbs ! Can confirm it in the following places:


Screenshot 2024-10-25 at 22 30 14
Screenshot 2024-10-25 at 22 30 01
Screenshot 2024-10-25 at 22 29 52
Screenshot 2024-10-25 at 22 29 07
Screenshot 2024-10-25 at 22 28 59
