### PR TITLE
Fix: handle loading state for the Crypto to Fiat tab components

### LINKED ISSUE #2747: Crypto-to-fiat: Improve loading state of steps and statuses
## Steps to reproduce

1. Complete Crypto to fiat set up process including both verification and bank details.
2. Reload the page and pay attention to the various loading states of detail fields, statuses and buttons.

## Expected behaviour

* The loading states should match the design. 
    - Figma link: https://www.figma.com/design/C2grfQysdsYXz0j4rADR6K/Crypto-to-Fiat?node-id=5228-20881&t=nfPCOjHxSPe4WuP4-4
 
image

## Actual behaviour

* The loading state is broken and shows inaccurate information to the user.

loading-state-crypto

image

### PR DESCRIPTION
**Pull request by rumzledz**
## Description

loader

## Secrets setup

> [!IMPORTANT]
> If you haven't done the secrets file set up yet, expand this section:

<details>
<summary><h4>Click to expand and view the secrets setup 👈 🤫 </h4></summary>

### Setting up your local environment

Create a `.env.local.secrets` file in the parent directory and populate it with the correct environment variables:
```console
echo -e "BSCSCAN_API_KEY=\nETHERSCAN_API_KEY=\nGOOGLE_TAG_MANAGER_ID=\nPINATA_API_KEY=\nPINATA_API_SECRET=\nCOINGECKO_API_KEY=\nCOINGECKO_API_URL=\nPOSTHOG_KEY=\nPOSTHOG_HOST=\nUSDC_LOCAL_ADDRESS=\nPERSONA_ENVIRONMENT_ID=" > .env.local.secrets
```
Once the `.env.local.secrets` file is created, open it and you should see the following content. You will need to provide values for `POSTHOG_KEY` and `POSTHOG_HOST` so please ask a fellow dev about this.
```js
BSCSCAN_API_KEY=
ETHERSCAN_API_KEY=
GOOGLE_TAG_MANAGER_ID=
PINATA_API_KEY=
PINATA_API_SECRET=
COINGECKO_API_KEY=
COINGECKO_API_URL=
POSTHOG_KEY=
POSTHOG_HOST=
USDC_LOCAL_ADDRESS=
```
Once you've provided values for `POSTHOG_KEY` and `POSTHOG_HOST`, inject them:
```console
npm run prepare
```

</details>

## Testing

> [!IMPORTANT]
> Open the `amplify/backend/function/bridgeXYZMutation/src/index.js` file and make sure you enter the right sandbox api key. Otherwise, you won't be able to do the KYC flow:
> ```js
> // Use the sandbox API key instead of 'xxx'
> let apiKey = 'xxx';
> ```
> Enable the Crypto to Fiat tab via our Feature Flag. I'm sure there's a better way to do this but open the `src/context/FeatureFlagsContext/FeatureFlagsContextProvider.tsx` file and do the following replacement:
> ```js
> // From
> [FeatureFlag.CRYPTO_TO_FIAT]: cryptoToFiatFeature
> // To
> [FeatureFlag.CRYPTO_TO_FIAT]: { isEnabled: true }
> ```

1. Visit your account settings page
2. Click the Crypto to fiat tab
3. Complete Step 1 Verification
4. Once you're approved, just reload the page
5. Check that you can see the loading states

## Diffs

**New stuff** ✨

* A new HoC component that renders a configurable Skeleton loader when you give it a truthy value for its `isLoading` prop

**Changes** 🛠️

* The page is now using the `loading` state from the `useCheckKycStatusMutation` GraphQL call to detect if the request is busy

Resolves #2747

### CODE REVIEW

File: src/components/common/HocWithLoading/HocWithLoading.tsx [hunk 1]
```diff
@@ -0,0 +1,22 @@
+import clsx from 'clsx';
+import React from 'react';
+
+import { type HocWithLoadingProps } from './types.ts';
+
+const hocWithLoading = <P extends object>(
```
Comment (jakubcolony) [inline src/components/common/HocWithLoading/HocWithLoading.tsx:6]: A good old HOC! I'm just wondering if having a "composable" component wouldn't be a more flexible solution? 

```tsx
<LoadingSkeleton isLoading={...}>
  <Component />
</LoadingSkeleton>
```

At the same time I don't have a strong argument against a HOC, so feel free to leave it in

**Review by jakubcolony — DISMISSED** [review]
The initial load with no data is indeed very quick and hard to test 😄 

With all details filled and throttled network speed, the loading looks great:


https://github.com/user-attachments/assets/e74cea6a-3abc-4689-a125-1c07be92c334

Nice work Romeo 👍

File: src/components/common/HocWithLoading/HocWithLoading.tsx (hunk 1 above)
Comment (rumzledz) [reply src/components/common/HocWithLoading/HocWithLoading.tsx:6]: Thanks for reviewing this @jakubcolony! It's a good thing you mentioned this because it reminded me of some stashed changes I have about passing KYC state! 😂 

I thought this a HOC was really neat because it saves us a few lines of code if used extensively and all we have to worry about really is making it load or not, and some dimensions config as well. But having said that, I think composition would be preferable as it aligns with the composition changes I did for the KYC page.

I'll be making this change and will also push the stashed changes I was referring to. It's basically just wrapping the page in a Context Provider which also exposes the mutation we use to get the KYC. Should be helpful when we want to refetch the data at any given time i.e. when the KYC flow has succeeded, we can refetch to refresh the data of the page 👌

**Review by melyndav — CHANGES_REQUESTED** [review]
Hey @rumzledz! Nice start on handling the skeletons for c2f! A couple of points of feedback just for a consistency from a UI perspective from Figma but also global skeleton implementation.

Bank details currently:

image

Figma:

image


Current pills:

image

Figma: 

image

 
 
Again, great start! 👍

**Comment by rumzledz** [comment]
> Hey @rumzledz! Nice start on handling the skeletons for c2f! A couple of points of feedback just for a consistency from a UI perspective from Figma but also global skeleton implementation.

Apologies, I broke it after pushing some changes yesterday 🤦‍♂️ Should be okay now @melyndav

**Review by rdig — DISMISSED** [review]
Nicely done. Loading states (that are part of this PR) work as expected / described. Tested both mobile and desktop


Screenshot from 2024-07-26 00-42-46
Screenshot from 2024-07-26 00-42-47
Screenshot from 2024-07-26 00-43-20
Screenshot from 2024-07-26 00-43-23

Just pointing out, as I did on Jakub's #2761 that the full page loader for the off ramp tab is mis-alined on desktop, and on mobile the colony logo is being cut off

Screenshot from 2024-07-26 00-42-28
Screenshot from 2024-07-26 00-43-11

**Review by melyndav — CHANGES_REQUESTED** [review]
Hey @rumzledz! Nice work on the updates and appreciate the quick fixes. 

Everything is looking good as per my previous comment:

image

image

**One request:**

Can we remove this page loader (across all responsive) since we're now implementing skeleton loaders? We don't need two loading states here (and also fixes the alignment issue). 

image

**Comment by rumzledz** [comment]
@rdig @melyndav yep that loader component is indeed horrendous 🫨 I shall remove it @melyndav !

**Comment by rumzledz** [comment]
@melyndav I've just pushed the changes 👌

**Review by jakubcolony — DISMISSED** [review]
Thanks for addressing the feedback @rumzledz, LGTM 👍 


https://github.com/user-attachments/assets/d8679129-efd3-49f9-97d9-dfb6e58c777b

**Review by melyndav — DISMISSED** [review]
Nice work on removing that extra page loader, the skeletons are a much nicer user experience. Thank @rumzledz for your work on this one. 🥳

**Review by rdig — DISMISSED** [review]
Yup, can confirm that wonky state is now gone, replaced by a blank screen.

Screenshot from 2024-07-30 00-44-48
Screenshot from 2024-07-30 00-44-49

Screenshot from 2024-07-30 00-46-55
Screenshot from 2024-07-30 00-47-00

Please however rebase this before merging, as it's got quite a number of conflicts _(or at least that's what Github claims)_

**Comment by rumzledz** [comment]
Hey @rdig @melyndav @jakubcolony , I had to rebase this and the ticks went away. Can you please review it again when you get the chance? Thank you!

**Review by jakubcolony — APPROVED** [review]

**Review by rdig — APPROVED** [review]
Re-approving

**Review by melyndav — APPROVED** [review]
Re-approving this one @rumzledz! 💯
